Repository openshift-eng/ocp-build-data, pull requests merged in 2018-12, with the labels that each got.

#24 Add bugzilla metadata for use in elliott
  openshift-3.10/bugzilla.yml
  openshift-3.11/bugzilla.yml
  openshift-3.3/bugzilla.yml
  openshift-3.4/bugzilla.yml
  openshift-3.5/bugzilla.yml
  openshift-3.6/bugzilla.yml
  openshift-3.7/bugzilla.yml
  openshift-3.8/bugzilla.yml
  openshift-3.9/bugzilla.yml
  openshift-4.0/bugzilla.yml
Labels: lgtm, size/L

#25 Add errata tool data
  openshift-3.10/erratatool.yml
  openshift-3.11/erratatool.yml
  openshift-3.3/erratatool.yml
  openshift-3.4/erratatool.yml
  openshift-3.5/erratatool.yml
  openshift-3.6/erratatool.yml
  openshift-3.7/erratatool.yml
  openshift-3.8/erratatool.yml
  openshift-3.9/erratatool.yml
Labels: size/L

#23 Multistage build for prometheus-operator images
  openshift-4.0/images/prometheus-config-reloader.yml
  openshift-4.0/images/prometheus-operator.yml
Labels: lgtm, size/XS

#22 Fix licenses of Prometheus images
  openshift-3.11/images/golang-github-prometheus-alertmanager.yml
  openshift-3.11/images/golang-github-prometheus-node_exporter.yml
  openshift-3.11/images/golang-github-prometheus-prometheus.yml
  openshift-4.0/images/golang-github-prometheus-alertmanager.yml
  openshift-4.0/images/golang-github-prometheus-node_exporter.yml
  openshift-4.0/images/golang-github-prometheus-prometheus.yml
Labels: lgtm, size/S

#20 ART-264 adding ignition rpm
  openshift-4.0/group.yml
  openshift-4.0/rpms/ignition.yml
Labels: lgtm, size/S

#28 update alertmanager and node_exporter to use multi-stage
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
Labels: size/XS

#27 remove prometheus-alert-buffer
  images/golang-github-openshift-prometheus-alert-buffer.yml
Labels: size/S

#29 update image names for alertmanager and node_exporter
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
Labels: size/XS
