Repository openshift-eng/ocp-build-data, pull requests merged in 2018-11, with the labels that each got.

#1 openshift-3.11: use version vars for cluster-monitoring-operator
  openshift-3.11/group.yml
Labels: lgtm, size/XS

#5 update monitoring projects branches
  openshift-3.11/group.yml
  openshift-4.0/group.yml
Labels: size/M

#7 3.10: put puddle repo name back
  openshift-3.10/group.yml
  openshift-3.10/images/aos3-installation.yml
  openshift-3.10/images/atomic-openshift-descheduler.yml
  openshift-3.10/images/atomic-openshift-node-problem-detector.yml
  openshift-3.10/images/csi-attacher.yml
  openshift-3.10/images/csi-driver-registrar.yml
  openshift-3.10/images/csi-livenessprobe.yml
  openshift-3.10/images/csi-provisioner.yml
  openshift-3.10/images/efs-provisioner.yml
  openshift-3.10/images/golang-github-openshift-oauth-proxy.yml
  openshift-3.10/images/golang-github-openshift-prometheus-alert-buffer.yml
  openshift-3.10/images/golang-github-prometheus-alertmanager.yml
  openshift-3.10/images/golang-github-prometheus-node_exporter.yml
  openshift-3.10/images/golang-github-prometheus-prometheus.yml
  openshift-3.10/images/image-inspector.yml
  openshift-3.10/images/jenkins-agent-nodejs-8-rhel7.yml
  openshift-3.10/images/logging-auth-proxy.yml
  openshift-3.10/images/logging-curator.yml
  openshift-3.10/images/logging-elasticsearch.yml
  openshift-3.10/images/logging-eventrouter.yml
  openshift-3.10/images/logging-fluentd.yml
  openshift-3.10/images/logging-kibana.yml
  openshift-3.10/images/metrics-hawkular-openshift-agent.yml
  openshift-3.10/images/metrics-heapster.yml
  openshift-3.10/images/openshift-enterprise-apb-base.yml
  openshift-3.10/images/openshift-enterprise-apb.yml
  openshift-3.10/images/openshift-enterprise-asb.yml
  openshift-3.10/images/openshift-enterprise-cli.yml
  openshift-3.10/images/openshift-enterprise-cluster-capacity.yml
  openshift-3.10/images/openshift-enterprise-egress-dns-proxy.yml
  openshift-3.10/images/openshift-enterprise-haproxy-router.yml
  openshift-3.10/images/openshift-enterprise-hyperkube.yml
  openshift-3.10/images/openshift-enterprise-hypershift.yml
  openshift-3.10/images/openshift-enterprise-mariadb.yml
  openshift-3.10/images/openshift-enterprise-mediawiki.apb.yml
  openshift-3.10/images/openshift-enterprise-mediawiki.container.yml
  openshift-3.10/images/openshift-enterprise-mysql.yml
  openshift-3.10/images/openshift-enterprise-node.yml
  openshift-3.10/images/openshift-enterprise-pod.yml
  openshift-3.10/images/openshift-enterprise-postgresql.yml
  openshift-3.10/images/openshift-enterprise-registry.yml
  openshift-3.10/images/openshift-enterprise-service-catalog.yml
  openshift-3.10/images/openshift-enterprise.yml
  openshift-3.10/images/openshift-jenkins-2.yml
  openshift-3.10/images/openshift-local-storage.yml
  openshift-3.10/images/openshift-manila-provisioner.yml
  openshift-3.10/images/openshift-monitor-project-lifecycle.yml
  openshift-3.10/images/openshift-monitor-sample-app.yml
  openshift-3.10/images/origin-web-console-server.yml
  openshift-3.10/images/registry-console.yml
  openshift-3.10/images/snapshot-controller.yml
  openshift-3.10/images/snapshot-provisioner.yml
  openshift-3.10/images/template-service-broker.yml
Labels: size/L

#8 update openshift/grafana repo to build from 'master'
  openshift-3.11/group.yml
  openshift-4.0/group.yml
Labels: lgtm, size/XS

#4 Update reporting operator Dockerfile source
  openshift-4.0/images/ose-metering-reporting-operator.yml
Labels: size/XS

#9 updating yaml file to reflect current values for ownership and Docker…
  openshift-4.0/images/coredns.yml
Labels: size/XS

#2 invoke script to update console sources at rebase
  modifications/README
  modifications/update-console-sources
  openshift-3.11/images/openshift-enterprise-console.yml
  openshift-4.0/images/openshift-enterprise-console.yml
Labels: size/L

#12 prepare for 3.11 ppc64le builds
  openshift-3.11/group.yml
  openshift-3.11/images/aos3-installation.yml
  openshift-3.11/images/atomic-openshift-cluster-autoscaler.yml
  openshift-3.11/images/atomic-openshift-descheduler.yml
  openshift-3.11/images/atomic-openshift-metrics-server.yml
  openshift-3.11/images/atomic-openshift-node-problem-detector.yml
  openshift-3.11/images/automation-broker-apb.yml
  openshift-3.11/images/csi-attacher.yml
  openshift-3.11/images/csi-driver-registrar.yml
  openshift-3.11/images/csi-livenessprobe.yml
  openshift-3.11/images/csi-provisioner.yml
  openshift-3.11/images/efs-provisioner.yml
  openshift-3.11/images/golang-github-openshift-oauth-proxy.yml
  openshift-3.11/images/golang-github-openshift-prometheus-alert-buffer.yml
  openshift-3.11/images/golang-github-prometheus-alertmanager.yml
  openshift-3.11/images/golang-github-prometheus-node_exporter.yml
  openshift-3.11/images/golang-github-prometheus-prometheus.yml
  openshift-3.11/images/image-inspector.yml
  openshift-3.11/images/jenkins-agent-nodejs-8-rhel7.yml
  openshift-3.11/images/logging-curator5.yml
  openshift-3.11/images/logging-elasticsearch5.yml
  openshift-3.11/images/logging-eventrouter.yml
  openshift-3.11/images/logging-fluentd.yml
  openshift-3.11/images/logging-kibana5.yml
  openshift-3.11/images/manila-provisioner.yml
  openshift-3.11/images/metrics-hawkular-openshift-agent.yml
  openshift-3.11/images/metrics-heapster.yml
  openshift-3.11/images/openshift-enterprise-apb-base.yml
  openshift-3.11/images/openshift-enterprise-apb.yml
  openshift-3.11/images/openshift-enterprise-asb.yml
  openshift-3.11/images/openshift-enterprise-autoheal.yml
  openshift-3.11/images/openshift-enterprise-cli.yml
  openshift-3.11/images/openshift-enterprise-cluster-capacity.yml
  openshift-3.11/images/openshift-enterprise-egress-dns-proxy.yml
  openshift-3.11/images/openshift-enterprise-haproxy-router.yml
  openshift-3.11/images/openshift-enterprise-hyperkube.yml
  openshift-3.11/images/openshift-enterprise-hypershift.yml
  openshift-3.11/images/openshift-enterprise-mariadb.yml
  openshift-3.11/images/openshift-enterprise-mediawiki.apb.yml
  openshift-3.11/images/openshift-enterprise-mediawiki.container.yml
  openshift-3.11/images/openshift-enterprise-mysql.yml
  openshift-3.11/images/openshift-enterprise-node.yml
  openshift-3.11/images/openshift-enterprise-pod.yml
  openshift-3.11/images/openshift-enterprise-postgresql.yml
  openshift-3.11/images/openshift-enterprise-registry.yml
  openshift-3.11/images/openshift-enterprise-service-catalog.yml
  openshift-3.11/images/openshift-enterprise-service-idler.yml
  openshift-3.11/images/openshift-enterprise-tests.yml
  openshift-3.11/images/openshift-enterprise.yml
  openshift-3.11/images/openshift-jenkins-2.yml
  openshift-3.11/images/openshift-local-storage.yml
  openshift-3.11/images/openshift-manila-provisioner.yml
  openshift-3.11/images/origin-web-console-server.yml
  openshift-3.11/images/ose-ovn-kubernetes.yml
  openshift-3.11/images/registry-console.yml
  openshift-3.11/images/snapshot-controller.yml
  openshift-3.11/images/snapshot-provisioner.yml
  openshift-3.11/images/template-service-broker.yml
Labels: size/L

#13 add / to ppc64le repo
  openshift-3.11/group.yml
Labels: size/XS

#14 fixing misc errors mostly dockerfile locations, builders, and file names
  openshift-4.0/images/cluster-node-tuning-operator.yml
  openshift-4.0/images/ose-containernetworking-plugins-unsupported.yml
  openshift-4.0/images/ose-containernetworking-plugins.yml
  openshift-4.0/images/ose-hadoop.yml
  openshift-4.0/images/ose-hive.yml
  openshift-4.0/images/telemeter.yml
  openshift-4.0/images/tuned.yml
Labels: size/S

#15 fixing hadoop/hive names so they match distgit names
  openshift-4.0/images/hadoop.yml
  openshift-4.0/images/hive.yml
Labels: size/XS

#17 openshift-4.0: etcd
  openshift-4.0/group.yml
  openshift-4.0/images/ose-etcd.yml
Labels: size/S

#19 ART-356 adding cluster-nfd-operator.yml
  openshift-4.0/group.yml
  openshift-4.0/images/cluster-nfd-operator.yml
Labels: size/S
