Repository openshift-eng/ocp-build-data, pull requests merged in 2019-12, with the labels that each got.

#241 [ART-839][ART-1343] Add operator_image_ref_mode to group.yml
  group.yml
Labels: size/XS

#242 [ART-839][ART-1343] Add operator_image_ref_mode to group.yml
  group.yml
Labels: size/XS

#243 [ART-839][ART-1343] Add operator_image_ref_mode to group.yml
  group.yml
Labels: size/XS

#244 [ART-839][ART-1343] Add operator_image_ref_mode to group.yml
  group.yml
Labels: size/XS

#249 Use mailing list for ironic image owners
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/M

#248 Use mailing list for ironic image owners
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/M

#247 Use mailing list for ironic image owners
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/M

#240 Remove deprecated update statement and wrap text
  erratatool.yml
Labels: lgtm, size/XS

#239 Remove deprecated update statement and wrap text
  erratatool.yml
Labels: lgtm, size/XS

#253 Remove OpenStack repos from Kuryr builds
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: lgtm, size/XS

#250 Add builder for ironic image
  images/ironic.yml
Labels: size/XS

#251 Add builder for ironic image
  images/ironic.yml
Labels: size/XS

#252 Enable ose-metering-helm on all arches
  images/ose-metering-helm.yml
Labels: size/XS

#257 Revert: Rename ironic-rhcos to ironic-machine-os in 4.2
  images/ironic-rhcos-downloader.yml
Labels: size/XS

#254 Remove OpenStack repos from Kuryr builds
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: size/XS

#256 Bumping go version for CVO
  images/cluster-version-operator.yml
Labels: size/XS

#260 freeze automation
  group.yml
Labels: size/XS

#259 freeze automation
  group.yml
Labels: size/XS
