Repository openshift-eng/ocp-build-data, pull requests merged in 2019-11, with the labels that each got.

#199 Embed 4.4 advisory numbers
  group.yml
Labels: size/S

#183 4.2: Provide per advisory kind boilerplate text
  erratatool.yml
Labels: size/M

#184 4.1: Provide per advisory kind boilerplate text
  erratatool.yml
Labels: size/M

#185 4.3: Provide per advisory kind boilerplate text
  erratatool.yml
Labels: size/M

#186 3.11: Provide per advisory kind boilerplate text
  erratatool.yml
Labels: size/M

#202 ovn-kubernetes: add FDP Next repo and allow it for ovn-kubernetes
  group.yml
  images/ose-ovn-kubernetes.yml
Labels: size/S

#194 remove wip
  images/sriov-network-webhook.yml
Labels: size/XS

#203 update contact information
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-apb-base.yml
  images/openshift-enterprise-asb.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mediawiki.apb.yml
  images/openshift-enterprise-mediawiki.container.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-postgresql.yml
  images/template-service-broker.yml
Labels: lgtm, size/M

#204 update contact information
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-ansible-service-broker-operator.yml
  images/openshift-enterprise-apb-base.yml
  images/openshift-enterprise-asb.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mediawiki.apb.yml
  images/openshift-enterprise-mediawiki.container.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-postgresql.yml
  images/openshift-enterprise-template-service-broker-operator.yml
  images/template-service-broker.yml
Labels: lgtm, size/M

#205 update contact information
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-ansible-service-broker-operator.yml
  images/openshift-enterprise-apb-base.yml
  images/openshift-enterprise-asb.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mediawiki.apb.yml
  images/openshift-enterprise-mediawiki.container.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-postgresql.yml
  images/openshift-enterprise-template-service-broker-operator.yml
  images/template-service-broker.yml
Labels: lgtm, size/M

#206 update contact information
  images/automation-broker-apb.yml
  images/openshift-enterprise-apb.yml
  images/template-service-broker.yml
Labels: lgtm, size/S

#207 update contact information
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-ansible-service-broker-operator.yml
  images/openshift-enterprise-apb-base.yml
  images/openshift-enterprise-asb.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mediawiki.apb.yml
  images/openshift-enterprise-mediawiki.container.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-postgresql.yml
  images/openshift-enterprise-template-service-broker-operator.yml
  images/template-service-broker.yml
Labels: lgtm, size/M

#188 Update gitlab URL to Github URL
  README.md
Labels: size/XS

#208 4.3 extras and metadata advisories
  group.yml
Labels: lgtm, size/XS

#200 MCO: add runcom and steve to MCO build
  images/ose-machine-config-operator.yml
Labels: lgtm, size/XS

#193 Switch Kuryr images to RHEL8 and OSP16
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  rpms/openshift-kuryr.yml
Labels: lgtm, size/M

#209 ose-containernetworking-plugins: Adds rhel-8-golang as an image stream
  images/ose-containernetworking-plugins.yml
Labels: size/XS

#210 Add rhel-8-golang build stream for container networking plugins
  images/ose-containernetworking-plugins.yml
Labels: size/XS

#211 4.3: Enable kuryr on ppc64le
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: size/XS

#214 [Openshift-4.4] Multus CNI should be built from two streams
  images/multus-cni.yml
Labels: size/XS

#215 Use CDN for s390x fast-datapath
  group.yml
Labels: size/XS

#217 4.4: Sync multi-arch changes from 4.3
  group.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: size/XS

#221 Redefine ironic images owners
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/S

#219 Redefine ironic images owners
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/XS

#220 Redefine ironic images owners
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: lgtm, size/S

#227 update contact info for service catalog
  images/openshift-enterprise-service-catalog.yml
  rpms/openshift-enterprise-service-catalog.yml
Labels: size/XS

#226 update contact info for svcat items
  images/openshift-enterprise-service-catalog.yml
  images/ose-cluster-svcat-apiserver-operator.yml
  images/ose-cluster-svcat-controller-manager-operator.yml
  rpms/openshift-enterprise-service-catalog.yml
Labels: size/S

#225 update contact info for svcat items
  images/openshift-enterprise-service-catalog.yml
  images/ose-cluster-svcat-apiserver-operator.yml
  images/ose-cluster-svcat-controller-manager-operator.yml
  rpms/openshift-enterprise-service-catalog.yml
Labels: size/S

#224 update contact info for svcat items
  images/openshift-enterprise-service-catalog.yml
  images/ose-cluster-svcat-apiserver-operator.yml
  images/ose-cluster-svcat-controller-manager-operator.yml
  rpms/openshift-enterprise-service-catalog.yml
Labels: size/S

#212 ovn-kubernetes: add FDP Next RHEL8 repos
  group.yml
Labels: size/S

#229 4.3: Use rhel-8 branches and tags for kuryr containers
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: size/XS

#232 Update owners on Kuryr deliverables
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  rpms/openshift-kuryr.yml
Labels: size/XS

#233 Update owners of Kuryr deliverables
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  rpms/openshift-kuryr.yml
Labels: size/XS

#234 Rename ironic-rhcos to ironic-machine-os
  images/ironic-rhcos-downloader.yml
Labels: size/XS

#235 Rename ironic-rhcos to ironic-machine-os
  images/ironic-rhcos-downloader.yml
Labels: size/XS

#236 Rename ironic-rhcos to ironic-machine-os
  images/ironic-rhcos-downloader.yml
Labels: size/XS

#218 images: send notifications regarding monitoring components to monitoring team
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/grafana.yml
  images/kube-rbac-proxy.yml
  images/kube-state-metrics.yml
  images/ose-prometheus-adapter.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: lgtm, size/M
