Repository openshift-eng/ocp-build-data, pull requests merged in 2019-01, with the labels that each got.

#31 Add router-base to the 4.0 build, base haproxy-router off it
  images/openshift-enterprise-haproxy-router-base.yml
  images/openshift-enterprise-haproxy-router.yml
Labels: size/S

#33 Fix operator marketplace name
  images/marketplace-operator.yml
Labels: size/XS

#35 rename repo cluster-osin-operator to cluster-authentication-operator
  images/ose-cluster-authentication-operator.yml
Labels: lgtm, size/XS

#36 Add ppc64le repos for 4.0
  group.yml
Labels: size/M

#38 attempting to add OpenStack RPMs to group.yml
  group.yml
Labels: lgtm, size/XS

#37 Include master jenkins image in release payload
  images/openshift-jenkins-2.yml
Labels: size/XS

#40 images: update etcd branch naming
  images/ose-etcd.yml
Labels: size/XS
