Repository openshift-eng/ocp-build-data, pull requests merged in 2019-10, with the labels that each got.

#172 sriov-network-config-daemon: use extras repo not optional
  images/sriov-network-config-daemon.yml
Labels: lgtm, size/XS

#181 Enable rhel-8 ose rpms to be reposynced
  group.yml
Labels: size/S

#182 Enable reposync for rhel-8 rpms
  group.yml
Labels: size/S

#187 Add RHEL 8 fast-datapath repos
  group.yml
Labels: size/S

#190 Initial pass for rhel-8-golang-1.12 compiler for CI
  group.yml
  images/openshift-golang-builder.yml
  rpms/golang-scl-shim.yml
Labels: size/S

#173 Always pull latest CI image (openshift-4.3)
  Jenkinsfile
Labels: size/XS

#174 Always pull latest CI image (openshift-4.2)
  Jenkinsfile
Labels: size/XS

#175 Always pull latest CI image (openshift-4.1)
  Jenkinsfile
Labels: size/XS

#176 Always pull latest CI image (openshift-3.11)
  Jenkinsfile
Labels: size/XS

#177 Always pull latest CI image (openshift-3.10)
  Jenkinsfile
Labels: size/XS

#178 Always pull latest CI image (openshift-3.9)
  Jenkinsfile
Labels: size/XS

#192 Art 1161
  images/sriov-network-webhook.yml
Labels: size/S

#195 Update advisory numbers for 3.9.102
  group.yml
Labels: size/XS

#170 4.3: Revert temporary s390x repos
  group.yml
  images/kube-proxy.yml
  images/ose-sdn.yml
Labels: size/S

#196 Rename linuxptp-daemon image name to ptp
  images/linuxptp-daemon.yml
Labels: lgtm, size/XS
