Repository openshift-eng/ocp-build-data, pull requests merged in 2019-06, with the labels that each got.

#138 Add ghostunnel.yml to image builds
  images/ghostunnel.yml
Labels: do-not-merge/hold, size/S

#139 Remove ose-metering-helm-operator
  group.yml
  images/ose-metering-helm-operator.yml
Labels: size/S

#143 Update streams.yml for 3.11
  streams.yml
Labels: size/XS

#145 Update streams.yml for 3.6
  streams.yml
Labels: size/XS

#140 Remove metering components from non-release list for 4.2
  group.yml
Labels: size/XS

#133 adding ose-metering-ansible-operator.yml
  images/ose-metering-ansible-operator.yml
Labels: size/S

#147 Update metering-ansible-operator builder images and enabled_repos
  images/ose-metering-ansible-operator.yml
Labels: size/XS

#144 Update streams.yml for 3.10
  streams.yml
Labels: size/XS

#151 add machine-config-daemon yml file
  rpms/machine-config-daemon.yml
Labels: size/S

#152 [ART-672] Add sriov-network-operator.yml
  images/sriov-network-operator.yml
Labels: lgtm, size/S

#153 Add cluster-update-keys for 4.2 (was not part of branch)
  images/ose-cluster-update-keys.yml
Labels: size/S

#156 add more monitoring team owners
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/grafana.yml
  images/kube-rbac-proxy.yml
  images/kube-state-metrics.yml
  images/ose-prometheus-adapter.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: size/S

#154 Use golang-1.12 for Network Edge operators
  images/ose-cluster-dns-operator.yml
  images/ose-cluster-ingress-operator.yml
Labels: size/XS

#158 [PROD-1276] Release 4.1.3 Update group.yml
  group.yml
Labels: size/XS

#142 un-WIP node-feature-discovery build for 4.2
  images/node-feature-discovery.yml
Labels: size/XS

#141 un-WIP node-feature-discovery build for 4.1
  images/node-feature-discovery.yml
Labels: size/XS
