Repository openshift-eng/ocp-build-data, pull requests merged in 2019-05, with the labels that each got.

#101 add elastic and logging operators as dependents of their operands
  images/golang-github-openshift-oauth-proxy.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-rsyslog.yml
Labels: size/XS

#79 update etcd3-docker.yml to change mode: disabled
  images/etcd3-docker.yml
Labels: lgtm, size/XS

#106 add cnv sync file
  images/virt-api.yml
  images/virt-handler.yml
Labels: size/S

#109 [4.1] Update DevEx owners
  images/ose-cluster-openshift-controller-manager-operator.yml
  images/ose-cluster-samples-operator.yml
Labels: size/XS

#110 Set metering images to non-release
  group.yml
Labels: size/XS

#113 update to replace images in CSV
  images/openshift-enterprise-template-service-broker-operator.yml
Labels: size/XS

#112 CSV substitution for CLO and EO
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
Labels: lgtm, size/XS

#114 fixing typo in manifests dir location for TSBO
  images/openshift-enterprise-template-service-broker-operator.yml
Labels: size/XS

#115 adding dependent clause on the operator.
  images/template-service-broker.yml
Labels: size/XS

#116 Bug 1703240: Update base image for ocp build of must-gather.
  images/ose-must-gather.yml
Labels: lgtm, size/XS

#121 enable repos so slave-base can install dumb-init
  images/jenkins-slave-base-rhel7.yml
Labels: size/XS

#122 enable repos so slave-base can install dumb-init
  images/jenkins-slave-base-rhel7.yml
Labels: size/XS

#120 enable repos so slave-base can install dumb-init
  images/jenkins-slave-base-rhel7.yml
Labels: size/XS

#119 Update metering-helm-operator base
  images/ose-metering-helm-operator.yml
Labels: size/XS

#124 [3.10]fix up image ownership
  images/jenkins-agent-maven-35-rhel7.yml
  images/jenkins-agent-nodejs-8-rhel7.yml
  images/jenkins-slave-base-rhel7.yml
  images/jenkins-slave-maven-rhel7.yml
  images/jenkins-slave-nodejs-rhel7.yml
  images/openshift-jenkins-2.yml
  images/template-service-broker.yml
  rpms/openshift-enterprise-image-registry.yml
Labels: size/S

#123 [3.11]fix up image ownership
  images/jenkins-agent-maven-35-rhel7.yml
  images/jenkins-agent-nodejs-8-rhel7.yml
  images/jenkins-slave-base-rhel7.yml
  images/jenkins-slave-maven-rhel7.yml
  images/jenkins-slave-nodejs-rhel7.yml
  images/openshift-jenkins-2.yml
  images/template-service-broker.yml
  rpms/openshift-enterprise-image-registry.yml
Labels: size/S

#127 Remove Kuryr images from non_release list
  group.yml
Labels: size/XS

#126 add rpm repo to allow dumb-init install on 4.2
  images/jenkins-slave-base-rhel7.yml
Labels: size/XS

#104 Add golang module paths for Network Edge components
  images/ose-cluster-dns-operator.yml
  images/ose-cluster-ingress-operator.yml
  images/ose-haproxy-router-base.yml
Labels: size/S

#129 Add cluster-update-keys to OCP
  images/ose-cluster-update-keys.yml
Labels: size/S

#130 Remove non-shipping images
  images/atomic-openshift-node-problem-detector.yml
  images/cluster-nfd-operator.yml
  images/csi-provisioner.yml
  images/efs-provisioner.yml
  images/hadoop.yml
  images/hive.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/node-problem-detector-operator.yml
  images/openshift-enterprise-autoheal.yml
  images/ose-leader-elector.yml
  images/ose-metering-helm-operator.yml
  images/ose-metering-helm.yml
  images/ose-metering-reporting-operator.yml
  images/presto.yml
  images/snapshot-controller.yml
  images/snapshot-provisioner.yml
Labels: size/L

#131 Remove federation v2 and service-idler
  group.yml
  images/federation-v2.yml
  images/openshift-enterprise-service-idler.yml
Labels: lgtm, size/M

#132 add ose-openshift-state-metrics
  images/ose-openshift-state-metrics.yml
Labels: size/S

#135 Remove leader-elector from non_release list
  group.yml
Labels: size/XS

#136 remove wip for openshift-state-metrics
  images/openshift-state-metrics.yml
Labels: size/XS
