Repository openshift-eng/ocp-build-data, pull requests merged in 2019-04, with the labels that each got.

#74 rpms/openshift: use custom tito config
  rpms/openshift.yml
Labels: lgtm, size/XS

#75 Add default advisory keys for bug sweep automation
  group.yml
Labels: size/S

#76 Add default advisory keys for bug sweep automation
  group.yml
Labels: size/S

#73 Add new artifacts images
  images/openshift-enterprise-cli-artifacts.yml
  images/ose-installer-artifacts.yml
Labels: size/M

#78 Add openshift-ansible to 4.1 rpms
  rpms/openshift-ansible.yml
Labels: size/S

#81 change oit to doozer
  example/images/myutil-base.yml
  example/images/myutil.yml
  example/images/template.yml
  example/rpms/myutil.yml
Labels: size/S

#82 add ose-baremetal-operator.yml
  images/ose-baremetal-operator.yml
Labels: size/S

#85 Switch to go 1.11
  images/ose-cluster-kube-scheduler-operator.yml
Labels: size/XS

#83 mark cli-artifacts as x86_64 only
  images/ose-cli-artifacts.yml
Labels: size/XS

#80 adding missing owner images for 4.1
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/image-inspector.yml
  images/logging-eventrouter.yml
  images/openshift-enterprise-autoheal.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-hypershift.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mediawiki.apb.yml
  images/openshift-enterprise-mediawiki.container.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-node.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-postgresql.yml
  images/openshift-enterprise-recycler.yml
  images/openshift-enterprise-tests.yml
  images/openshift-local-storage.yml
  images/ose-egress-http-proxy.yml
  images/ose-haproxy-router-base.yml
  images/snapshot-controller.yml
  images/snapshot-provisioner.yml
Labels: size/M

#88 remove mode wip
  images/ose-baremetal-operator.yml
Labels: size/XS

#87 sync service broker repos
  group.yml
Labels: size/XS

#90 Update metrics-cassandra.yml
  images/metrics-cassandra.yml
Labels: size/XS

#91 Update logging-kibana.yml
  images/logging-kibana.yml
Labels: size/XS

#92 Update streams.yml
  streams.yml
Labels: size/XS

#93 Update streams.yml
  streams.yml
Labels: size/XS

#89 Update README to point to existing branch
  README.md
Labels: lgtm, size/XS

#94 jobspec: update for v3.1 pipeline
  jobspec.yaml
Labels: size/S

#95 Jenkinsfile: use SHA for checkout
  Jenkinsfile
Labels: size/XS

#96 Jenksfile: remove trust since this public
  Jenkinsfile
  ca.crt
Labels: size/S

#98 remove etcd-quorum-guard image
  images/etcd-quorum-guard.yml
Labels: size/S
