Repository openshift-eng/ocp-build-data, pull requests merged in 2020-05, with the labels that each got.

#448 modify Jenkinsfile to add sshagent wrapper
  Jenkinsfile
Labels: lgtm

#458 Bug 1835318: ovn-kubernetes: re-enable fast-datapath-beta for ovn2.13-2.13.0-30
  images/ose-ovn-kubernetes.yml
Labels: bugzilla/severity-urgent, bugzilla/valid-bug

#462 Update images to Ansible 2.8
  group.yml
  images/aos3-installation.yml
  images/openshift-enterprise-apb-base.yml
Labels: lgtm

#297 Change vertical-pod-autoscaler-operator install from CVO to OLM
  images/vertical-pod-autoscaler-operator.yml
Labels: do-not-merge/hold, size/XS

#459 Add aos-workloads to descheduler owners
  images/atomic-openshift-descheduler.yml
Labels: lgtm
