Repository openshift-eng/ocp-build-data, pull requests merged in 2020-02, with the labels that each got.

#301 Bug 1798086: Re-enable the TSB and its operator
  images/openshift-enterprise-template-service-broker-operator.yml
  images/template-service-broker.yml
Labels: bugzilla/valid-bug, lgtm, size/M

#304 Remove template-service-broker-operator from dependent list
  images/openshift-enterprise-template-service-broker-operator.yml
  images/template-service-broker.yml
Labels: lgtm, size/XS

#307 Bug 1802325: Use Fast Datapath puddles on IBM arches
  group.yml
Labels: bugzilla/valid-bug, size/S

#306 Bug 1802716: Use FDP-next repos
  group.yml
Labels: bugzilla/valid-bug, size/S

#309 Swizzle fast-datapath again to pull in pre-GA
  group.yml
  images/ose-ovn-kubernetes.yml
Labels: lgtm, size/XS

#308 Add 3.11 build profiles
  group.yml
Labels: size/S

#321 freeze automation
  group.yml
Labels: size/XS

#322 freeze automation
  group.yml
Labels: size/XS

#312 Add build profiles
  group.yml
Labels: lgtm, size/S

#313 Add build profiles
  group.yml
Labels: lgtm, size/S

#314 Add build profiles
  group.yml
Labels: lgtm, size/S

#315 Add build profiles
  group.yml
Labels: lgtm, size/S

#316 Add build profiles
  group.yml
Labels: lgtm, size/S

#318 Create jenkins-agent-nodejs-10-rhel7.yml
  images/jenkins-agent-nodejs-10-rhel7.yml
Labels: lgtm, size/S

#324 Eliminate tito use for 4.4
  rpms/openshift.yml
Labels: size/XS

#325 Revert "Update advisories on group.yml"
  group.yml
Labels: size/S

#327 ART-1559 [4.5] - Get OLM operator owners to update their CSV channels
  images/cluster-logging-operator.yml
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/local-storage-operator.yml
  images/ptp-operator.yml
Labels: size/XS

#330 Disable because it has no 4.5 branch
  images/ose-cluster-csi-snapshot-controller-operator.yml
Labels: size/XS
