Repository openshift-eng/ocp-build-data, pull requests merged in 2020-01, with the labels that each got.

#265 [ART-1422] Disable kube-storage-version-migrator
  images/ose-kube-storage-version-migrator.yml
Labels: lgtm, size/XS

#262 Ironic images should not use osp repos
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: size/XS

#263 Ironic images should not use osp repos
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
Labels: size/XS

#266 Remove the template service broker from 4.4
  images/template-service-broker.yml
Labels: size/M

#267 Remove the ansible service broker from 4.4.
  images/openshift-enterprise-asb.yml
Labels: size/S

#268 remove APBs that were meant for ASB
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-apb-base.yml
  images/openshift-enterprise-apb.yml
  images/openshift-enterprise-mariadb.yml
  images/openshift-enterprise-mysql.yml
  images/openshift-enterprise-postgresql.yml
Labels: size/M

#278 branch is release-x.y not openshift-x.y
  rpms/machine-config-daemon.yml
Labels: lgtm, size/XS

#279 branch is release-x.y not openshift-x.y
  rpms/machine-config-daemon.yml
Labels: lgtm, size/XS

#280 branch is release-x.y not openshift-x.y
  rpms/machine-config-daemon.yml
Labels: lgtm, size/XS

#281 branch is release-x.y not openshift-x.y
  rpms/machine-config-daemon.yml
Labels: lgtm, size/XS

#273 Disable reposync for rpms available on cdn
  group.yml
Labels: size/M

#274 Disable reposync for rpms available on cdn
  group.yml
Labels: size/M

#275 Disable reposync for rpms available on cdn
  group.yml
Labels: size/M

#276 Disable reposync for rpms available on cdn
  group.yml
Labels: size/S

#277 Disable reposync for rpms available on cdn
  group.yml
Labels: size/S

#269 remove rsyslog
  images/logging-rsyslog.yml
Labels: size/S

#282 Sync recent 4.4 additions to 4.5
  images/ose-csi-snapshot-controller.yml
  images/ose-oauth-apiserver.yml
Labels: size/M

#270 4.4: Sanitize storage image owners
  images/cluster-storage-operator.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/csi-provisioner.yml
  images/efs-provisioner.yml
  images/local-storage-diskmaker.yml
  images/local-storage-operator.yml
  images/local-storage-static-provisioner.yml
  images/openshift-enterprise-recycler.yml
Labels: size/S

#283 images: remove sjenning from descheduler owners
  images/atomic-openshift-descheduler.yml
Labels: size/XS

#284 Change oauth-proxy Dockerfile path
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#285 Update golang-github-openshift-oauth-proxy.yml
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#288 The ironic-ipa-downloader image should not use osp repos
  images/ironic-ipa-downloader.yml
Labels: lgtm, size/XS

#289 The ironic-ipa-downloader image should not use osp repos
  images/ironic-ipa-downloader.yml
Labels: lgtm, size/XS

#290 The ironic-ipa-downloader image should not use osp repos
  images/ironic-ipa-downloader.yml
Labels: lgtm, size/XS

#287 [ART-1460 ART-1461] Add ose-route-override-cni ose-whereabouts-cni
  images/ose-route-override-cni.yml
  images/ose-whereabouts-cni.yml
Labels: size/M

#261 Enable ODCS for image build
  group.yml
Labels: size/XS

#299 Renames route-override-cni and whereabouts-cni to follow naming conventions
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: size/XS

#300 Add route-override whereabouts to 4.5
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: size/M
