Repository openshift-eng/ocp-build-data, pull requests merged in 2020-11, with the labels that each got.

#721 Enable cachitos
  images/baremetal-machine-controller.yml
  images/baremetal-runtimecfg.yml
  images/cluster-etcd-operator.yml
  images/cluster-node-tuning-operator.yml
  images/oauth-server.yml
  images/operator-registry.yml
Labels: lgtm

#729 [openshift-4.5] Use RHEL 8.2 EUS yum repos and images
  group.yml
  streams.yml
Labels: do-not-merge/hold

#736 WIP: 3.11 haproxy-router: Add release specific Dockerfile
  images/openshift-enterprise-haproxy-router.yml
Labels: do-not-merge/work-in-progress

#751 openshift-4.7: Fix build of ptp-operator-must-gather
  images/ptp-operator-must-gather.yml
Labels: lgtm

#760 Add ose-cluster-kube-descheduler-operator as a dependent of descheduler
  images/atomic-openshift-descheduler.yml
Labels: lgtm

#769 Exclude windows bugzilla component
  bugzilla.yml
Labels: lgtm

#783 [ART-2467] Set custom bundle brew component for nmstate-operator
  images/openshift-kubernetes-nmstate-operator.yml
Labels: do-not-merge/hold
