Repository openshift-eng/ocp-build-data, pull requests merged in 2020-03, with the labels that each got.

#331 Fix up owners of networking images [4.4]
  images/cluster-network-operator.yml
  images/kube-proxy.yml
  images/ose-ovn-kubernetes.yml
Labels: size/XS

#332 Fix up owners of networking images [4.3]
  images/cluster-network-operator.yml
  images/kube-proxy.yml
  images/ose-ovn-kubernetes.yml
Labels: size/XS

#333 Fix up owners of networking images [4.2]
  images/cluster-network-operator.yml
  images/kube-proxy.yml
  images/ose-ovn-kubernetes.yml
  images/ose-sdn.yml
Labels: size/S

#334 Fix up owners of networking images [4.1]
  images/cluster-network-operator.yml
  images/kube-proxy.yml
  images/openshift-enterprise-node.yml
  images/ose-ovn-kubernetes.yml
Labels: size/S

#336 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#337 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#338 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#339 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#340 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#341 oauth-proxy: use mail list
  images/golang-github-openshift-oauth-proxy.yml
Labels: size/XS

#335 Update ansible-operator base image
  group.yml
  images/openshift-enterprise-ansible-operator.yml
Labels: size/S

#353 remove rmeggins@redhat.com
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#352 remove rmeggins@redhat.com
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#347 remove rmeggins@redhat.com
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#346 remove rmeggins@redhat.com
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#345 remove rmeggins@redhat.com
  images/logging-curator.yml
  images/logging-elasticsearch.yml
  images/logging-fluentd.yml
  images/logging-kibana.yml
Labels: size/XS

#343 remove rmeggins@redhat.com
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#351 remove rmeggins@redhat.com
  images/cluster-logging-operator.yml
  images/elasticsearch-operator.yml
  images/logging-curator5.yml
  images/logging-elasticsearch5.yml
  images/logging-fluentd.yml
  images/logging-kibana5.yml
Labels: size/XS

#342 remove rmeggins@redhat.com
  images/logging-curator.yml
  images/logging-elasticsearch.yml
  images/logging-fluentd.yml
  images/logging-kibana.yml
Labels: size/XS

#356 Revert "Update advisories on group.yml"
  group.yml
Labels: size/XS

#359 Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: size/XS

#358 bug 1810977: Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: bugzilla/invalid-bug, size/XS

#360 Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: size/XS

#361 Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: size/XS

#362 Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: size/XS

#363 Change owners of cluster-capacity image
  images/openshift-enterprise-cluster-capacity.yml
Labels: size/XS

#364 Enable operators which fixed their package.yaml thing
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
Labels: size/XS

#365 Use FDP-next repos
  group.yml
Labels: lgtm, size/S

#367 Adds multus-route-override-cni and multus-whereabouts-ipam-cni in 4.3
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: size/M

#372 4.5 Enable local-storage operator.
  images/local-storage-operator.yml
Labels: size/XS

#369 add images/openshift-enterprise-helm-operator.yml [openshift-4.5]
  images/openshift-enterprise-helm-operator.yml
Labels: size/S

#370 add images/openshift-enterprise-helm-operator.yml [openshift-4.6]
  images/openshift-enterprise-helm-operator.yml
Labels: size/S

#373 Disable logging components for 4.5
  images/logging-elasticsearch5.yml
  images/logging-kibana5.yml
Labels: size/XS

#385 Bug 1816774: Fix build order in new multus images
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: bugzilla/invalid-bug

#317 enable es/kibana 6 publishing
  images/logging-elasticsearch6.yml
  images/logging-kibana6.yml
Labels: lgtm, size/S
