Repository openshift-eng/ocp-build-data, pull requests merged in 2021-11, with the labels that each got.

#1127 [openshift-4.7][ART-3423] Use RHEL 8.4 EUS content
  group.yml
  streams.yml
Labels: do-not-merge/hold

#1140 4.10: Allow MISMATCHED_SIBLINGS
  releases.yml
Labels: lgtm

#1143 ART-3409 Bump rhel8 golang to 1.17
  streams.yml
Labels: lgtm

#1153 [openshift-3.11] Remove images/manila-provisioner
  images/manila-provisioner.yml
Labels: lgtm

#1174 ping openshift pkg
  releases.yml
Labels: needs-rebase

#1176 Allow rpm pins for ironic image
  releases.yml
Labels: lgtm

#1144 [ART-3408] remove rhel7 workers for 4.10
  images/egress-router-cni-alt.yml
  images/multus-cni-alt.yml
  images/ose-containernetworking-plugins-alt.yml
  images/ose-multus-route-override-cni-alt.yml
  images/ose-multus-whereabouts-ipam-cni-alt.yml
Labels: lgtm

#1177 Exclude certain components form BZ attachment to ET
  bugzilla.yml
Labels: lgtm
