Repository openshift-eng/ocp-build-data, pull requests merged in 2021-04, with the labels that each got.

#865 [ART-2744] Pin RHEL_VERSION in images/driver-toolkit.yml
  images/driver-toolkit.yml
Labels: lgtm

#867 [ART-2744] Add images/driver-toolkit.yml
  group.yml
  images/driver-toolkit.yml
Labels: lgtm

#876 Updates to 4.6 advisory text
  erratatool.yml
Labels: lgtm

#875 Updates to 4.5 advisory text
  erratatool.yml
Labels: lgtm

#860 wip [art-1887]: Fix ansible-runner
  base-images/ansible-runner/Dockerfile
  images/openshift-enterprise-apb-base.yml
Labels: do-not-merge/work-in-progress

#879 Remove "vmware" prefix from CSI operator and driver
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver.yml
Labels: lgtm

#881 Drop rhel8 suffix
  images/vmware-vsphere-syncer.yml
Labels: lgtm

#870 [ART-2340] [4.5] inline streams as members
  images/atomic-openshift-cluster-autoscaler.yml
  images/atomic-openshift-descheduler.yml
  images/golang-github-openshift-oauth-proxy.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/hadoop.yml
  images/hive.yml
  images/ironic-hardware-inventory-recorder-image.yml
  images/ironic-inspector.yml
  images/ironic-ipa-downloader.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/logging-curator5.yml
  images/logging-elasticsearch6.yml
  images/logging-eventrouter.yml
  images/logging-fluentd.yml
  images/logging-kibana6.yml
  images/openshift-base-nodejs-runtime.yml
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel7.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-ruby.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-console.yml
  images/ose-cluster-samples-operator.yml
  images/ose-metering-helm.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
  images/presto.yml
  images/prom-label-proxy.yml
  images/tuned.yml
  streams.yml
Labels: lgtm

#899 cluster-capacity: fix CVP warnings
  images/openshift-enterprise-cluster-capacity.yml
Labels: lgtm

#885 Build 4.8 with RHEL 8.4 Beta
  group.yml
  images/driver-toolkit.yml
  streams.yml
Labels: do-not-merge/hold

#907 builder: Use runc from ose repo
  images/openshift-enterprise-builder.yml
Labels: lgtm

#911 Bug 1954881: update manifests location for NFD
  images/cluster-nfd-operator.yml
Labels: bugzilla/invalid-bug, bugzilla/severity-high
