Repository openshift-eng/ocp-build-data, pull requests merged in 2022-05, with the labels that each got.

#1552 Bug 2081062: Revert "Revert "Pin rhcos for amd64 until BZ2077052 is fixed""
  releases.yml
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#1553 Revert "Bug 2081062: Revert "Revert "Pin rhcos for amd64 until BZ2077052 is fixed"""
  releases.yml
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#1555 Prepare 4.9.32
  releases.yml
Labels: lgtm

#1556 Prepare 4.7.50
  releases.yml
Labels: lgtm

#1554 Prepare 4.10.13
  releases.yml
Labels: lgtm

#1557 4.10.13: Pin kube-rbac-proxy and related images
  releases.yml
Labels: lgtm

#1562 Remove extra build stage
  images/ose-ibm-cloud-controller-manager.yml
Labels: lgtm

#1572 Pin openshift-client RPM version
  releases.yml
Labels: lgtm

#1573 Declare deps on rbac-proxy
  images/kube-rbac-proxy.yml
Labels: lgtm

#1574 Pin new builds for rbac deps
  releases.yml
Labels: lgtm

#1580 [ART-3987] Rename {,machine-}image-customization-controller (#1540)
  images/ose-image-customization-controller.yml
Labels: lgtm

#1588 [4.10] bug 2084234: streams.yml: update rhel8-els image
  streams.yml
Labels: lgtm, bugzilla/invalid-bug, bugzilla/severity-medium

#1597 4.10.15
  releases.yml
Labels: lgtm

#1600 Prep 4.8.40
  releases.yml
Labels: lgtm

#1599 Prep 4.7.51
  releases.yml
Labels: lgtm

#1598 Prepare 4.6.58
  releases.yml
Labels: lgtm

#1601 Add promotion permits for 4.8.40
  releases.yml
Labels: lgtm

#1602 Add promotion permits for 4.7.51
  releases.yml
Labels: lgtm

#1609 4.11 - Remove redundant permits from releases.yml
  releases.yml
Labels: lgtm

#1610 4.11: driver-toolkit tracks rhel-8.5
  group.yml
  images/driver-toolkit.yml
Labels: lgtm

#1584 Build cli-artifacts and enterprise-cli on rhel8 exclusively
  images/openshift-enterprise-cli-alt.yml
  images/openshift-enterprise-cli.yml
  images/ose-cli-artifacts-alt.yml
  images/ose-cli-artifacts.yml
  streams.yml
Labels: lgtm

#1619 Prepare 4.9.35
  releases.yml
Labels: lgtm

#1621 ose-machine-os-images: Don't reconcile build_root_image
  images/ose-machine-os-images.yml
Labels: lgtm

#1569 [ART-3904] Remove jenkins images
  images/openshift-jenkins-2.yml
  images/ose-jenkins-agent-base.yml
  images/ose-jenkins-agent-maven.yml
  images/ose-jenkins-agent-nodejs-12.yml
Labels: lgtm

#1608 ose-console: Get rid of distgit lookaside cache
  images/openshift-enterprise-console.yml
  modifications/update-console-sources
Labels: lgtm

#1611 [4.11] remove rhel7 rpms
  rpms/openshift-ansible.yml
  rpms/openshift-clients.yml
Labels: lgtm

#1633 Temporarily add ose repo for nmstate-handler
  images/openshift-kubernetes-nmstate-handler.yml
Labels: lgtm

#1647 Freeze 4.7 automation in anticipation of 8.4 rhel update
  group.yml
Labels: lgtm
