Repository openshift-eng/ocp-build-data, pull requests merged in 2022-08, with the labels that each got.

#1815 Add release 4.10.26
  releases.yml
Labels: lgtm

#1816 Add release 4.9.45
  releases.yml
Labels: lgtm

#1818 Prepare 4.8.47
  releases.yml
Labels: lgtm

#1820 [openshift-4.12] Bug 2114968: Revert "releases.yml: remove ironic pins now that they build"
  releases.yml
Labels: lgtm, bugzilla/invalid-bug, bugzilla/severity-high

#1824 rc.7 assembly definition
  releases.yml
Labels: lgtm

#1831 Stop building 4.11 for bootimage creation
  group.yml
Labels: lgtm

#1833 Define 4.11.0
  releases.yml
Labels: lgtm

#1859 Revert "Stop building 4.11 for bootimage creation"
  group.yml
Labels: lgtm

#1862 4.7.56 assembly
  releases.yml
Labels: lgtm

#1864 [ART-4465] Pin cri-o build present in RHCOS
  releases.yml
Labels: lgtm

#1832 [ART-4316] Add ingress-node-firewall
  images/ingress-node-firewall.yml
Labels: lgtm

#1867 4.7.57 assembly
  releases.yml
Labels: lgtm

#1874 Start sweeping PAO bugs
  bug.yml
  bugzilla.yml
Labels: lgtm

#1876 NetworkManager from our repo
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-agent-installer-api-server.yml
  images/ose-image-customization-controller.yml
Labels: lgtm

#1877 Get NetworkManager from ose repo
  images/ose-image-customization-controller.yml
Labels: lgtm

#1881 Revert "Freeze 4.11 for now"
  group.yml
Labels: do-not-merge/hold

#1887 [4.6] consolidate bug.yml with bugzilla.yml
  bug.yml
Labels: lgtm

#1888 [4.7] consolidate bug.yml with bugzilla.yml
  bug.yml
Labels: lgtm

#1889 [4.8] consolidate bug.yml with bugzilla.yml
  bug.yml
Labels: lgtm

#1891 [4.9] Add missing component in security filter
  bug.yml
Labels: lgtm

#1892 [4.11] Add missing component in security filter
  bug.yml
Labels: lgtm

#1893 [4.12] Add missing component + Delete bugzilla.yml
  bug.yml
  bugzilla.yml
Labels: lgtm

#1847 Remove advisories from group.yml
  group.yml
Labels: lgtm

#1909 [4.12] Add the OLM openshift/operator-framework-rukpak component
  images/ose-olm-rukpak.yml
Labels: lgtm

#1911 Propose 4.10.31
  releases.yml
Labels: lgtm

#1913 Freeze 4.11 to ensure one bug gets included in next build
  group.yml
Labels: lgtm
