Repository openshift-eng/ocp-build-data, pull requests merged in 2022-04, with the labels that each got.

#1486 Freeze automation for 4.6 for now
  group.yml
Labels: lgtm

#1487 Remove assisted-installer from bugzilla components
  bugzilla.yml
Labels: lgtm

#1491 respin 4.10.7 as 4.10.8
  releases.yml
Labels: lgtm

#1493 Re-enable Cachito for ocp-release-operator-sdk
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-helm-operator.yml
  images/openshift-enterprise-operator-sdk.yml
Labels: lgtm

#1477 [ART-3889] Add ose-azure-cluster-api-controllers
  images/ose-azure-cluster-api-controllers.yml
Labels: do-not-merge/hold

#1478 [ART-3890] Add ose-gcp-cluster-api-controllers
  images/ose-gcp-cluster-api-controllers.yml
Labels: do-not-merge/hold

#1479 [ART-3891] Add ose-vsphere-cluster-api-controllers
  images/ose-vsphere-cluster-api-controllers.yml
Labels: do-not-merge/hold

#1480 [ART-3916] Add images/ose-nutanix-machine-controllers (mode: wip)
  images/ose-nutanix-machine-controllers.yml
Labels: do-not-merge/hold

#1496 Pin rhcos for amd64 until BZ 2072050 is fixed
  releases.yml
Labels: lgtm

#1501 Bug 2064204: Enable cachito for operator-sdk images
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-helm-operator.yml
  images/openshift-enterprise-operator-sdk.yml
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#1508 ose-baremetal-installer: provide GA libvirt
  group.yml
  images/ose-baremetal-installer.yml
Labels: lgtm

#1513 Try out cachito on 3.11 again
  group.yml
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/efs-provisioner.yml
  images/grafana.yml
  images/kube-rbac-proxy.yml
  images/kube-state-metrics.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-console.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: lgtm

#1512 Enable cachito metering images
  images/ose-metering-ansible-operator.yml
  images/ose-metering-helm.yml
Labels: lgtm

#1516 Add release 4.9.29
  releases.yml
Labels: lgtm

#1519 Cachito: add remove-unsafe-symlinks flag
  group.yml
Labels: lgtm

#1518 Cachito: add remove-unsafe-symlinks flag
  group.yml
Labels: lgtm

#1522 4.8.37 - Add promotion permit
  releases.yml
Labels: lgtm

#1531 openshift RPM: no longer supporting RHEL7 workers
  rpms/openshift.yml
Labels: lgtm

#1548 4.10.12: pin local-storage-operator
  releases.yml
Labels: lgtm

#1549 Revert "Revert "openshift RPM: no longer supporting RHEL7 workers""
  rpms/openshift.yml
Labels: lgtm, do-not-merge/hold

#1540 [ART-3987] Rename {,machine-}image-customization-controller
  images/ose-image-customization-controller.yml
Labels: lgtm

#1550 Revert "Pin rhcos for amd64 until BZ2077052 is fixed"
  releases.yml
Labels: lgtm

#1534 Auto-merge alignment PRs against storage components
  images/azure-file-csi-driver-operator.yml
  images/azure-file-csi-driver.yml
  images/csi-attacher.yml
  images/csi-driver-manila-operator.yml
  images/csi-driver-manila.yml
  images/csi-driver-nfs.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/csi-snapshot-validation-webhook.yml
  images/ibm-vpc-node-label-updater.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-alibaba-disk-csi-driver-operator.yml
  images/ose-aws-ebs-csi-driver-operator.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-azure-disk-csi-driver-operator.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-csi-external-resizer.yml
  images/ose-csi-external-snapshotter.yml
  images/ose-csi-snapshot-controller.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver.yml
  images/vmware-vsphere-syncer.yml
  images/vsphere-problem-detector.yml
Labels: lgtm
