Repository openshift-eng/ocp-build-data, pull requests merged in 2022-06, with the labels that each got.

#1650 Revert "Freeze 4.8 automation in anticipation of 8.4 rhel update"
  group.yml
Labels: lgtm

#1652 ART-4103
  releases.yml
Labels: lgtm

#1655 4.11 fc.0 assembly definition
  releases.yml
Labels: lgtm

#1663 3.11 - Add bug.yml
  bug.yml
Labels: lgtm

#1664 Fix bundle dir for vertical-pod-autoscaler-operator
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm

#1665 4.11: Get dtk to rhel-8.6
  group.yml
  images/driver-toolkit.yml
Labels: lgtm

#1673 Prepare 4.8.43
  releases.yml
Labels: lgtm

#1674 Add promotion permits for attached bugs
  releases.yml
Labels: lgtm

#1675 4.6 - Add promotion permits
  releases.yml
Labels: lgtm

#1681 4.6.59: advance brew event to include RPMs in RHCOS
  releases.yml
Labels: lgtm

#1684 [release-4.8] Bug 2095360: Remove microdnf replacement for handler
  images/openshift-kubernetes-nmstate-handler.yml
Labels: do-not-merge/hold, bugzilla/invalid-bug, bugzilla/severity-medium

#1685 [ART-4020] validate image changes
  images/node-problem-detector-operator.yml
  images/sriov-network-must-gather.yml
Labels: lgtm

#1659 Add ironic tag to product version mapping
  erratatool.yml
Labels: lgtm

#1669 [ART-4060] Add ose-agent-installer-api-server
  images/ose-agent-installer-api-server.yml
Labels: lgtm

#1583 [ART-4059] Add ose-agent-installer-csr-approver
  images/ose-agent-installer-csr-approver.yml
Labels: lgtm

#1582 [ART-4058] Add ose-agent-installer-orchestrator
  images/ose-agent-installer-orchestrator.yml
Labels: lgtm

#1666 [ART-4076] Add TALO precache
  images/topology-aware-lifecycle-operator-precache.yml
Labels: lgtm

#1702 Add bugzilla component info to support product security
  images/ose-agent-installer-csr-approver.yml
Labels: lgtm

#1704 Add bugzilla component info to support product security
  images/ose-agent-installer-orchestrator.yml
Labels: lgtm

#1703 Add bugzilla component info to support product security
  images/ose-agent-installer-node-agent.yml
Labels: lgtm

#1701 Add bugzilla component info to support product security
  images/ose-agent-installer-api-server.yml
Labels: lgtm

#1725 [ART-4075] add bare-metal-event-relay
  images/bare-metal-event-relay.yml
  images/baremetal-hardware-event-proxy.yml
Labels: lgtm

#1635 [ART-4070] Add `valid-subscription-label` values to OLM operators
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/dpu-network-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-cluster-kube-descheduler-operator.yml
  images/ose-metallb-operator.yml
  images/ptp-operator.yml
  images/special-resource-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm

#1724 Disable baremetal-operator temporarily
  images/ose-cluster-baremetal-operator.yml
Labels: lgtm

#1733 Exclude containernetworking-plugins from appstream repo
  group.yml
Labels: lgtm

#1742 group.yml: allow compiler sheer until we get it fixed
  group.yml
Labels: lgtm

#1743 Remove MISMATCHED_SIBLINGS permits
  releases.yml
Labels: lgtm

#1737 [ART-4052] add topology-aware-lifecycle-manager
  images/baremetal-hardware-event-proxy.yml
  images/kube-rbac-proxy.yml
  images/topology-aware-lifecycle-manager.yml
  images/topology-aware-lifecycle-operator-precache.yml
Labels: lgtm

#1746 Enable 2 images
  images/clusterresourceoverride.yml
  images/openshift-kubernetes-nmstate-handler.yml
Labels: lgtm

#1751 Start 4.9.41
  releases.yml
Labels: lgtm, do-not-merge/hold

#1755 Do not sweep jenkins bugs
  bug.yml
  bugzilla.yml
Labels: lgtm
