Repository openshift-eng/ocp-build-data, pull requests merged in 2022-07, with the labels that each got.

#1634 Bug 2078573: Revert "Temporarily add ose repo for nmstate-handler"
  images/openshift-kubernetes-nmstate-handler.yml
Labels: do-not-merge/hold, bugzilla/invalid-bug, bugzilla/severity-urgent

#1760 add missing dependents
  images/kube-rbac-proxy.yml
Labels: lgtm

#1759 Do not ignore "Telco Edge" BZs
  bug.yml
  bugzilla.yml
Labels: lgtm

#1764 Prepare 4.11-rc.1
  releases.yml
Labels: lgtm

#1735 [openshift-4.10] Bug 2100850: Add RHEL8 openshift-ansible RPM
  rpms/openshift-ansible.yml
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1771 group.yml: use the arm64 RHCOS builds
  group.yml
Labels: lgtm

#1777 Bump etcd to 3.5.4 and protoc to 3.15.5 to match upstream k8s
  ci_transforms/rhel-8/ci-build-root/Dockerfile
Labels: lgtm

#1776 enable dependents
  images/clusterresourceoverride.yml
  images/kube-rbac-proxy.yml
  images/ose-aws-efs-csi-driver.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm

#1778 images/cluster-version-operator: auto_label for merge
  images/cluster-version-operator.yml
Labels: lgtm

#1786 Freeze automation to eliminate moving parts
  group.yml
Labels: lgtm

#1794 [ART-4068] streams: update to golang 1.17.10 builders
  streams.yml
Labels: lgtm

#1805 rc.6: replace metadata advisory to prepare-release
  releases.yml
Labels: lgtm

#1807 rpms/openshift{,-clients}: enable el9 builds
  rpms/openshift-clients.yml
  rpms/openshift.yml
Labels: lgtm

#1773 [ART-3883] group.yml: define RHCOS alternate container conf
  group.yml
  releases.yml
Labels: lgtm

#1810 4.12 group.yml: temporarily allow minor golang shear
  group.yml
Labels: lgtm

#1811 [4.10] streams: update golang to 1.17.12
  streams.yml
Labels: lgtm
