Repository openshift-eng/ocp-build-data, pull requests merged in 2023-09, with the labels that each got.

#3425 etcd to rhel9
  images/ose-etcd.yml
  streams.yml
Labels: lgtm, approved

#3460 etcd to rhel9
  images/ose-etcd.yml
Labels: lgtm, approved

#3458 Fix rebase local-storage-operator
  images/local-storage-mustgather.yml
Labels: lgtm

#3463 [4.15] update operand cdn/bundle name to match errata
  images/cloud-event-proxy.yml
  images/local-storage-mustgather.yml
Labels: lgtm, approved

#3464 4.13: etcd to rhel9
  images/ose-etcd.yml
  streams.yml
Labels: lgtm, approved

#3427 [4.15] Document automation_freeze behavior
  group.yml
Labels: lgtm, approved

#3465 sriov-cni to rhel9
  images/sriov-cni.yml
Labels: lgtm, approved

#3466 sriov-cni to rhel9
  images/sriov-cni.yml
Labels: lgtm, approved

#3468 update build config for linuxptp-daemon to use rhel9 base image
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3454 Update etcd and protoc to match k8s 1.28
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#3475 Correct dist-git branches for el9 based images
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/sriov-cni.yml
Labels: lgtm, approved

#3453 Update protoc to match k8s 1.27
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#3476 Also use a rhel9 golang
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3452 Update protoc to match k8s 1.26 and etcd in rhel9 builder to match rhel8
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#3480 ingress-node-firewall to rhel9
  images/ingress-node-firewall-daemon.yml
Labels: lgtm, approved

#3484 [4.15] Enable nfd operator as dependent
  images/kube-rbac-proxy.yml
  images/node-feature-discovery.yml
Labels: approved

#3486 Build on rhel8 branch for now
  images/sriov-cni.yml
Labels: lgtm, approved

#3485 [ART-7067] Enable OLM operators
  images/cloud-event-proxy.yml
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/dpu-network-operator.yml
  images/ib-sriov-cni.yml
  images/ingress-node-firewall-daemon.yml
  images/ingress-node-firewall-operator.yml
  images/kube-rbac-proxy.yml
  images/linuxptp-daemon.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/nmstate-console-plugin.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-csi-external-resizer.yml
  images/ose-csi-external-snapshotter.yml
  images/ose-frr.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved

#3479 update build config for linuxptp-daemon to use rhel9 base image
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3488 update CI build root stream for linuxptp-daemon
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3487 Revert "Build on rhel8 branch for now"
  images/sriov-cni.yml
Labels: lgtm, approved

#3489 Accommodate for rteval inclusion
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#3407 [ART-7273] add modifications to support go 1.19 rhel9 wrapper
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3409 [ART-7273] add modifications to support go 1.19 rhel8 wrapper
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3408 [ART-7273] add modifications to support go 1.18 rhel8 wrapper
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3492 Update network-tools container image to refer to new JIRA component
  product.yml
Labels: lgtm, approved

#3356 [ART-7273] add modifications to support rhel-8-golang-1.17
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm

#3393 Do not look at 4.15.z bugs
  bug.yml
Labels: lgtm, approved

#3493 linuxptp-daemon: Set name_in_bundle to match upstream image-references
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3494 sriov-cni: Fix rhel9 image name in operator
  images/sriov-cni.yml
Labels: lgtm, approved

#3500 pull 4.15 changes for bundle build to 4.14 for linuxptp-daemon
  images/linuxptp-daemon.yml
Labels: lgtm, approved

#3498 Fix rhel9 build stage route override image
  images/ose-multus-route-override-cni.yml
Labels: lgtm, approved

#3496 ART-7241: Add rhel-9-codeready-builder-rpms
  group.yml
Labels: lgtm, approved, jira/valid-reference

#3501 4.14.0-rc.0 - Pin cluster-nfd build to satisfy prepare-release
  releases.yml
Labels: lgtm, approved

#3502 ART-7733 Use 4.15-9.2 for 4.15
  group.yml
Labels: lgtm, approved

#3503 Mark 4.6 as EOL
  group.yml
Labels: lgtm, approved

#3504 Mark 4.7 as EOL
  group.yml
Labels: lgtm, approved

#3505 Mark 4.8 as EOL
  group.yml
Labels: lgtm, approved

#3506 Mark 4.9 as EOL
  group.yml
Labels: lgtm, approved

#3507 Mark 3.11 as EOL
  group.yml
Labels: lgtm

#3508 4.14.0-rc.0 exclude bugs to unblock prepare-release
  releases.yml
Labels: lgtm

#3511 Ignore Node / numa aware scheduling bugs
  bug.yml
Labels: lgtm, approved

#3515 Ignore Node / numa aware scheduling bugs
  bug.yml
Labels: lgtm, approved

#3514 Ignore Node / numa aware scheduling bugs
  bug.yml
Labels: lgtm, approved

#3513 Ignore Node / numa aware scheduling bugs
  bug.yml
Labels: lgtm, approved

#3512 Ignore Node / numa aware scheduling bugs
  bug.yml
Labels: lgtm, approved

#3517 [ART-5526] publish 4.13 operators in 4.14+ index
  group.yml
Labels: lgtm, approved

#3519 [ART-7545] image add ose-secrets-store-csi-mustgather
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#3524 assembly definition for 4.14 rc.1
  releases.yml
Labels: lgtm

#3525 pin ose-secrets-store-csi-mustgather
  releases.yml
Labels: lgtm, approved

#3526 exclude bugs for rc.1 prepare release
  releases.yml
Labels: lgtm, approved

#3434 [ART-4761] add upstream_image_mirror confg in 4.10
  streams.yml
Labels: lgtm, approved

#3431 [ART-4761] add upstream_image_mirror confg in 4.13
  streams.yml
Labels: lgtm, approved

#3432 [ART-4761] add upstream_image_mirror confg in 4.12
  streams.yml
Labels: lgtm, approved

#3433 [ART-4761] add upstream_image_mirror confg in 4.11
  streams.yml
Labels: lgtm, approved

#3474 ART-7273 add tags for rhel9 golang 1.20
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3530 sriov-cni: update name for rhel9
  images/sriov-cni.yml
Labels: lgtm, approved

#3531 Updates `ci_alignment` for OLM components
  images/ose-olm-catalogd.yml
  images/ose-olm-operator-controller.yml
  images/ose-olm-rukpak.yml
Labels: lgtm, approved

#3535 Update ose-vertical-pod-autoscaler product mapping
  product.yml
Labels: lgtm, approved

#3533 Add prefix to automatic PR in storage repos
  images/azure-file-csi-driver.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/csi-snapshot-validation-webhook.yml
  images/ibm-vpc-node-label-updater.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-csi-external-resizer.yml
  images/ose-csi-external-snapshotter.yml
  images/ose-csi-snapshot-controller.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-gcp-pd-csi-driver.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-vmware-vsphere-csi-driver.yml
  images/vmware-vsphere-syncer.yml
Labels: lgtm, approved

#3537 4.14: Add prefix to automatic PR in storage repos
  images/azure-file-csi-driver.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/csi-snapshot-validation-webhook.yml
  images/ibm-vpc-node-label-updater.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-csi-external-resizer.yml
  images/ose-csi-external-snapshotter.yml
  images/ose-csi-snapshot-controller.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-gcp-pd-csi-driver.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-vmware-vsphere-csi-driver.yml
  images/vmware-vsphere-syncer.yml
Labels: lgtm, approved

#3538 Add auto-lgtm to new storage repos
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
Labels: lgtm, approved

#3522 Publish production golang builders to CI
  streams.yml
Labels: lgtm, approved

#3521 Publish production golang builders to CI
  streams.yml
Labels: lgtm, approved

#3540 add modifications to support go wrapper for rhel8 golang 1.20
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3541 rhel9 builds should happen in rhel9 branches/tags
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-agent-installer-node-agent.yml
Labels: lgtm, approved

#3536 Compile assisted-installer-agent for RHEL 9
  images/ose-agent-installer-node-agent.yml
Labels: lgtm, approved

#3543 4.14 GA - Add reasons for why some ocpbugs have wrong pscomponents
  releases.yml
Labels: lgtm, approved

#3542 [4.15] rhel9 builds should happen in rhel9 branches/tags
  images/openshift-kubernetes-nmstate-handler.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-agent-installer-node-agent.yml
Labels: lgtm, approved

#3548 Stop meaningles ovn rebuilds
  images/ovn-kubernetes-base.yml
Labels: lgtm, approved

#3552 Fix codeready builder rhel9 repos
  group.yml
Labels: lgtm, approved

#3555 ART-7821 [4.15] Migrate hyperkube build to rhel9
  images/openshift-enterprise-hyperkube.yml
  releases.yml
Labels: lgtm, approved

#3550 Make rhel-coreos primary rhcos
  group.yml
Labels: lgtm, approved

#3469 OCP-4.14-linkfix: updates links for 4.14 docs url move
  erratatool.yml
Labels: lgtm, approved

#3560 [4.14][ART-7318] make everything ship to prerelease tags for now
  releases.yml
Labels: lgtm, approved

#3557 cvo: label alignment PRs with `qe-approved`
  images/cluster-version-operator.yml
Labels: lgtm, approved

#3558 ose-kube-metrics-server.yml Update payload_name to match upstream
  images/ose-kube-metrics-server.yml
Labels: lgtm, approved

#3567 4.15 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3575 4.7 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3569 4.13 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3571 4.11 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3572 4.10 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3574 4.8 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3570 4.12 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3573 4.9 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3568 4.14 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved

#3576 4.6 Remove obsolete field 'required'
  images/openshift-state-metrics.yml
Labels: lgtm, approved
