Repository openshift-eng/ocp-build-data, pull requests merged in 2023-11, with the labels that each got.

#3829 ART-8110 Bump golang for 4.9
  streams.yml
Labels: lgtm, approved

#3814 Update image for sriov dp admission controller
  images/sriov-dp-admission-controller.yml
Labels: lgtm, approved

#3828 revert #3722 'disable operators until fixed' due to fixing
  images/cluster-nfd-operator.yml
  images/kube-rbac-proxy.yml
  images/node-feature-discovery.yml
Labels: lgtm, approved

#3831 Bump golang builders
  streams.yml
Labels: lgtm

#3769 [ART-7994] ec.1 release: adjust to become an operator pre-release
  releases.yml
Labels: approved

#3837 Add mbiarnes as an owner
  OWNERS
Labels: lgtm, approved

#3840 4.13.20: Exclude bugs
  releases.yml
Labels: lgtm, approved

#3841 4.12.42: Exclude CVE bugs
  bug.yml
  releases.yml
Labels: lgtm, approved

#3843 4.13.20 - Permit invalid errata status
  releases.yml
Labels: lgtm, approved

#3842 Ignore cpaas talm operator bugs
  bug.yml
Labels: lgtm

#3853 OCPBUGS-21942: Revert "[ART-7960] disable clusterresourceoverride until fixed"
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
Labels: lgtm, approved, jira/invalid-bug, jira/severity-critical, jira/valid-reference

#3854 OCPBUGS-21944: Revert "[ART-7960] disable vertical-pod-autoscaler-operator until fixed"
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved, jira/invalid-bug, jira/severity-critical, jira/valid-reference

#3670 Move aws-ebs-csi-driver-operator from its own repo to csi-operator
  images/ose-aws-ebs-csi-driver-operator.yml
Labels: lgtm, approved

#3851 [ART-4932] group.yml: remove machine-os-content
  group.yml
Labels: approved

#3865 exclude bug OCPBUGS-14708
  releases.yml
Labels: lgtm, approved

#3866 exclude bugs for 4.14.2
  bug.yml
  releases.yml
Labels: lgtm, approved

#3868 Promotion permit for 4.14.2
  releases.yml
Labels: lgtm, approved

#3861 ART-8233: Add installer-altinfra to product build.
  product.yml
Labels: lgtm, approved, jira/valid-reference

#3879 Fix 4.15.0-ec.2
  releases.yml
Labels: lgtm, approved

#3880 4.15.0-ec.2: Specify right distgit component
  releases.yml
Labels: lgtm, approved

#3877 [ART-8113][4.15] enable prerelease/advance/bootimage advisories
  erratatool.yml
Labels: lgtm, approved

#3878 [4.15-ec.2] manually include advisories w/ prerelease
  releases.yml
Labels: lgtm, approved

#3881 Explicitly mention name_in_bundle for operators and operands
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/ib-sriov-cni.yml
  images/kube-rbac-proxy.yml
  images/local-storage-diskmaker.yml
  images/local-storage-operator.yml
  images/nmstate-console-plugin.yml
  images/node-feature-discovery.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ptp-operator.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved

#3872 OCPBUGS-21108: Use etcd golang also for operator
  images/cluster-etcd-operator.yml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3883 fix issues in 4.12.44
  releases.yml
Labels: lgtm

#3886 Revert "[ART-4932] group.yml: remove machine-os-content"
  group.yml
Labels: lgtm, approved

#3873 ART-8233 add ose-installer-altinfra
  images/ose-installer-altinfra.yml
Labels: lgtm

#3889 4.14.3 Exclude bugs
  releases.yml
Labels: lgtm

#3894 append -rhel9
  images/cluster-node-tuning-operator.yml
  images/driver-toolkit.yml
  images/ose-baremetal-cluster-api-controllers.yml
  images/ose-cluster-config-api.yml
  images/ose-etcd.yml
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#3893 [ART-7926] Activate sast scanning bugs pipeline for 4.15 sriov
  group.yml
  images/sriov-network-operator.yml
Labels: lgtm, approved

#3896 Set payload name cluster-config-api
  images/ose-cluster-config-api.yml
Labels: lgtm, approved

#3900 cluster resource override operator to rhel9
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
Labels: lgtm, approved

#3901 local storage operator to rhel9
  images/local-storage-diskmaker.yml
  images/local-storage-operator.yml
Labels: lgtm, approved

#3902 ptp-operator to rhel9
  images/cloud-event-proxy.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#3903 vpo operator to rhel9
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved

#3911 ART-8111 Update rhel-9 golang-1.21 branch
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm

#3912 4.12 - Freeze automation until mass rebuilds are complete
  group.yml
Labels: lgtm, approved

#3913 Revert "4.12 - Freeze automation until mass rebuilds are complete"
  group.yml
Labels: lgtm, approved

#3723 ART-6865 4.15 - Enable ci-openshift-golang-builder-latest
  ci_images/rhel-9/ci-openshift-golang-builder-latest/Dockerfile
  images/ci-openshift-golang-builder-extra-rhel9.yml
  images/ci-openshift-golang-builder-latest-rhel9.yml
  images/ci-openshift-golang-builder-previous-rhel9.yml
Labels: lgtm, approved

#3921 Exclude bug(s) for 4.14.4
  releases.yml
Labels: lgtm, approved

#3922 4.13.24: exclude bug(s)
  releases.yml
Labels: lgtm, approved

#3924 recycled advisories from previous run
  releases.yml
Labels: lgtm, approved

#3925 4.13.24: Exclude shipped CVEs
  releases.yml
Labels: lgtm

#3927 4.14.4: Exclude bug
  releases.yml
Labels: lgtm

#3929 4.15 - Change ci golang builder filenames to be consistent with distgit repo name
  images/ci-openshift-golang-builder-extra.yml
  images/ci-openshift-golang-builder-latest.yml
  images/ci-openshift-golang-builder-previous.yml
Labels: lgtm, approved

#3928 4.13.24: Exclude one more
  releases.yml
Labels: lgtm, approved

#3935 4.15 - ART-8111 Define golang-1.21 streams
  streams.yml
Labels: lgtm, approved

#3936 4.14: Change operator_index_mode to ga
  group.yml
Labels: lgtm, approved

#3937 4.15: Remove golang-1.19
  images/ci-openshift-golang-builder-previous.yml
  images/ose-ovn-kubernetes.yml
  streams.yml
Labels: lgtm, approved

#3939 OSDOCS-8829: fix url in microshift 4.14 errata text
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#3941 Restore libvirt-machine-controllers to rhel8
  images/ose-libvirt-machine-controllers.yml
Labels: lgtm, approved

#3891 Remove cachito from AWS EBS CSI driver operator
  images/ose-aws-ebs-csi-driver-operator.yml
Labels: lgtm, approved

#3943 ART-8364 Stop building CI images
  images/ci-openshift-golang-builder-extra.yml
  images/ci-openshift-golang-builder-latest.yml
  images/ci-openshift-golang-builder-previous.yml
Labels: lgtm, approved

#3946 Fixing typo in ose-gcp-cluster-api-controllers-container mapping
  product.yml
Labels: lgtm, approved

#3947 OCPBUGS-24174: cloud-credential-operator to rhel8
  images/ose-cloud-credential-operator.yml
Labels: lgtm, approved, jira/invalid-bug, jira/valid-reference

#3949 ART-8370 Update golang-1.18 with fips wrapper
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm

#3964 Pin dtk until newer rhcos
  releases.yml
Labels: lgtm, approved

#3972 4.11: Do not rebuild because of redhat-release
  releases.yml
Labels: lgtm, approved

#3956 Add web links to RPMs
  rpms/microshift.yml
  rpms/openshift-ansible.yml
  rpms/openshift-clients.yml
  rpms/openshift.yml
  rpms/openshift4-aws-iso.yml
Labels: lgtm, approved
