Repository openshift-eng/ocp-build-data, pull requests merged in 2023-08, with the labels that each got.

#3352 add OWNERS
  OWNERS
Labels: lgtm

#3353 add OWNERS
  OWNERS
Labels: lgtm

#3354 add deps for local storage operator
  images/local-storage-mustgather.yml
Labels: lgtm, approved

#3366 microshift-rebase: Mount docker config into the container
  modifications/microshift-rebase
Labels: lgtm, approved

#2658 Fix jira components for images
  product.yml
Labels: lgtm, approved, tide/merge-method-squash

#3379 ART-7469: Add rpms to product
  product.yml
Labels: jira/valid-reference

#3380 Fix rebase local-storage-mustgather
  images/local-storage-mustgather.yml
Labels: lgtm, approved

#3309 [ART-7273] add modifications to support go wrapper
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3385 4.15: Use right golang builder for etcd
  streams.yml
Labels: lgtm, approved

#3390 4.15 fixes
  images/egress-router-cni.yml
  images/linuxptp-daemon.yml
  images/local-storage-mustgather.yml
  images/multus-cni.yml
  images/ose-containernetworking-plugins.yml
Labels: lgtm, approved

#3391 4.15: Fix etcd
  images/ose-etcd.yml
Labels: lgtm, approved

#3398 [ART-7061] disable olm operators
  images/atomic-openshift-descheduler.yml
  images/cloud-event-proxy.yml
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/dpu-network-operator.yml
  images/ib-sriov-cni.yml
  images/ingress-node-firewall-daemon.yml
  images/ingress-node-firewall-operator.yml
  images/kube-rbac-proxy.yml
  images/linuxptp-daemon.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/nmstate-console-plugin.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-cluster-kube-descheduler-operator.yml
  images/ose-csi-external-resizer.yml
  images/ose-csi-external-snapshotter.yml
  images/ose-frr.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved

#3403 Fix 4.15 nightlies
  images/ose-azure-workload-identity-webhook.yml
Labels: lgtm, approved

#3401 4.15 - Remove operator channel stable config
  group.yml
Labels: lgtm, approved

#3347 add upstream_image_priv confg
  streams.yml
Labels: lgtm, approved

#3421 Revert "[openshift-4.10] [ART-7474] Set freeze_automation to weekdays"
  group.yml
Labels: lgtm, approved

#3422 Disable 4.11 automation
  group.yml
Labels: lgtm, approved

#3424 [ART-7318] introduce pre-release operator_index_mode
  group.yml
Labels: lgtm, approved

#3437 4.14 - Revert "add console-dashboards-plugin.yml"
  images/console-dashboards-plugin.yml
Labels: lgtm

#3436 Revert "[openshift-4.15] [ART-7141] add console-dashboards-plugin.yml"
  images/console-dashboards-plugin.yml
Labels: lgtm

#3438 4.14 - Pin older consistent driver toolkit image
  releases.yml
Labels: lgtm

#3447 Remove driver-toolkit pin
  releases.yml
Labels: lgtm

#3448 Build 4.10 only in weekends
  group.yml
Labels: lgtm, approved

#3449 4.11: etcd to golang-1.19
  images/ose-etcd.yml
  streams.yml
Labels: lgtm, approved

#3430 update operand cdn/bundle name to match errata
  images/cloud-event-proxy.yml
  images/local-storage-mustgather.yml
Labels: lgtm, approved

#3455 Start signing 4.14 rpms
  group.yml
Labels: lgtm, approved
