Repository openshift-eng/ocp-build-data, pull requests merged in 2023-12, with the labels that each got.

#3974 MULTIARCH-4040: Add all arches for Agent Install
  images/ose-machine-os-images.yml
Labels: lgtm, approved, jira/valid-reference

#3976 openstack-cluster-api-controllers-container mapping
  product.yml
Labels: lgtm, approved

#3973 [sast-scan] Enable OCPBUGS workflow for RPMs
  rpms/microshift.yml
  rpms/openshift-ansible.yml
  rpms/openshift-clients.yml
  rpms/openshift.yml
  rpms/openshift4-aws-iso.yml
Labels: lgtm, approved

#3984 ec.3 - Update advisories and release ticket
  releases.yml
Labels: lgtm

#3985 Do not reuse prerelease advisory
  releases.yml
Labels: lgtm, approved

#3987 Build apiserver-network-proxy on etcd_golang stream
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3963 branch openshift-4.16
  bug.yml
  erratatool.yml
  group.yml
  images/ose-cluster-kube-descheduler-operator.yml
  releases.yml
Labels: lgtm, approved

#3995 [scan-osh] Tracking components that ART is shipping but not building
  group.yml
Labels: lgtm, approved

#3997 4.15 - Remove go-1.19 ci buildroot
  streams.yml
Labels: lgtm, approved

#4001 disable OCPBUGS pipeline feature for 4.16
  group.yml
Labels: lgtm, approved

#4014 Revert "Allow conflicting rpms in rhcos for stream assembly"
  releases.yml
Labels: lgtm, approved

#4012 [4.11] Remove some owners in ose-baremetal-operator, baremetal-machine-controller and ironic-agent
  images/baremetal-machine-controller.yml
  images/ironic-agent.yml
  images/ose-baremetal-operator.yml
Labels: lgtm, approved

#4015 [SAST] add missing product mappings
  product.yml
Labels: lgtm, approved

#4010 [4.13] Remove some owners in ose-baremetal-operator and baremetal-machine-controller
  images/baremetal-machine-controller.yml
  images/ose-baremetal-operator.yml
Labels: lgtm, approved

#4023 [4.12] enable SAST OCPBUGS workflow
  group.yml
Labels: lgtm, approved

#4024 4.16 - Pattern match exempt rpms
  images/openshift-enterprise-tests.yml
  images/ose-machine-config-operator.yml
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  releases.yml
Labels: lgtm, approved

#4026 ec.3 set operator index mode to pre-release
  releases.yml
Labels: lgtm, approved

#4008 [4.16] Remove some owners in ose-baremetal-operator and baremetal-machine-controller
  images/baremetal-machine-controller.yml
  images/ose-baremetal-operator.yml
Labels: lgtm, approved

#4007 [4.15] Remove some owners in ose-baremetal-operator and baremetal-machine-controller
  images/baremetal-machine-controller.yml
  images/ose-baremetal-operator.yml
Labels: lgtm, approved

#3999 ART-8307 4.16 - Bump to go1.21
  streams.yml
Labels: lgtm, approved

#4028 [sast] exclude kernel and systemd
  group.yml
Labels: lgtm, approved

#4038 4.16: Revert default golang to 1.20
  streams.yml
Labels: lgtm, approved

#4042 ART-8369: remove descheduler from 4.16
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, jira/valid-reference

#4048 ART-8479: update release phase to get 4.15 signed for RC
  group.yml
Labels: lgtm, approved, jira/valid-reference

#4045 ART-8369: remove descheduler from 4.15
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, approved, jira/valid-reference

#4037 4.11 - Pattern match exempt rpms
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/openshift-base-nodejs.yml
  images/openshift-enterprise-tests.yml
  images/ose-ovn-kubernetes.yml
  releases.yml
Labels: lgtm, approved

#4046 OCPBUGS-23386: add rhel-9-golang in cli artifacts stream
  images/ose-cli-artifacts.yml
Labels: lgtm, approved, jira/invalid-bug, jira/valid-reference

#4040 ART-8170: Use 4.16-9.2 for 4.16
  group.yml
Labels: lgtm, approved, jira/valid-reference

#4067 fix ose-secrets-store-csi-driver-operator reference
  images/ose-secrets-store-csi-driver-operator.yml
Labels: lgtm, approved

#4049 OCPBUGS-25031: Move mustgather to rhel9, decouple from cli image
  images/local-storage-mustgather.yml
Labels: lgtm, approved, jira/invalid-bug, jira/valid-reference

#4068 CMO to golang-1.21
  images/cluster-monitoring-operator.yml
Labels: lgtm, approved

#4050 Remove olm image from any dependents
  images/kube-rbac-proxy.yml
  images/ose-olm-catalogd.yml
  images/ose-olm-operator-controller.yml
  images/ose-olm-rukpak.yml
Labels: lgtm, approved

#4084 Pin dtk to get nightlies
  releases.yml
Labels: lgtm, approved

#4077 exclude bug for 4.13.27
  releases.yml
Labels: lgtm

#4087 Revert "Pin dtk to get nightlies"
  releases.yml
Labels: lgtm, approved

#3996 ART-8419 Introduce installer-terraform-providers base image
  images/ose-baremetal-installer.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-installer.yml
Labels: lgtm, approved

#4072 Move wasmedge spdlog gtest to Node / CRI-O component
  product.yml
Labels: lgtm, approved

#4080 Suggest moving to golang-1.21, listen to upstream for base images
  group.yml
  images/atomic-openshift-cluster-autoscaler.yml
  images/baremetal-runtimecfg.yml
  images/cluster-etcd-operator.yml
  images/cluster-monitoring-operator.yml
  images/cluster-network-operator.yml
  images/coredns.yml
  images/golang-github-openshift-oauth-proxy.yml
  images/hypershift.yml
  images/kube-proxy.yml
  images/oauth-server.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/operator-lifecycle-manager.yml
  images/ose-apiserver-network-proxy.yml
  images/ose-cluster-config-operator.yml
  images/ose-cluster-dns-operator.yml
  images/ose-cluster-ingress-operator.yml
  images/ose-cluster-kube-apiserver-operator.yml
  images/ose-cluster-kube-cluster-api-operator.yml
  images/ose-cluster-kube-storage-version-migrator-operator.yml
  images/ose-cluster-openshift-apiserver-operator.yml
  images/ose-cluster-openshift-controller-manager-operator.yml
  images/ose-kube-storage-version-migrator.yml
  images/ose-kubevirt-cloud-controller-manager.yml
  images/ose-oauth-apiserver.yml
  images/ose-openshift-apiserver.yml
  images/ose-openshift-controller-manager.yml
  images/ose-ovirt-csi-driver.yml
  images/ose-ovirt-machine-controllers.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-mustgather.yml
  images/ose-service-ca-operator.yml
  images/sriov-network-device-plugin.yml
  images/telemeter.yml
  streams.yml
Labels: lgtm

#4027 OCPBUGS-25036: Use openshift-clients rpm
  images/ose-sdn.yml
Labels: lgtm, approved, jira/invalid-bug, jira/valid-reference

#4091 Pin old installer
  releases.yml
Labels: lgtm, approved

#4093 Stop ironic rebuilds
  images/ironic-agent.yml
  images/ironic.yml
Labels: lgtm, approved

#4094 Exclude some member froms from upstream initiative
  images/marketplace-operator.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-tests.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-baremetal-installer.yml
  images/ose-cli-artifacts.yml
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-installer-artifacts.yml
  images/ose-installer.yml
  images/ose-machine-os-images.yml
  images/ose-must-gather.yml
  images/ose-network-tools.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-microshift.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#4095 [sast] exclude ovs and ovn
  group.yml
Labels: lgtm, approved

#4098 Fix alignment PR ovn-base
  images/ovn-kubernetes-base.yml
Labels: lgtm, approved

#4070 Build ironic image with cachito
  images/ironic.yml
Labels: lgtm, approved

#4102 Disable pushing to reg-aws
  group.yml
Labels: lgtm

#4103 OCPBUGS-19685: Use RHEL 9 builder image for ose-agent-installer-utils
  group.yml
  images/ose-agent-installer-utils.yml
Labels: lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#4047 [ART-8416] Add check_external_packages config options - 4.16
  group.yml
Labels: lgtm, approved

#4106 Enable cachito for ironic container
  images/ironic.yml
Labels: lgtm, approved

#4105 Follow-ups on golang and rhel transitions
  images/atomic-openshift-cluster-autoscaler.yml
  images/baremetal-runtimecfg.yml
  images/cluster-etcd-operator.yml
  images/cluster-network-operator.yml
  images/coredns.yml
  images/golang-github-openshift-oauth-proxy.yml
  images/hypershift.yml
  images/ironic-rhcos-downloader.yml
  images/kube-proxy.yml
  images/oauth-server.yml
  images/openshift-enterprise-console-operator.yml
  images/operator-lifecycle-manager.yml
  images/ose-apiserver-network-proxy.yml
  images/ose-azure-workload-identity-webhook.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-capi-operator.yml
  images/ose-cluster-config-api.yml
  images/ose-cluster-config-operator.yml
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-cluster-dns-operator.yml
  images/ose-cluster-ingress-operator.yml
  images/ose-cluster-kube-apiserver-operator.yml
  images/ose-cluster-kube-cluster-api-operator.yml
  images/ose-cluster-kube-storage-version-migrator-operator.yml
  images/ose-cluster-openshift-apiserver-operator.yml
  images/ose-cluster-openshift-controller-manager-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-csi-driver-shared-resource-webhook.yml
  images/ose-csi-driver-shared-resource.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-kube-metrics-server.yml
  images/ose-kube-storage-version-migrator.yml
  images/ose-kubevirt-cloud-controller-manager.yml
  images/ose-nutanix-cloud-controller-manager.yml
  images/ose-nutanix-machine-controllers.yml
  images/ose-oauth-apiserver.yml
  images/ose-openshift-apiserver.yml
  images/ose-openshift-controller-manager.yml
  images/ose-ovirt-csi-driver.yml
  images/ose-ovirt-machine-controllers.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-service-ca-operator.yml
  images/sriov-network-device-plugin.yml
  images/telemeter.yml
Labels: lgtm, approved

#4108 Fix typo ci image
  images/baremetal-runtimecfg.yml
Labels: lgtm, approved

#4107 4.16 - Move router base image to rhel9
  images/openshift-enterprise-haproxy-router.yml
  images/ose-haproxy-router-base.yml
Labels: lgtm, approved

#4097 Revert "Stop ironic rebuilds"
  images/ironic-agent.yml
  images/ironic.yml
Labels: lgtm, approved

#4116 Move SRIOV infiniband CNI to RHEL 9
  images/ib-sriov-cni.yml
Labels: lgtm, approved

#4113 Enable FoD for rpm builder
  group.yml
Labels: lgtm, approved

#4114 Enable FoD for rpm builder
  group.yml
Labels: lgtm, approved
