Repository openshift-eng/ocp-build-data, pull requests merged in 2023-10, with the labels that each got.

#2462 ART-5862 Remove openstack-machine-controllers
  images/ose-openstack-machine-controllers.yml
Labels: lgtm, approved

#3584 ART-7858 fix microshift rebase
  modifications/Dockerfile
  modifications/microshift-rebase
Labels: lgtm, approved

#3554 ART-7821 4.14 - Migrate hyperkube build to rhel9
  images/openshift-enterprise-hyperkube.yml
Labels: lgtm, approved

#3590 Exclude OCPBUGS-11244
  releases.yml
Labels: lgtm, approved

#3587 4.13: Stop eternal rebuilds
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#3597 Exclude bugs with no builds
  releases.yml
Labels: lgtm, approved

#3600 Revert rc.5
  releases.yml
Labels: lgtm, approved

#3602 ART-7894 don't update ci build root for openshift-enterprise-pod in 4.14
  images/openshift-enterprise-pod.yml
Labels: lgtm, approved

#3601 ART-7894 move openshift-enterprise-pod to rhel9 in 4.15
  images/openshift-enterprise-pod.yml
Labels: lgtm, approved

#3520 OCPBUGS-18979: Use RHEL 9 builder image for ose-agent-installer-utils
  images/ose-agent-installer-utils.yml
Labels: lgtm, approved, jira/severity-important, jira/invalid-bug, jira/valid-reference

#3603 Also change base images to rhel9
  images/openshift-enterprise-pod.yml
Labels: lgtm, approved

#3607 Suspend builds
  group.yml
Labels: lgtm, approved

#3606 Suspend builds
  group.yml
Labels: lgtm, approved

#3605 Suspend builds for 4.15
  group.yml
Labels: lgtm, approved

#3610 Revert "Suspend builds for 4.15"
  group.yml
Labels: lgtm, approved

#3608 Revert "Suspend builds"
  group.yml
Labels: lgtm, approved

#3611 Re-enable ose-cluster-kube-descheduler-operator
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, approved

#3609 Revert "Suspend builds"
  group.yml
Labels: lgtm, approved

#3604 Rebuild cri-tools to have new tests running
  releases.yml
Labels: lgtm, approved

#3613 Suspend automation
  group.yml
Labels: lgtm, approved

#3614 Suspend automation
  group.yml
Labels: lgtm, approved

#3594 ART-7892 Add openstack-cluster-api-controllers
  images/openstack-cluster-api-controllers.yml
Labels: lgtm, do-not-merge/hold, approved

#3586 ART-7859 Add cluster-api-provider-metal3
  images/ose-baremetal-cluster-api-controllers.yml
Labels: do-not-merge/hold

#3628 group.yml: end bundle drift from 4.13
  group.yml
Labels: lgtm, approved

#3629 [4.15] group: only do bundle pre-release on demand
  group.yml
Labels: lgtm, approved

#3625 4.7 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
  images/ose-hello-openshift.yml
Labels: lgtm

#3624 4.8 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm

#3623 4.9 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm

#3622 4.10 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm

#3621 4.11 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm

#3620 4.12 Remove global aliases
  group.yml
  images/openshift-enterprise-tests.yml
Labels: lgtm

#3619 4.14 Remove unused global aliases
  group.yml
Labels: lgtm

#3645 Exclude OCPBUGS-18792 from 4.13.16
  releases.yml
Labels: lgtm, approved

#3646 Exclude OCPBUGS-14708
  releases.yml
Labels: lgtm, approved

#3673 rc.5 microshift rebuild with a specific commit
  releases.yml
Labels: lgtm, approved

#3674 Use upstream since priv hasn't synced
  releases.yml
Labels: lgtm, approved

#3677 4.11.51: Pin kata-containers to already shipped build
  releases.yml
Labels: lgtm, approved

#3680 Explicitly include and exclude bugs from rc.6
  releases.yml
Labels: lgtm, approved

#3681 Build microshift from a specific commit for rc.6
  releases.yml
Labels: lgtm, approved

#3683 Stop building dpu-network-operator
  images/dpu-network-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#3685 4.10: Build on x86_64 exclusively
  group.yml
Labels: lgtm, approved

#3689 exclude bug for 4.13.17
  releases.yml
Labels: lgtm, approved

#3688 exclude bugs for 4.12.39
  releases.yml
Labels: lgtm, approved

#3696 previous ad was dropped
  releases.yml
Labels: lgtm, approved

#3697 Include CVE fixes
  releases.yml
Labels: lgtm, approved

#3700 Remove extraneous tabs
  releases.yml
Labels: lgtm, approved

#3702 [rhel-8-golang-1.19] Tag into hotfix tags; update wrapper script path; update repo path
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm

#3703 [rhel-9-golang-1.19] Tag into hotfix tags; update wrapper script path; update repo path
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm

#3706 [rhel-8-golang-1.20] Tag into hotfix tags; update wrapper script path; update repo path
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm

#3705 [rhel-9-golang-1.20] Tag into hotfix tags; update wrapper script path; update repo path
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm

#3707 ART-7949 - 4.13 - Bump golang builder
  streams.yml
Labels: lgtm

#3708 ART-7948 - 4.12 - Bump golang builders
  streams.yml
Labels: lgtm, approved

#3671 [ART-7927] releases: add art7927 assembly
  releases.yml
Labels: lgtm, approved

#3709 ART-7947 - 4.11 - Bump golang builders
  streams.yml
Labels: lgtm, do-not-merge/hold, approved

#3710 ART-7950 - 4.14 - Bump golang builders
  streams.yml
Labels: lgtm, do-not-merge/hold, approved

#3634 ART-7945 4.6 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs-runtime.yml
  images/openshift-base-nodejs.yml
  images/openshift-base-python.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-ruby.yml
Labels: lgtm, approved

#3635 ART-7945 4.7 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
Labels: lgtm, approved

#3636 ART-7945 4.8 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
Labels: lgtm, approved

#3711 bump golang to 1.20.10/1.19.13
  streams.yml
Labels: lgtm, approved

#3616 sriov-network-operator to rhel9
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved

#3690 rhel 7 golang 1.16: Build with -hotfix target
  group.yml
Labels: lgtm

#3713 releases.yml: [ART-7927] get new advisories for assembly
  releases.yml
Labels: lgtm, approved

#3714 Disable early kernel tagging for 4.14
  group.yml
Labels: lgtm, approved

#3715 Disable early kernel tagging for 4.13
  group.yml
Labels: lgtm, approved

#3669 ART-7945 3.11 ocp-build-data has moved to openshift-eng
  images/openshift-base-elasticsearch.yml
  images/openshift-base-jboss.yml
  images/openshift-base-nodejs-runtime.yml
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel7.yml
  images/openshift-enterprise-apb-base.yml
Labels: lgtm

#3643 ART-7945 4.15 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3641 ART-7945 4.14 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3642 ART-7945 4.12 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3640 ART-7945 4.13 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3639 ART-7945 4.11 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3638 ART-7945 4.10 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
Labels: lgtm

#3720 Revert "ART-7945 4.14 ocp-build-data moved to openshift-eng"
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm

#3716 Revert "ART-7945 4.10 ocp-build-data moved to openshift-eng"
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
Labels: lgtm

#3727 exclude ovn bug for 4.12.40
  releases.yml
Labels: lgtm, approved

#3728 exclude ovn bug
  releases.yml
Labels: lgtm, approved

#3729 ose-azure-workload-identity-webhook-container->Hive
  product.yml
Labels: lgtm, approved

#3545 change 4.15 configuration for ptp-operator to rhel-9 base
  images/ptp-operator.yml
Labels: lgtm, approved

#3731 Include golang bump trackers
  releases.yml
Labels: lgtm, approved

#3734 Partial 4.12 golang bump include
  releases.yml
Labels: lgtm, approved

#3732 Disable golang wrapper output in CI
  ci_transforms/rhel-9/ci-build-root/Dockerfile
  ci_transforms/rhel-9/golang/Dockerfile
Labels: lgtm

#3733 Disable golang wrapper output in CI
  ci_transforms/rhel-9/ci-build-root/Dockerfile
  ci_transforms/rhel-9/golang/Dockerfile
Labels: lgtm

#3668 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3651 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3667 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3666 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3665 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3663 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3661 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3660 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3659 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3658 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3647 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3649 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3652 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3653 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3656 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3655 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3654 ART-7945 ocp-build-data has moved to openshift-eng
  images/openshift-golang-builder.yml
Labels: do-not-merge/hold

#3737 ART-7945 4.15 ocp-build-data moved to openshift-eng
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: do-not-merge/hold

#3745 ART-7952 Tag into hotfix tags; update wrapper script path; update repo path
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#3749 Exempt tzdata 4.15
  releases.yml
Labels: lgtm, approved

#3763 Fix ose-apiserver-network-proxy branch
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3774 Update microshift target config
  rpms/microshift.yml
Labels: lgtm, approved

#3776 Define arches for mucroshift rpm to be synced
  rpms/microshift.yml
Labels: lgtm, approved

#3775 ART-7991 Bump nodejs to 18
  streams.yml
Labels: lgtm, approved

#3778 add cluster-config-api component mapping
  product.yml
Labels: lgtm, approved

#3777 descheduler[-operator]: bump rhel version to rhel9
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, approved

#3779 fix deschedular comet repo names
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, approved

#3771 disable alignment pr
  images/multus-cni.yml
Labels: lgtm, approved

#3781 4.11 disable apiserver alignment PRs
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3783 4.13 disable apiserver alignment PRs
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3784 4.14 Disable alignment PRs for apiserver
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3782 4.12 disable apiserver alignment PRs
  images/ose-apiserver-network-proxy.yml
Labels: lgtm, approved

#3785 4.15 ose-cluster-kube-descheduler-operator: use rhel9 distgit branch
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, approved

#3788 4.15 Fix atomic-openshift-descheduler name in bundle
  images/atomic-openshift-descheduler.yml
Labels: lgtm, approved

#3756 Exempt tzdata 4.11
  releases.yml
Labels: lgtm, approved

#3757 Exempt tzdata 4.12
  releases.yml
Labels: lgtm, approved

#3746 Stop triggering meaningless ovn rebuilds
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#3759 Exempt tzdata 4.14
  releases.yml
Labels: lgtm, approved

#3792 Stop 4.13 ovn rebuilds
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#3793 ose-baremetal-operator-container mapping
  product.yml
Labels: lgtm, approved

#3747 Update clusterresourceoverride component mapping
  product.yml
Labels: lgtm, approved

#3794 4.14.0 Make metadata silentops
  releases.yml
Labels: lgtm

#3802 4.12.41 Include/exclude bugs
  releases.yml
Labels: lgtm, approved

#3796 Add 4.14.0 assembly and ignore non shippable bug
  releases.yml
Labels: lgtm, approved

#3805 4.13.19 Fix issues
  releases.yml
Labels: lgtm, approved

#3806 OCPBUGS-20211: Enable sriov operator
  images/ib-sriov-cni.yml
  images/sriov-cni.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved, jira/invalid-bug, jira/severity-critical, jira/valid-reference

#3807 Exclude OCPBUGS-22128
  releases.yml
Labels: lgtm, approved

#3809 4.14.0 - Ignore nightly that got GC'd
  releases.yml
Labels: lgtm

#3799 ART-7727 move ose-metallb to RHEL9
  images/ose-frr.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
Labels: lgtm, approved

#3813 Add release 4.14.1
  releases.yml
Labels: lgtm, approved

#3815 Remove reference releases from 4.14.1 definition
  releases.yml
Labels: lgtm, approved

#3817 Exclude bugs
  releases.yml
Labels: lgtm, approved

#3818 Exclude bugs
  releases.yml
Labels: lgtm, approved

#3819 Exclude bugs
  releases.yml
Labels: lgtm, approved

#3820 Remove redundant advisories field
  releases.yml
Labels: lgtm, approved

#3826 Start looking for 4.14.z bugs
  bug.yml
Labels: lgtm, approved

#3827 Also do not trigger on ovn*vtep
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#3798 ART-7999 add ose-cluster-config-api
  images/ose-cluster-config-api.yml
Labels: lgtm, approved

#3825 Fix 1.16 rhel7 golang-builder
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm

#3830 [cluster-config-api] remove -rhel9 suffix
  images/ose-cluster-config-api.yml
Labels: lgtm
