Repository openshift-eng/ocp-build-data, pull requests merged in 2024-06, with the labels that each got.

#4911 Explicitly enable cachito for nmstate-console
  images/nmstate-console-plugin.yml
Labels: lgtm, approved

#4912 [4.14] fix sriov-cni rebase
  images/sriov-cni.yml
Labels: lgtm, do-not-merge/hold, approved

#4906 ART-9793 Introduce 'signing' release phase
  group.yml
Labels: lgtm, approved

#4921 Fixing two Telco component mappings
  product.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4924 4.15.17: pin cri-o
  releases.yml
Labels: lgtm, approved

#4927 4.15.17: pin el8 cri-o
  releases.yml
Labels: lgtm, approved

#4928 pinned crio version
  releases.yml
Labels: lgtm, approved

#4929 minor fixes in pinned crio versions
  releases.yml
Labels: lgtm, approved

#4932 added promotion-permits
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#4930 Be more strict for 4.16 nightly consistency checks
  releases.yml
Labels: lgtm, approved

#4935 4.16 - Ptp golang to rhel9 + enable ci alignment
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
Labels: lgtm, approved, tide/merge-method-squash

#4936 ptp tweaks: Manual cherrypick of 4935
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#4941 [4.17.0] Adjust ec0 assembly
  releases.yml
Labels: lgtm, do-not-merge/hold

#4894 [ART-9556] Look at early-kernel-candidate
  group.yml
Labels: lgtm, approved

#4944 Remove altinfra modification
  images/ose-installer-altinfra.yml
Labels: lgtm, approved

#4947 OCPBUGS-34739: pause/pod: stop aligning go build root
  images/openshift-enterprise-pod.yml
Labels: lgtm, approved, jira/invalid-bug, jira/valid-reference

#4953 add dependent to kube-rbac-proxy
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#4950 pin DTK to match rhcos in 4.17
  releases.yml
  streams.yml
Labels: lgtm, approved

#4955 4.16 - Prep advance advisory rc.4
  releases.yml
Labels: lgtm, approved

#4956 Have route-override image use standard enterprise base
  images/ose-multus-route-override-cni.yml
Labels: lgtm, approved

#4961 add promotion_permits
  releases.yml
Labels: lgtm, approved

#4966 Move cvo to rhel-9-golang-1.21
  images/cluster-version-operator.yml
Labels: lgtm, approved

#4968 4.16 - Ignore bug of removed image
  releases.yml
Labels: lgtm, approved

#4970 Move to enterprise base for OKD to have uuidgen binary
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: lgtm, approved

#4972 Mapping for networking-console-plugin-container
  product.yml
Labels: lgtm, approved

#4971 Move to enterprise base for OKD to have uuidgen binary
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: lgtm, approved

#4967 Revert "Move cvo to rhel-9-golang-1.21"
  images/cluster-version-operator.yml
Labels: lgtm, approved

#4965 hotfix console: Do not do go mod in cachito
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#4974 ART-9931 Move 4.12 RHEL 8.6 to E4S
  group.yml
Labels: lgtm, approved

#4977 4.16 - Define rc.6 assembly
  releases.yml
Labels: lgtm, approved

#4920 ART-9329: added ose-sriov-network-metrics-exporter
  product.yml
Labels: lgtm, approved, jira/valid-reference

#4919 ART-9329: added ose-sriov-network-metrics-exporter image
  images/ose-sriov-network-metrics-exporter.yml
Labels: lgtm, approved, jira/valid-reference

#4980 Revert "ART-9931 Move 4.12 RHEL 8.6 to E4S"
  group.yml
Labels: lgtm, approved

#4987 Nutanix CCM should use commit prefix
  images/ose-nutanix-cloud-controller-manager.yml
Labels: lgtm, approved

#4989 pin advisory ids
  releases.yml
Labels: lgtm

#4982 ART-9391 [4.15] Update to ubi8 repos and base images
  group.yml
  streams.yml
Labels: lgtm, approved

#4991 rc.7 assembly
  releases.yml
Labels: lgtm, approved

#4994 rc.8 assembly
  releases.yml
Labels: lgtm, approved

#4996 Pin ovn rpm in rc.8 images
  releases.yml
Labels: lgtm, tide/merge-method-squash

#4997 pin ose-sriov-network-metrics-exporter
  releases.yml
Labels: lgtm, approved

#4998 Define 4.16 rc.9 assembly
  releases.yml
Labels: lgtm, approved

#5003 prep 4.16.0 GA assembly
  releases.yml
Labels: lgtm, approved

#5004 override permits to []
  releases.yml
Labels: lgtm, approved

#5005 override permits with {}
  releases.yml
Labels: lgtm

#5011 start looking z stream bug for 4.16
  bug.yml
Labels: lgtm, approved

#5016 Stop building and shipping sriov-operator until backport of OCPBUGS-3…
  images/sriov-network-operator.yml
Labels: lgtm, approved

#5018 4.17: Get kmaint bug tracking set up
  bug.yml
Labels: lgtm, approved

#5017 Get 4.16 in post-GA state
  bug.yml
  group.yml
Labels: lgtm, approved

#5019 add permits for ec.1
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#5015 [ART-10029] bump rhel-9 golang to 1.22.4
  streams.yml
Labels: lgtm, approved

#5023 [ART-9503] [4.11] replace repo URLs with the new ocp-artifacts host
  group.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5022 Unpin dtk for 4.17
  releases.yml
Labels: lgtm, approved

#5025 Fix installer-altinfra rebase
  images/ose-installer-altinfra.yml
Labels: lgtm, approved
