Repository openshift-eng/ocp-build-data, pull requests merged in 2024-05, with the labels that each got.

#4659 agent-installer-api-server to rhel9
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-csr-approver.yml
Labels: lgtm, approved

#4768 [4.15.12] include bugs
  releases.yml
Labels: lgtm, approved

#4769 [4.14.24] include bugs
  releases.yml
Labels: lgtm, approved

#4770 [4.15.12] exclude bugs
  releases.yml
Labels: lgtm, approved

#4772 4.14.24 attached bugs promotion permit
  releases.yml
Labels: lgtm, approved

#4777 smb-csi-driver-operator: fix valid-subscription-label
  images/ose-smb-csi-driver-operator.yml
Labels: lgtm, approved

#4774 Etcd installer
  images/ose-installer-etcd-artifacts.yml
Labels: lgtm, approved

#4780 WRKLDS-1251: cli to rhel9
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-deployer.yml
  images/ose-cli-artifacts.yml
  images/ose-tools.yml
Labels: lgtm, approved, jira/valid-reference

#4784 ovn: Ignore python deps in cachito
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#4787 add rc.0
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#4789 WRKLDS-1257: must-gather and descendants to rhel9
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-must-gather.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved, jira/valid-reference

#4781 CORS-3191: installer: add kas/etcd deps to images
  images/ose-baremetal-installer.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
  images/ose-installer.yml
Labels: lgtm, approved, jira/valid-reference

#4794 Fix installer etcd build
  images/ose-installer-etcd-artifacts.yml
Labels: lgtm, approved

#4802 fix terraform image name for ci
  images/ose-installer-terraform-providers.yml
Labels: lgtm, approved

#4796 Tweak microshift container names
  images/container-networking-plugins-microshift.yml
  images/multus-cni-container-microshift.yml
Labels: lgtm, approved

#4820 Fix 94 rt repos
  group.yml
Labels: lgtm, approved

#4788 added new images
  images/aws-kms-encryption-provider.yml
  images/azure-kms-encryption-provider.yml
Labels: lgtm, approved

#4836 [4.16.0-rc.1] pin aws-kms-encryption-provider
  releases.yml
Labels: lgtm, approved

#4835 Prune alternative-upstream
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-operator-sdk.yml
  images/ose-agent-installer-orchestrator.yml
  images/ose-egress-http-proxy.yml
Labels: lgtm, approved

#4834 Fix ci-build-root build failures
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#4845 [smb-csi-driver] fix name name_in_bundle
  images/ose-smb-csi-driver.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4850 fix ci golang stream
  images/aws-kms-encryption-provider.yml
  images/azure-kms-encryption-provider.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4847 4.14: Stop alignment PRs alibaba-cloud-provider
  images/ose-alibaba-cloud-controller-manager.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4852 Update smb-csi-driver name in bundle to match image_references
  images/ose-smb-csi-driver.yml
Labels: lgtm, approved

#4864 pin openshift-kubernetes-nmstate-operator, ose-metallb-operator
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4860 etcd on golang 1.21
  images/ose-etcd.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4866 stabilize-4.16
  group.yml
  images/marketplace-operator.yml
  images/oauth-server.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-tests.yml
  images/ose-aws-efs-utils.yml
  images/ose-baremetal-installer.yml
  images/ose-cli-artifacts.yml
  images/ose-cluster-config-operator.yml
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-installer-artifacts.yml
  images/ose-installer.yml
  images/ose-kubevirt-cloud-controller-manager.yml
  images/ose-machine-os-images.yml
  images/ose-must-gather.yml
  images/ose-ovn-kubernetes.yml
  images/ose-service-ca-operator.yml
  images/ovn-kubernetes-microshift.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#4868 [4.16.0] rc.2 operator pre-release
  releases.yml
Labels: lgtm, approved

#4874 [ART-9118] add rhel-8-golang-1.22 builder
  streams.yml
Labels: lgtm, approved

#4875 Clean up after rhel9 move
  images/marketplace-operator.yml
  images/oauth-server.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-helm-operator.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-tests.yml
  images/ose-aws-efs-utils.yml
  images/ose-baremetal-installer.yml
  images/ose-cli-artifacts.yml
  images/ose-cluster-config-operator.yml
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-installer-artifacts.yml
  images/ose-installer.yml
  images/ose-kubevirt-cloud-controller-manager.yml
  images/ose-machine-os-images.yml
  images/ose-must-gather.yml
  images/ose-ovn-kubernetes.yml
  images/ose-service-ca-operator.yml
  images/ovn-kubernetes-microshift.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#4879 MON-3876: Add auto_label for stream PRs to monitoring images
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/kube-state-metrics.yml
  images/openshift-state-metrics.yml
  images/ose-kube-metrics-server.yml
  images/ose-prometheus-adapter.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator-admission-webhook.yml
  images/prometheus-operator.yml
  images/telemeter.yml
  images/thanos.yml
Labels: lgtm, approved, jira/valid-reference

#4873 Enable openshift-clients rpm
  rpms/openshift-clients.yml
Labels: lgtm, approved

#4880 Fix owners for images/kube-rbac-proxy.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#4885 4.17 to golang 1.22
  group.yml
  images/dpu-network-operator.yml
  images/egress-router-cni.yml
  images/ib-sriov-cni.yml
  images/monitoring-plugin.yml
  images/multus-cni.yml
  images/networking-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-ansible-operator.yml
  images/ose-cli-artifacts.yml
  images/ose-cloud-credential-operator.yml
  images/ose-containernetworking-plugins.yml
  images/ose-etcd.yml
  images/ose-installer-etcd-artifacts.yml
  images/ose-machine-config-operator.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
  images/ose-network-interface-bond-cni.yml
  images/ose-ovn-kubernetes.yml
  images/ose-sdn.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  streams.yml
Labels: lgtm, approved

#4892 Fix metadata for golang streams
  streams.yml
Labels: lgtm, approved

#4904 [4.17] disable cachito for images using 1.22
  images/baremetal-machine-controller.yml
  images/ose-olm-operator-controller.yml
Labels: lgtm, approved

#4905 Fix sriov-cni rebase
  images/ib-sriov-cni.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only
