Repository openshift-eng/ocp-build-data, pull requests merged in 2024-11, with the labels that each got.

#5612 4.17: Enable gcp-workload-identity-federation-webhook
  images/gcp-workload-identity-federation-webhook.yml
Labels: lgtm, approved

#5579 [ART-11159] Remove ose-prometheus-adapter
  images/ose-prometheus-adapter.yml
Labels: lgtm, approved

#5602 [ART-11115] Remove ose-alibaba-machine-controllers
  images/ose-alibaba-machine-controllers.yml
Labels: lgtm, approved

#5603 [ART-11174] Remove ose-alibaba-cloud-controller-manager
  images/ose-alibaba-cloud-controller-manager.yml
Labels: lgtm, approved

#5616 4.17: Remove alibaba-machine-controllers
  images/ose-alibaba-machine-controllers.yml
Labels: lgtm, approved

#5614 Remove cluster-platform-operators-manager from 4.16
  images/ose-cluster-platform-operators-manager.yml
Labels: lgtm, approved

#5617 4.14: Stop eternal rebuild loop for ovn-kubernets
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#5622 create openshift-4.19 branch
  bug.yml
  erratatool.yml
  group.yml
  releases.yml
Labels: lgtm, approved

#5621 Use release controller public key for OKD verification
  images/ose-cluster-update-keys.yml
Labels: lgtm, approved

#5624 Remove caching of legacy manila CSI dir
  images/csi-driver-manila-operator.yml
Labels: lgtm, approved

#5651 enable nfd operator / cro operator
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#5620 Add insights-runtime-extractor
  images/ose-insights-runtime-extractor.yml
Labels: lgtm, approved

#5660 centos base image: Mirror manifest list
  streams.yml
Labels: lgtm, approved

#5661 Do not mirror centos_rhel{8,9}
  streams.yml
Labels: lgtm, approved

#5640 [ART-11252] add insights-runtime-exporter
  images/ose-insights-runtime-exporter.yml
Labels: lgtm, approved

#5667 ART-11251: [4.19][konflux] update vendor to RedHat, Inc.
  images/atomic-openshift-cluster-autoscaler.yml
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/container-networking-plugins-microshift.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/csi-provisioner.yml
  images/golang-github-openshift-oauth-proxy.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/kube-rbac-proxy.yml
  images/kube-state-metrics.yml
  images/multus-cni-container-microshift.yml
  images/multus-cni.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/operator-lifecycle-manager.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-haproxy-router-base.yml
  images/ose-insights-runtime-exporter.yml
  images/ose-installer-etcd-artifacts.yml
  images/ose-installer-kube-apiserver-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-olm-operator-controller.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: lgtm, tide/merge-method-squash, jira/valid-reference

#5678 4.13: Re-enable repos for ose-gcp-filestore-csi-driver
  images/ose-gcp-filestore-csi-driver.yml
Labels: lgtm, approved

#5681 included bug in 4.16.22
  releases.yml
Labels: lgtm, approved

#5683 Add assembly 4.16.23
  releases.yml
Labels: lgtm, approved

#5677 [ART-11187] update golang to 1.23
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#5682 Stop building ocp 4.12 for s390x arch
  group.yml
Labels: lgtm, approved

#5665 CFE-1176: Update openshift-enterprise-ansible-operator 4.16 image configuration to use pip from openshift/ansible-operator-plugins repo
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5690 ART-11059: 4.18: Get ready for RCs
  group.yml
  releases.yml
Labels: lgtm, approved, jira/valid-reference

#5692 Set 4.18 to signing release phase
  group.yml
Labels: lgtm, approved

#5707 Revert "Freeze 4.19 automation for now"
  group.yml
Labels: lgtm, approved

#5709 4.15.39: explicitly include python-waitress
  releases.yml
Labels: lgtm

#5711 Revert "ART-11389 - Bump 4.18 golang builders to 1.22.9"
  streams.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5694 4.13: limit arches to x86_64, build only in weekends
  group.yml
Labels: lgtm, approved

#5723 ART-11432: 4.19: Do not yet open reconciliation prs
  group.yml
Labels: lgtm, approved, jira/valid-reference

#5618 ART-8910: Switch to multi in ci
  ci_transforms/rhel-7/base-repos/Dockerfile
  ci_transforms/rhel-7/ci-build-root/Dockerfile
  ci_transforms/rhel-7/golang/Dockerfile
  ci_transforms/rhel-8/base-repos/Dockerfile
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-8/ci-build-root/OWNERS
  ci_transforms/rhel-8/golang/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
  ci_transforms/rhel-9/golang/Dockerfile
  images/atomic-openshift-cluster-autoscaler.yml
  images/ci-openshift-base.rhel9.yml
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-build-root-previous.rhel8.disabled
  images/ci-openshift-build-root-previous.rhel9.disabled
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.disabled
  images/ci-openshift-golang-builder-previous.rhel9.disabled
  images/golang-github-openshift-oauth-proxy.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-builder.yml
  images/ose-cluster-samples-operator.yml
  images/ose-frr.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
  streams.yml
Labels: lgtm, approved, jira/valid-reference

#5732 Fix openstack-16-for-rhel-8-rpms repo
  group.yml
Labels: lgtm, approved

#5739 Enable previous golang
  images/ci-openshift-build-root-previous.rhel8
  images/ci-openshift-build-root-previous.rhel9
  images/ci-openshift-golang-builder-previous.rhel8
  images/ci-openshift-golang-builder-previous.rhel9
Labels: lgtm, approved

#5736 Revert "Freeze automation"
  group.yml
Labels: lgtm, approved

#5740 4.18: Allow some outdatedness in rhcos
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5738 Revert "[openshift-4.12] Freeze automation"
  group.yml
Labels: lgtm, approved

#5741 disable vertical-pod-autoscaler-operator build
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#5727 Revert "Revert "ART-11389 - Bump 4.18 golang builders to 1.22.9""
  streams.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5742 Add germanparente git user to 4.12 branch
  OWNERS
Labels: lgtm, approved

#5743 Start relying on ci base image for CI
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
  images/openshift-base-rhel9.yml
Labels: lgtm, approved

#5745 Add jq to build root CI images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5746 Re-enable vertical-pod-autoscaler-operator build
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#5710 ART-11334: added ose-azure-service-operator image
  images/ose-azure-service-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5713 SDN-5457: Move kube-proxy image from openshift/sdn to openshift/kubernetes
  images/kube-proxy.yml
Labels: lgtm, approved, jira/valid-reference

#5703 OCPCRT-339: Update with missing components
  product.yml
Labels: lgtm, approved, jira/valid-reference

#5747 ci-buildroot images: Fix dnf install at brew build time
  ci_images/dnf_wrapper.sh
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-8/ci-openshift-golang-builder/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-9/ci-openshift-golang-builder/Dockerfile
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
Labels: lgtm, approved

#5752 Bump base image of rhel8 golang builder to 8.10
  group.yml
  streams.yml
Labels: lgtm, approved

#5757 4.12.70: python-waitress for CVE
  releases.yml
Labels: lgtm, approved

#5758 Remove doozer env vars from ci-openshift golang images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-golang-builder/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-golang-builder/Dockerfile
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
Labels: lgtm, approved

#5759 rhel8 golang: Add codeready builder repo
  group.yml
Labels: lgtm, approved

#5766 CNTRLPLANE-1: Update etcd to match k8s 1.32
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved, jira/valid-reference
