Repository openshift-eng/ocp-build-data, pull requests merged in 2024-02, with the labels that each got.

#4324 [4.16] Disable canonical builders for machine-config-operator
  images/ose-machine-config-operator.yml
Labels: lgtm, approved

#4327 Disable cachito pkg_managers for STONEBLD-1973
  images/ose-machine-api-provider-azure.yml
Labels: lgtm, approved

#4329 [4.16] re-enable canonical builders for machine-config-operator
  images/ose-machine-config-operator.yml
Labels: lgtm, approved

#4330 Microshift: Use go1.21 for rebase
  modifications/Dockerfile
Labels: lgtm, approved

#4317 [ART-8354] migrate csi drivers to rhel9
  images/azure-file-csi-driver-operator.yml
  images/csi-driver-manila-operator.yml
  images/ose-alibaba-disk-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
Labels: lgtm, approved

#4310 Fix cli-artifacts from statements
  images/ose-cli-artifacts.yml
Labels: lgtm, approved

#4339 exclude bugs for 4.15 rc
  releases.yml
Labels: lgtm, approved

#4342 Add prerelease
  releases.yml
Labels: lgtm, approved

#4343 Make ec.2 build-sync compliant
  releases.yml
Labels: lgtm, approved

#4344 Another component for the security profiles operator maintainers
  product.yml
Labels: lgtm, approved

#4348 4.11 stream builds not on weekdays
  group.yml
Labels: lgtm, approved

#4347 Temporarily disable cachito gomod handling for nutanix-machine-controllers
  images/ose-nutanix-machine-controllers.yml
Labels: lgtm, approved

#4345 Fix ptp-operator stream
  images/ptp-operator.yml
Labels: lgtm, approved

#4351 added ose-aws-ecr-image-credential-provider
  product.yml
Labels: lgtm, approved

#4352 Fix 4.15 rc.5 prerelease
  releases.yml
Labels: lgtm

#4341 Update ose-cli-artifacts
  images/ose-cli-artifacts.yml
Labels: lgtm, approved

#4356 [4.16] Disable alignment PRs for ptp components
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#4357 Remove kernel-rt from require_consistency
  group.yml
Labels: lgtm, approved

#4353 [4.16] Enable canonical builders for images that moved to rhel 9
  images/ose-oauth-apiserver.yml
  images/ose-ovirt-csi-driver.yml
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved

#4354 [4.16] Define alternative_upstream configs
  images/marketplace-operator.yml
  images/oauth-server.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/ose-cluster-config-operator.yml
  images/ose-cluster-openshift-controller-manager-operator.yml
  images/ose-kubevirt-cloud-controller-manager.yml
  images/ose-openshift-controller-manager.yml
  images/ose-service-ca-operator.yml
  images/telemeter.yml
Labels: lgtm, approved

#4358 Fix build root defs ovn
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm

#4361 in to cri-o version provided by rhcos in nightly
  releases.yml
Labels: lgtm, approved

#4312 [ART-6890] Create CI image metadatas and Dockerfiles
  ci_images/dnf_wrapper.sh
  ci_images/install_dnf_wrapper.sh
  ci_images/install_etcd.sh
  ci_images/install_protoc.sh
  ci_images/rhel-8/ci-openshift-base/Dockerfile
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-golang-builder/Dockerfile
  ci_images/rhel-9/ci-openshift-base/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-golang-builder-latest/Dockerfile
  ci_images/rhel-9/ci-openshift-golang-builder/Dockerfile
  group.yml
  images/ci-openshift-base.rhel8.yml
  images/ci-openshift-base.rhel9.yml
  images/ci-openshift-build-root-extra.rhel9.disabled
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-extra.rhel9.disabled
  images/ci-openshift-golang-builder-extra.yml
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/ci-openshift-golang-builder-latest.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
  images/ci-openshift-golang-builder-previous.yml
  streams.yml
Labels: lgtm, approved

#4364 Add assembly 4.13.33
  releases.yml
Labels: lgtm, approved

#4306 Disable canonical builders for ART images
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm, approved

#4379 [4.16] disable cachito for cluster-etcd-operator
  images/cluster-etcd-operator.yml
Labels: lgtm, approved

#4355 STOR-1354, STOR-1611: Remove Alibaba CSI driver and IBM node labeler
  images/ibm-vpc-node-label-updater.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-alibaba-disk-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#4383 Fix misplaced ci_alignment PR disabling
  images/ci-openshift-base.rhel8.yml
  images/ci-openshift-base.rhel9.yml
  images/ci-openshift-build-root-extra.rhel9.disabled
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-extra.rhel9.disabled
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
  images/egress-router-cni.yml
  images/multus-cni.yml
  images/ose-containernetworking-plugins.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#4386 [4.16] Bump egress-dns-proxy to rhel9
  images/openshift-enterprise-egress-dns-proxy.yml
Labels: lgtm, approved

#4387 Mark 4.11 EOL
  group.yml
Labels: lgtm

#4389 Include/exclude relevant tracker bugs
  releases.yml
Labels: lgtm

#3944 openshift-4.15 Remove image openshift-proxy-pull-test
  images/openshift-proxy-pull-test.yml
Labels: lgtm, approved

#4407 Changed openshift-golang-builder-container routing to Security
  product.yml
Labels: lgtm, approved

#4410 [4.15] Fix misplaced ci_alignment PR disabling
  images/ci-openshift-golang-builder-extra.yml
  images/ci-openshift-golang-builder-latest.yml
  images/ci-openshift-golang-builder-previous.yml
  images/egress-router-cni.yml
  images/multus-cni.yml
  images/ose-containernetworking-plugins.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: lgtm, approved

#4411 [4.16] build enterprise-tests with golang 1.21
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4413 Switch azure-file to csi-operator
  images/azure-file-csi-driver.yml
Labels: lgtm, approved

#4349 Revert "Temporarily disable cachito gomod handling for nutanix-machine-controllers"
  images/ose-nutanix-machine-controllers.yml
Labels: lgtm, approved

#4417 [4.16] re-enable cachito processing
  images/azure-file-csi-driver-operator.yml
  images/cluster-etcd-operator.yml
  images/cluster-storage-operator.yml
  images/cluster-version-operator.yml
  images/csi-driver-manila-operator.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-cluster-autoscaler-operator.yml
  images/ose-cluster-cloud-controller-manager-operator.yml
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-cluster-csi-snapshot-controller-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-ibm-cloud-controller-manager.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-operator.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/vsphere-problem-detector.yml
Labels: lgtm, approved

#4418 [4.16] re-enable canonical builders for telemeter
  images/telemeter.yml
Labels: lgtm, approved

#4419 TRT-1523: Revert #4413 "Switch azure-file to csi-operator"
  images/azure-file-csi-driver.yml
Labels: lgtm, approved, jira/valid-reference

#4416 Update etcd to match k8s 1.28
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#4421 [4.16] disable cachito processing for ibm-cloud-controller-manager
  images/ose-ibm-cloud-controller-manager.yml
Labels: lgtm

#4436 Add release 4.15.0
  releases.yml
Labels: lgtm, approved

#4396 Enable secrets-store-csi-driver and operator and move to rhel9
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#4442 cluster-openshift-controller-manager-operator really to rhel9
  images/ose-cluster-openshift-controller-manager-operator.yml
Labels: lgtm, approved

#4445 Ignore jira components
  bug.yml
Labels: lgtm, approved

#4447 Revert "[4.16] Re-enable canonical builders for unresolved member images"
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-tests.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-baremetal-installer.yml
  images/ose-cli-artifacts.yml
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-installer-artifacts.yml
  images/ose-installer.yml
  images/ose-machine-os-images.yml
  images/ose-must-gather.yml
  images/ose-network-tools.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-microshift.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#4455 Revert "Revert "Move extra storage images to rhel9""
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/ose-csi-external-resizer.yml
  images/ose-gcp-filestore-csi-driver.yml
Labels: lgtm, approved

#4420 Switch azure-file building from csi-operator
  images/azure-file-csi-driver-operator.yml
Labels: lgtm, approved

#4456 Revert "Revert "Revert "Move extra storage images to rhel9"""
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/ose-csi-external-resizer.yml
  images/ose-gcp-filestore-csi-driver.yml
Labels: lgtm, approved

#4459 Revert "Revert "Revert "Revert "Move extra storage images to rhel9""""
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/ose-csi-external-resizer.yml
  images/ose-gcp-filestore-csi-driver.yml
Labels: lgtm, approved

#4460 [4.16] Purge alternative_upstream for images that moved to rhel9
  images/golang-github-prometheus-alertmanager.yml
  images/kube-rbac-proxy.yml
  images/ose-multus-route-override-cni.yml
Labels: lgtm, approved

#4461 [4.16] Fix csi-livenessprobe branch name
  images/csi-livenessprobe.yml
Labels: lgtm, approved

#4438 Reenable full cachito for azure-file-csi-driver
  images/azure-file-csi-driver.yml
Labels: lgtm, approved

#4464 Fix stream definition
  images/csi-livenessprobe.yml
Labels: lgtm, approved
