Repository openshift-eng/ocp-build-data, pull requests merged in 2024-08, with the labels that each got.

#5100 Add one-layer-up fix in rhcos
  releases.yml
Labels: lgtm, approved

#5153 Update CRO & VPA owners to pod autoscaling team
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
  images/vertical-pod-autoscaler-operator.yml
  images/vertical-pod-autoscaler.yml
Labels: lgtm, approved

#5168 Update machine-api provider IBM component mapping
  product.yml
Labels: lgtm, approved

#5074 ART-9391 [4.17] Update to ubi8 repos and base images
  group.yml
  streams.yml
Labels: lgtm, approved

#5073 ART-9391 [4.16] Update to ubi8 repos and base images
  group.yml
  streams.yml
Labels: lgtm, approved

#5183 Stop pinning git in ci images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5169 ART-10082: Create an own signing_advisory for 4.18
  group.yml
Labels: lgtm, approved, jira/valid-reference

#5217 excluded OCPBUGs for 4.12.62
  releases.yml
Labels: lgtm, approved

#5209 [ART-10306] [ose-frr] set for_payload as true
  images/ose-frr.yml
Labels: lgtm, approved

#5213 4.15.26: Pinning rpms that included in RHCOS
  releases.yml
Labels: do-not-merge/hold

#5219 Update monitoring-plugin builder
  images/monitoring-plugin.yml
Labels: lgtm, approved

#5226 repromote to 4.15.27
  releases.yml
Labels: lgtm

#4848 ART-7860: Use GOAMD64=v2 on rhel9 1.22 golang builder containers
  images/openshift-golang-builder.Dockerfile
Labels: lgtm, approved, jira/valid-reference

#5234 fix ci image build
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5233 ART-9391 [4.18] Update to ubi8 repos and base images
  group.yml
  streams.yml
Labels: lgtm, approved

#5236 Add OKD-only image for upi-installer
  images/okd-only-upi-installer.yml
Labels: lgtm, approved

#5237 disable dpu-operator.yml
  images/dpu-operator.yml
Labels: lgtm, approved

#5240 [4.18] remove dpu-network-operator
  images/dpu-network-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#5242 [4.16] remove dpu-network-operator
  images/dpu-network-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#5244 [4.14] remove dpu-network-operator
  images/dpu-network-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#5238 remove images/dpu-network-operator.yml
  images/dpu-network-operator.yml
Labels: lgtm, approved

#5245 [4.13] remove dpu-network-operator
  images/dpu-network-operator.yml
Labels: lgtm, approved

#5257 4.17: Enable signing for RPMs
  group.yml
Labels: lgtm, approved

#5264 disable ose-aws-efs-csi-driver-operator
  images/ose-aws-efs-csi-driver-operator.yml
Labels: lgtm, approved

#5249 upgrade pkgs to fix mismatch issue
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5263 [ART-10455] add rhel9 base and appstream repo to sync list
  group.yml
Labels: lgtm

#5265 rename haproxy dockerfile
  images/openshift-enterprise-haproxy-router.yml
  images/ose-haproxy-router-base.yml
Labels: do-not-merge/hold, approved

#5267 [4.18] re-enable dpu-operator
  images/dpu-operator.yml
Labels: lgtm, approved

#5270 fetch right go version for cachito
  images/monitoring-plugin.yml
Labels: lgtm, approved

#5231 [ART-10298] pf-status-relay image add
  images/pf-status-relay.yml
Labels: lgtm, approved

#5194 ART-10051: update RHCOS to 4.18
  group.yml
Labels: lgtm, approved, jira/valid-reference

#5232 CFE-1111: [openshift-4.17] Update Dockerfile and repo location for ansible-operator-plugins
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5277 [4.17] disable canonical builders
  group.yml
Labels: lgtm, approved

#5187 4.17: Stop pinning git in ci images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5188 Backport build root image rpm addition
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5268 [4.17] re-enable dpu-operator
  images/dpu-operator.yml
Labels: lgtm, approved

#5282 Preserve ironic OKD dockerfiles
  images/ironic-agent.yml
  images/ironic.yml
Labels: lgtm

#5182 Update etcd to match k8s 1.31
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5288 exclude bug for 4.15.29
  releases.yml
Labels: lgtm, approved

#5291 [fix] include ose-aws-efs-csi-driver-operator as dependency for ose-tools
  images/ose-tools.yml
Labels: lgtm, approved

#5292 [fix] include sriov-network-operator as dependency for kube-rbac-proxy
  images/kube-rbac-proxy.yml
Labels: lgtm, approved

#5294 include ironic related bugs
  releases.yml
Labels: lgtm

#5299 [4.16] remove unused openshift-base-nodejs.rhel8
  images/openshift-base-nodejs.yml
Labels: lgtm, approved

#5303 Revert #5294, #5297 and #5298
  releases.yml
Labels: lgtm, approved

#5306 OKD-224: okd alignment for marketplace and samples operator
  images/marketplace-operator.yml
  images/ose-cluster-samples-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5312 4.16: Disable "previous" ci golang builders
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
Labels: lgtm, approved

#5313 Pin imagbuilder to 1.2.14 for go1.20-
  ci_transforms/rhel-7/ci-build-root/Dockerfile
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5316 PODAUTO-225: Fix bundle and manifest directories for vertical-pod-autoscaler-operator
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5323 [4.15.30] pin python-werkzeug dependency
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#5325 oc-mirror: go.work without vendor/
  images/oc-mirror-plugin.yml
Labels: lgtm, approved

#5330 Disable helm and operator-sdk images
  images/openshift-enterprise-helm-operator.yml
  images/openshift-enterprise-operator-sdk.yml
Labels: lgtm, approved

#5332 Revert "<temp> freeze 4.18 automation"
  group.yml
Labels: lgtm
