Repository openshift-eng/ocp-build-data, pull requests merged in 2024-12, with the labels that each got.

#5768 Add upstream_images for builder images
  group.yml
  images/ose-cluster-config-api.yml
  streams.yml
Labels: lgtm, approved

#5780 Ignore stop-ship-tag for non-GA release
  group.yml
Labels: lgtm, approved

#5773 Move 4.13 advisories to silent release
  erratatool.yml
Labels: lgtm, approved

#5762 Solidify repositories for rhel9 golang builder
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#5764 Solidify rhel9 go1.22 repositories
  group.yml
  images/openshift-golang-builder.yml
Labels: lgtm, approved

#5786 pin python-waitress-3.0.1-1.el9
  releases.yml
Labels: lgtm, approved

#5787 [4.19] remove -previous ci-images
  group.yml
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
Labels: lgtm, approved

#5789 [4.17] remove -previous ci images
  group.yml
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.yml
  images/ci-openshift-golang-builder-previous.rhel9.yml
Labels: lgtm, approved

#5788 [4.18] remove -previous ci images
  group.yml
  images/ci-openshift-build-root-previous.rhel8.disabled
  images/ci-openshift-build-root-previous.rhel9.disabled
  images/ci-openshift-golang-builder-previous.rhel8.disabled
  images/ci-openshift-golang-builder-previous.rhel9.disabled
Labels: lgtm, approved

#5798 [konflux] use VM with higher disk for ose-installer-artifacts
  images/ose-installer-artifacts.yml
Labels: lgtm, approved

#5800 ART-11563: [konflux] disable ose-installer-artifacts until issue is resolved
  images/ose-installer-artifacts.yml
Labels: jira/valid-reference

#5771 Add pf-status-relay-operator
  images/pf-status-relay-operator.yml
  images/pf-status-relay.yml
Labels: lgtm, approved

#5794 OCPCLOUD-2642: ASO should use commit prefix
  images/ose-azure-service-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5783 add germanparente git user to owners for 4.13
  OWNERS
Labels: lgtm, approved

#5809 update ci build root to member
  images/pf-status-relay-operator.yml
Labels: lgtm, approved

#5811 [4.17] [konflux] override params
  images/monitoring-plugin.yml
  images/networking-console-plugin.yml
  images/nmstate-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-console.yml
  images/ose-cli-artifacts.yml
  images/ose-etcd.yml
  images/ose-installer-artifacts.yml
Labels: lgtm, approved

#5812 [konflux] use openshift-priv for openshift-eng
  group.yml
  images/ci-openshift-base.rhel8.yml
  images/ci-openshift-base.rhel9.yml
  images/ci-openshift-build-root-extra.rhel9.disabled
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-golang-builder-extra.rhel9.disabled
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/openshift-base-nodejs.rhel9.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
Labels: lgtm, approved

#5813 ART-11251: [konflux] 4.17 remove vendor override
  images/atomic-openshift-cluster-autoscaler.yml
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/container-networking-plugins-microshift.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/csi-provisioner.yml
  images/golang-github-openshift-oauth-proxy.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/kube-rbac-proxy.yml
  images/kube-state-metrics.yml
  images/multus-cni-container-microshift.yml
  images/multus-cni.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/operator-lifecycle-manager.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-haproxy-router-base.yml
  images/ose-installer-etcd-artifacts.yml
  images/ose-installer-kube-apiserver-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-olm-operator-controller.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5817 ART-11578: [konflux] disable VPA cause of git tag issue
  images/vertical-pod-autoscaler-operator.yml
Labels: jira/valid-reference

#5814 add pf-status-relay-operator
  images/pf-status-relay-operator.yml
  images/pf-status-relay.yml
Labels: lgtm, approved

#5835 use 4.19 rhocs
  group.yml
Labels: lgtm, approved

#5836 permit-conflicting-group-rpm-4.19.ec0
  releases.yml
Labels: lgtm, approved

#5822 create 4.19 9.6 repos for CI
  group.yml
Labels: lgtm, approved

#5818 Set component for multus-cni to Networking
  product.yml
Labels: lgtm, approved

#5808 ci images: Install certificate when using repos from vpn
  ci_images/dnf_wrapper.sh
Labels: lgtm, approved

#5843 Use shipped nodejs image
  streams.yml
Labels: lgtm, approved

#5842 Switch to released node image
  streams.yml
Labels: lgtm, approved

#5854 Revert "use 4.19 rhocs"
  group.yml
Labels: lgtm, approved

#5763 Get rhel8 golang 1.22 builder to rhel8.10
  group.yml
  images/openshift-golang-builder.yml
  streams.yml
Labels: lgtm

#5855 [4.18] disabe pf-status-relay-operator
  images/pf-status-relay-operator.yml
Labels: lgtm

#5866 Revert "scan-sources:noop [konflux] disable ose-installer-etcd-artifacts"
  images/ose-installer-etcd-artifacts.yml
Labels: lgtm, approved

#5863 Revert "[4.18] disabe pf-status-relay-operator"
  images/pf-status-relay-operator.yml
Labels: lgtm, approved

#5844 libreswan: No reason for rebuild
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#5904 added dependency to libreswan
  releases.yml
Labels: lgtm, approved

#5905 added dependency to libreswan
  releases.yml
Labels: lgtm, approved

#5918 added missing repo to enabled_repos
  images/ci-openshift-base.rhel9.yml
Labels: lgtm, approved

#5897 Re-enable cluster-resource-override-operator build for 4.19
  images/clusterresourceoverride-operator.yml
Labels: lgtm, approved
