Repository openshift-eng/ocp-build-data, pull requests merged in 2024-07, with the labels that each got.

#5029 4.11: Allow kernel inconsistencies dtk/rhcos
  releases.yml
Labels: lgtm, approved

#5021 [ART-9503] [4.17] replace repo URLs with the new ocp-artifacts host
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  group.yml
  images/monitoring-plugin.yml
  images/networking-console-plugin.yml
  images/nmstate-console-plugin.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5030 OSDOCS-11155: updates solution text to 4.16 for MicroShift
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#5027 ART-9441 add ose-operator-framework-tools.yml
  images/ose-operator-framework-tools.yml
Labels: lgtm, approved, tide/merge-method-squash

#5002 [ART-9923] set dockerfile_fallback
  images/ose-azure-workload-identity-webhook.yml
Labels: lgtm, approved, tide/merge-method-squash

#5032 embargoed ose repo for console
  images/openshift-base-nodejs.yml
Labels: lgtm, approved

#5034 [4.17] [ART-10029] bump golang to 1.22.4-2
  streams.yml
Labels: lgtm, approved

#5040 ART-9928 Update 1.22 rhel8 builders
  streams.yml
Labels: lgtm, approved

#5042 4.17: Own signing advisory
  group.yml
Labels: lgtm, approved

#5043 Fix 4.17 rebase operator-framework-tools
  images/ose-operator-framework-tools.yml
Labels: lgtm, approved

#5044 4.13: Own signing advisory
  group.yml
Labels: lgtm, approved

#5045 4.14: Own signing advisory
  group.yml
Labels: lgtm, approved

#5047 4.16: Own signing advisory
  group.yml
Labels: lgtm, approved

#4913 STOR-1856: move AWS EFS operator to csi-operator repo
  images/ose-aws-efs-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5050 ART-9503 [4.13] update plashets URL
  group.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5060 [4.17] use must-gather as base for LSO and secrets-store-csi mustgather
  images/local-storage-mustgather.yml
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#5062 Improve DNF wrapper behavior and output
  ci_images/dnf_wrapper.sh
  ci_images/dnf_wrapper_test.Dockerfile
Labels: lgtm, approved

#5048 ART-9503 [4.15] update plashets URL
  group.yml
  images/monitoring-plugin.yml
  images/nmstate-console-plugin.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5049 ART-9503 [4.14] update plashets URL
  group.yml
  images/monitoring-plugin.yml
  images/nmstate-console-plugin.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5051 ART-9503 [4.12] update plashets URL
  group.yml
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#5052 ART-9990 4.17 to 9.4
  group.yml
  images/driver-toolkit.yml
  streams.yml
Labels: lgtm, approved

#5069 [4.17] baremetal-cluster-api-controllers not for payload
  images/ose-baremetal-cluster-api-controllers.yml
Labels: lgtm, approved

#5072 Allow default behavior overrides from dnf wrapper callers
  ci_images/dnf_wrapper.sh
Labels: lgtm, approved

#5076 Stop 4.12 automation
  group.yml
Labels: lgtm, approved

#5078 Fix GOPROXY URL
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5075 Revert "Stop building and shipping sriov-operator until backport of OCPBUGS-3…"
  images/sriov-network-operator.yml
Labels: lgtm, approved

#5079 Update goproxy url
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5080 Update goproxy url
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5081 [4.17] Remove the -k curl option from ci images Dockerfiles
  ci_images/install_etcd.sh
  ci_images/install_protoc.sh
Labels: lgtm, approved

#5089 Make rteval available to tests image
  group.yml
Labels: lgtm, approved

#5090 exclude bug
  releases.yml
Labels: lgtm, do-not-merge/hold, approved

#4937 4.12: Stop building ingress-node-firewall-operator
  images/ingress-node-firewall-daemon.yml
  images/ingress-node-firewall-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm

#4938 4.12: Disable abandoned dpu-operator
  images/dpu-network-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm

#5098 Revert "Stop 4.12 automation"
  group.yml
Labels: lgtm, approved

#5099 ART-10042: created new branch for openshift-4.18
  bug.yml
  erratatool.yml
  group.yml
  releases.yml
Labels: lgtm, approved, jira/valid-reference

#5102 add hotfix art10187
  releases.yml
Labels: lgtm, tide/merge-method-squash

#5104 remove fallbacks
  images/coredns.yml
  images/csi-attacher.yml
  images/csi-livenessprobe.yml
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-enterprise-registry.yml
  images/ose-aws-pod-identity-webhook.yml
  images/ose-cluster-config-api.yml
  images/ose-cluster-config-operator.yml
  images/ose-cluster-csi-snapshot-controller-operator.yml
  images/ose-cluster-kube-apiserver-operator.yml
  images/ose-cluster-kube-controller-manager-operator.yml
  images/ose-cluster-kube-scheduler-operator.yml
  images/ose-must-gather.yml
  images/ose-oauth-apiserver.yml
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved

#5115 pin skopeo version
  releases.yml
Labels: lgtm, approved

#5116 fixed skopeo pin
  releases.yml
Labels: lgtm, approved

#5122 Freeze 4.18 automation
  group.yml
Labels: lgtm, approved

#5126 update 4.16.4 excludes
  releases.yml
Labels: lgtm, approved

#5130 Fix 4.12.61 operator refs
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5133 fix aarch refs
  releases.yml
Labels: tide/merge-method-squash

#5129 ART-9932: 4.12: Only x86_64 s390x
  group.yml
  images/azure-file-csi-driver-operator.yml
  images/azure-file-csi-driver.yml
  images/cloud-event-proxy.yml
  images/csi-driver-manila-operator.yml
  images/csi-driver-manila.yml
  images/csi-driver-nfs.yml
  images/dpu-network-operator.yml
  images/ib-sriov-cni.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/linuxptp-daemon.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-aws-ebs-csi-driver-operator.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-aws-efs-utils.yml
  images/ose-aws-pod-identity-webhook.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-azure-disk-csi-driver-operator.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-gcp-cloud-controller-manager.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-machine-os-images.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver.yml
  images/ose-powervs-cloud-controller-manager.yml
  images/ose-powervs-machine-controllers.yml
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#5067 ci-build-root: Add more packages
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#5135 image-registry update dockerfile name
  images/openshift-enterprise-registry.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5138 Also pin el8 podman in 4.15.23
  releases.yml
Labels: lgtm, approved

#5139 4.16.4 - Pin bug that was missed in bug sweep
  releases.yml
Labels: lgtm, approved

#5120 STOR-1856: remove cachito legacy manifest dir for aws efs
  images/ose-aws-efs-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5141 ART-9932: Disable multi payloads
  group.yml
Labels: lgtm, approved, jira/valid-reference

#5028 ART-9441 add ose-operator-framework-tools.yml
  images/ose-operator-framework-tools.yml
Labels: lgtm, approved, tide/merge-method-squash

#5144 Explicitly define branch for openshift4-aws-iso rpm
  rpms/openshift4-aws-iso.yml
Labels: lgtm, approved

#5145 Repromote
  group.yml
  images/azure-file-csi-driver-operator.yml
  images/azure-file-csi-driver.yml
  images/cloud-event-proxy.yml
  images/csi-driver-manila-operator.yml
  images/csi-driver-manila.yml
  images/csi-driver-nfs.yml
  images/dpu-network-operator.yml
  images/ib-sriov-cni.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic-static-ip-manager.yml
  images/ironic.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/linuxptp-daemon.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-aws-ebs-csi-driver-operator.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-aws-efs-utils.yml
  images/ose-aws-pod-identity-webhook.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-azure-disk-csi-driver-operator.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-gcp-cloud-controller-manager.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-machine-os-images.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver.yml
  images/ose-powervs-cloud-controller-manager.yml
  images/ose-powervs-machine-controllers.yml
  images/ptp-operator-must-gather.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  images/sriov-dp-admission-controller.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-device-plugin.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: do-not-merge/hold

#4948 Add Luis to OWNERS
  OWNERS
Labels: lgtm, approved

#5101 Declare containernetworking-plugins fixed in rhcos
  releases.yml
Labels: lgtm, approved

#5095 ART-10105: added new image
  product.yml
Labels: lgtm, approved, jira/valid-reference

#5094 ART-10105: added new image ose-sriov-rdma-cni
  images/ose-sriov-rdma-cni.yml
Labels: lgtm, approved, jira/valid-reference

#5161 Revert "[4.17] baremetal-cluster-api-controllers not for payload"
  images/ose-baremetal-cluster-api-controllers.yml
Labels: lgtm, approved

#5164 4.14: added missing kernel-rt
  group.yml
Labels: lgtm, approved

#5165 4.13: added missing kernel-rt
  group.yml
Labels: lgtm, approved

#5166 4.15: added missing kernel-rt
  group.yml
Labels: lgtm, approved

#5167 ART-10301: remove Rukpak image
  images/ose-olm-rukpak.yml
Labels: lgtm, approved, jira/valid-reference
