Repository openshift-eng/ocp-build-data, pull requests merged in 2024-10, with the labels that each got.

#5442 4.17: Etcd to go1.22
  images/ose-etcd.yml
  images/ose-installer-etcd-artifacts.yml
  streams.yml
Labels: lgtm, approved

#5447 support CI builds in Konflux
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
Labels: lgtm

#5426 STOR-1873: update OLM manifests to use stable channel
  images/ose-secrets-store-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5456 Revert "Include OCPBUGS-38513"
  releases.yml
Labels: lgtm, approved

#5460 microshift-rebase: to go1.22
  modifications/Dockerfile
Labels: lgtm, approved

#5462 Use ci image for microshift-rebase
  modifications/Dockerfile
Labels: lgtm, approved

#5458 4.17 ansible operator
  group.yml
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved

#5465 monitoring-plugin: Move to npm
  images/monitoring-plugin.yml
Labels: lgtm, approved

#5345 ART-10430 Onboard microshift bootc images for konflux build
  group.yml
  images/microshift-bootc.yml
  streams.yml
Labels: do-not-merge/hold, approved, tide/merge-method-squash

#5472 pin cri-o version of rhcos
  releases.yml
Labels: lgtm

#5474 dependencies to python-webob
  releases.yml
Labels: lgtm, approved

#5475 handle bugs for 4.16.17
  releases.yml
Labels: lgtm, approved

#5477 Add crb to ironic to make wheel available
  images/ironic.yml
Labels: lgtm, approved

#5481 [chore] disable few operators with wrong metadata.{name,version}
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-metallb-operator.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#5480 use priv repo for cloud-event-proxy
  images/cloud-event-proxy.yml
Labels: lgtm, approved, tide/merge-method-squash

#5487 [rhel-8-golang-1.22] bump MINOR to 4.18
  group.yml
Labels: lgtm

#5488 [rhel-9-golang-1.22] bump MINOR to 4.18
  group.yml
Labels: lgtm

#5493 Cleanup unused repos
  group.yml
Labels: lgtm, approved

#5494 ART-10789: Remove LVMS image in microshift rebase
  rpms/microshift.yml
Labels: lgtm, approved, jira/valid-reference

#5495 crb for ironic-agent
  images/ironic-agent.yml
Labels: lgtm, approved

#5501 Update etcd to match Kubernetes 1.30.5
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5499 ART-10787: add gcp-workload-identity-federation-webhook
  images/gcp-workload-identity-federation-webhook.yml
Labels: lgtm, approved, jira/valid-reference

#5504 microshift: Fix rebase error
  modifications/microshift-rebase
Labels: lgtm

#5509 Enable mirror true
  streams.yml
Labels: lgtm, approved

#5513 Fix ci golang buildroot build
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5514 Fix ci golang buildroot build
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5525 ART-9905 [openshift-4.18] Publish golang builders for partner access
  streams.yml
Labels: lgtm, approved

#5526 STOR-1844: update OLM manifests to use stable channel
  images/ose-smb-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5543 4.17.2 Include fixed golang trackers
  releases.yml
Labels: lgtm, approved

#5542 4.16.18: Add golang trackers
  releases.yml
Labels: lgtm, approved

#5510 CLID-252: renaming oc-mirror component
  product.yml
Labels: lgtm, approved, jira/valid-reference

#5546 [4.16] stop pinning git in CI images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5548 Update etcd to match Kubernetes 1.30.5
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#5551 remove non_shipping field for thanos
  images/thanos.yml
Labels: lgtm, approved

#5554 base-nodejs: Exempt nodejs packages from update check
  images/openshift-base-nodejs.rhel9.yml
Labels: lgtm, approved

#5555 base-nodejs: Exempt nodejs packages from update check
  images/openshift-base-nodejs.yml
Labels: lgtm, approved

#5559 Update Cloud Compute components
  product.yml
Labels: lgtm, approved

#5547 Bump golang-1.22 builder to RHEL 9.4
  group.yml
  streams.yml
Labels: lgtm, approved

#5561 scan-sources:noop 4.18: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/container-networking-plugins-microshift.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic.yml
  images/multus-cni.yml
  images/openshift-base-nodejs.rhel9.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/operator-lifecycle-manager.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-frr.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-haproxy-router-base.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-operator-controller.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-route-controller-manager.yml
  images/ose-sriov-rdma-cni.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
Labels: lgtm, approved

#5459 ART-10785: parameter for new release versioning scheme
  group.yml
Labels: lgtm, approved, jira/valid-reference

#5449 STOR-1823, ART-10892: Remove shared-resource CSI driver and operator
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-csi-driver-shared-resource-webhook.yml
  images/ose-csi-driver-shared-resource.yml
Labels: lgtm, approved, jira/valid-reference

#5565 scan-sources:noop 4.17: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/container-networking-plugins-microshift.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic.yml
  images/multus-cni.yml
  images/openshift-base-nodejs.rhel9.yml
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/operator-lifecycle-manager.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-frr.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-haproxy-router-base.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-operator-controller.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-route-controller-manager.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5564 scan-sources:noop disable konflux images
  images/monitoring-plugin.yml
  images/networking-console-plugin.yml
  images/nmstate-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-console.yml
  images/ose-alibaba-machine-controllers.yml
  images/ose-baremetal-installer.yml
  images/ose-etcd.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-etcd-artifacts.yml
  images/ose-installer.yml
  images/ose-machine-os-images.yml
Labels: lgtm, do-not-merge/hold, tide/merge-method-squash

#5567 scan-sources:noop 4.15: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic.yml
  images/multus-cni.yml
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/operator-lifecycle-manager.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-frr.yml
  images/ose-haproxy-router-base.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-rukpak.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5521 ART-10787 add gcp-workload-identity-federation-webhook.yml
  images/gcp-workload-identity-federation-webhook.yml
Labels: lgtm, approved

#5574 Remove cluster-platform-operators-manager
  images/ose-cluster-platform-operators-manager.yml
Labels: lgtm, approved

#5581 Fix config to make validator happy
  images/egress-router-cni.yml
  images/multus-cni.yml
  images/ose-containernetworking-plugins.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
Labels: lgtm, approved

#5568 scan-sources:noop 4.14: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/ironic-agent.yml
  images/ironic-rhcos-downloader.yml
  images/ironic.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/multus-cni.yml
  images/openshift-base-nodejs.yml
  images/openshift-base-rhel8.yml
  images/openshift-enterprise-ansible-operator.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/operator-lifecycle-manager.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-azure-workload-identity-webhook.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-frr.yml
  images/ose-haproxy-router-base.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-rukpak.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-secrets-store-csi-mustgather.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5569 scan-sources:noop 4.13: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/configmap-reload.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/multus-cni.yml
  images/openshift-base-rhel8.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/operator-lifecycle-manager.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-haproxy-router-base.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-rukpak.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5570 scan-sources:noop 4.12: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/cluster-node-tuning-operator.yml
  images/configmap-reload.yml
  images/driver-toolkit.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/multus-cni.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-operator-sdk.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-service-idler.yml
  images/openshift-enterprise-tests.yml
  images/operator-lifecycle-manager.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-cluster-platform-operators-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-haproxy-router-base.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-olm-rukpak.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5571 scan-sources:noop 4.11: Remove non_shipping_repos
  images/cluster-monitoring-operator.yml
  images/cluster-node-tuning-operator.yml
  images/configmap-reload.yml
  images/driver-toolkit.yml
  images/golang-github-prometheus-alertmanager.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/grafana.yml
  images/kuryr-cni.yml
  images/kuryr-controller.yml
  images/multus-cni.yml
  images/openshift-enterprise-base.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-cli.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/openshift-enterprise-deployer.yml
  images/openshift-enterprise-egress-router.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/openshift-enterprise-operator-sdk.yml
  images/openshift-enterprise-pod.yml
  images/openshift-enterprise-registry.yml
  images/openshift-enterprise-tests.yml
  images/operator-lifecycle-manager.yml
  images/ose-agent-installer-api-server.yml
  images/ose-aws-cloud-controller-manager.yml
  images/ose-azure-cloud-controller-manager.yml
  images/ose-azure-cloud-node-manager.yml
  images/ose-egress-http-proxy.yml
  images/ose-etcd.yml
  images/ose-frr.yml
  images/ose-haproxy-router-base.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-ovn-kubernetes.yml
  images/ose-tools.yml
  images/prom-label-proxy.yml
  images/prometheus-config-reloader.yml
  images/prometheus-operator.yml
  images/thanos.yml
Labels: lgtm, approved

#5580 4.18: Cleanup of artifacts
  group.yml
  images/ci-openshift-base.rhel8.yml
  images/ci-openshift-build-root-extra.rhel9.disabled
  images/ci-openshift-build-root-previous.rhel8.disabled
  images/ci-openshift-build-root-previous.rhel9.disabled
  images/ci-openshift-golang-builder-extra.rhel9.disabled
  images/ci-openshift-golang-builder-previous.rhel8.disabled
  images/ci-openshift-golang-builder-previous.rhel9.disabled
  images/openshift-base-rhel8.yml
  images/openshift-enterprise-base.yml
  streams.yml
Labels: lgtm, approved

#5584 ART-10787 disable gcp-workload-identity-federation-webhook.yml
  images/gcp-workload-identity-federation-webhook.yml
Labels: lgtm, approved

#5586 ART-10998: [4.18.0-ec.3] disable failing operators
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5587 [konflux] different dockerfile for konflux
  images/ose-installer-etcd-artifacts.yml
Labels: lgtm, approved

#5590 Fix multi ci golang image builds
  group.yml
Labels: lgtm, approved

#5601 bug.yml: Drop unused component
  bug.yml
Labels: lgtm, approved

#5607 scan-sources:noop use priv org for ocp-build-data
  group.yml
  images/ci-openshift-base.rhel9.yml
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
  images/ci-openshift-build-root-previous.rhel8.disabled
  images/ci-openshift-build-root-previous.rhel9.disabled
  images/ci-openshift-golang-builder-latest.rhel8.yml
  images/ci-openshift-golang-builder-latest.rhel9.yml
  images/ci-openshift-golang-builder-previous.rhel8.disabled
  images/ci-openshift-golang-builder-previous.rhel9.disabled
  images/openshift-base-nodejs.rhel9.yml
  images/openshift-base-rhel9.yml
Labels: lgtm, approved
