Repository openshift-eng/ocp-build-data, pull requests merged in 2024-01, with the labels that each got.

#4130 4.14.8 Permit INVALID_ERRATA_STATUS during promotion
  releases.yml
Labels: lgtm, approved

#4131 Permit ATTACHED_BUGS
  releases.yml
Labels: lgtm, approved

#4133 4.11.56: Pin conmon version for ose-agent-installer-node-agent
  releases.yml
Labels: lgtm

#4134 [scan-osh] activate for 4.16
  group.yml
Labels: lgtm, approved

#4135 permit CONFLICTING_INHERITED_DEPENDENCY for 4.11.56
  releases.yml
Labels: lgtm

#3890 OCPNODE-1887: Bump etcd version in accordance with k8s-v1.29
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#4144 [scan-osh] activate for 4.14
  group.yml
Labels: lgtm, approved

#4145 haproxy-router: Name to rhel9
  images/openshift-enterprise-haproxy-router.yml
Labels: lgtm, approved

#4152 [group.yml] remove operator index mode
  group.yml
Labels: lgtm, approved

#4147 ART-8476 Move ose-libvirt-machine-controllers to rhel9
  images/ose-libvirt-machine-controllers.yml
Labels: lgtm, approved

#4157 installer-terraform-providers: Leave promotion in CI to CI
  images/ose-installer-terraform-providers.yml
Labels: lgtm, approved

#4161 [scan-osh] enable for 4.13
  group.yml
Labels: lgtm, approved

#4160 Add missing labels to baremetalc-luster-api-provider
  images/ose-baremetal-cluster-api-controllers.yml
Labels: lgtm, approved

#4162 Add upgrade edges
  releases.yml
Labels: lgtm

#4164 [scan-osh] activate for 4.12
  group.yml
Labels: lgtm, approved

#4166 prepare prerelease for ec.1
  releases.yml
Labels: lgtm

#4170 RPM add ose-aws-ecr-image-credential-provider
  rpms/ose-aws-ecr-image-credential-provider.yml
Labels: lgtm, approved

#4171 [ART-8310] Remove atomic-openshift-node-problem-detector from 4.14
  bug.yml
  images/atomic-openshift-node-problem-detector.yml
Labels: lgtm, approved

#4148 STOR-1713: Move azure disk operator to csi-operator repo
  images/ose-azure-disk-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#4191 Update ose-aws-ecr-image-credential-provider path to priv
  rpms/ose-aws-ecr-image-credential-provider.yml
Labels: lgtm, approved

#4194 add prerelease -1
  releases.yml
Labels: lgtm

#4199 olm: base image fixes
  images/operator-lifecycle-manager.yml
Labels: lgtm, approved

#4099 Revert "revert ART-8419 Introduce installer-terraform-providers base …
  images/ose-baremetal-installer.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-installer.yml
Labels: lgtm, approved

#4198 bump ose-azure-disk-csi-driver-operator to rhel-9 images
  images/ose-azure-disk-csi-driver-operator.yml
Labels: lgtm, approved

#4203 Enable automation for ci golang-builders
  images/ci-openshift-golang-builder-extra.yml
  images/ci-openshift-golang-builder-latest.yml
  images/ci-openshift-golang-builder-previous.yml
Labels: lgtm, approved

#4205 Add assembly for ART-8712
  releases.yml
Labels: lgtm

#4212 exclude bugs for 4.14.10
  releases.yml
Labels: lgtm, approved

#4213 exclude bugs for 4.13.30
  releases.yml
Labels: lgtm, approved

#4215 4.14 - Remove old rhcos permit
  releases.yml
Labels: lgtm, approved

#4214 4.15 - Set prerelease advisory release back to rhose async auto
  erratatool.yml
Labels: lgtm, approved

#4206 ART-8530 Use RHEL 9.4 in 4.16
  group.yml
  images/driver-toolkit.yml
  releases.yml
Labels: lgtm

#4224 Add 4.15 z target release
  bug.yml
Labels: lgtm, approved

#4230 Add krb5-devel to RHEL9 golang 1.21 image
  images/openshift-golang-builder.Dockerfile
Labels: lgtm

#4233 RPM add ose-aws-ecr-image-credential-provider
  rpms/ose-aws-ecr-image-credential-provider.yml
Labels: lgtm, approved

#4236 Migrate ocp-build-data-validator to art-tools
  .github/workflows/validate.yaml
Labels: lgtm, approved

#4245 Mapping for openshift-kubernetes-nmstate-handler-rhel-9-container
  product.yml
Labels: lgtm, approved

#4246 Images to rhel9
  images/atomic-openshift-cluster-autoscaler.yml
  images/cluster-etcd-operator.yml
  images/coredns.yml
  images/ose-apiserver-network-proxy.yml
  images/ose-cluster-dns-operator.yml
  images/ose-cluster-kube-apiserver-operator.yml
  images/ose-cluster-kube-storage-version-migrator-operator.yml
  images/ose-kube-storage-version-migrator.yml
  images/ose-openshift-apiserver.yml
  images/ose-ovn-kubernetes.yml
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#4238 Disable cachito accounting
  images/azure-file-csi-driver-operator.yml
  images/cluster-storage-operator.yml
  images/cluster-version-operator.yml
  images/csi-driver-manila-operator.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-cluster-autoscaler-operator.yml
  images/ose-cluster-cloud-controller-manager-operator.yml
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-cluster-csi-snapshot-controller-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/vsphere-problem-detector.yml
Labels: lgtm, approved

#4237 [4.16] Define alternative config
  images/baremetal-runtimecfg.yml
Labels: lgtm, approved

#4267 ose-sdn: move to rhel 9
  images/ose-sdn.yml
Labels: lgtm, approved

#4280 libssh
  releases.yml
Labels: lgtm, approved

#4276 [ART-8358][4.16] alignment for multi-builder migration to rhel9
  images/egress-router-cni.yml
  images/multus-cni.yml
  images/ose-containernetworking-plugins.yml
  images/ose-machine-config-operator.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
  images/ose-network-interface-bond-cni.yml
Labels: approved

#4296 [4.16] Fix alternative config payload name for machine-config-operator
  images/ose-machine-config-operator.yml
Labels: lgtm, approved

#4286 [4.16] enable canonical builders for images that switched to rhel9
  images/cluster-network-operator.yml
  images/hypershift.yml
  images/ose-cluster-ingress-operator.yml
  images/ose-cluster-kube-cluster-api-operator.yml
  images/ose-cluster-openshift-apiserver-operator.yml
Labels: lgtm, approved

#4295 No pkg-managers to deal with STONEBLD-1973
  images/azure-file-csi-driver-operator.yml
  images/cluster-storage-operator.yml
  images/cluster-version-operator.yml
  images/csi-driver-manila-operator.yml
  images/local-storage-diskmaker.yml
  images/local-storage-mustgather.yml
  images/local-storage-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-cluster-autoscaler-operator.yml
  images/ose-cluster-cloud-controller-manager-operator.yml
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-cluster-csi-snapshot-controller-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-ibm-cloud-controller-manager.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-operator.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/vsphere-problem-detector.yml
Labels: lgtm, approved

#4305 temp cachito tweak for ose-machine-api-provider-gcp
  images/ose-machine-api-provider-gcp.yml
Labels: lgtm, approved

#4303 Add rhel-9-golang stream for oc 4.15
  images/ose-cli-artifacts.yml
Labels: lgtm, approved

#4308 hotfix ovn
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#4309 another hotfix
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#4304 METAL-832: Move image-customization-controller to RHEL-9
  images/ose-image-customization-controller.yml
Labels: lgtm, approved, jira/valid-reference

#4313 Freeze automation temporarily
  group.yml
Labels: lgtm
