Repository openshift-eng/ocp-build-data, pull requests merged in 2024-09, with the labels that each got.

#5307 [chore] add initial work for new image kube-compare-artifacts-container
  images/kube-compare-artifacts.yml
Labels: lgtm, approved

#5336 Revert "[chore] add initial work for new image kube-compare-artifacts-container"
  images/kube-compare-artifacts.yml
Labels: lgtm, approved

#5337 [chore] add kube-compare-artifacts to product listing
  product.yml
Labels: lgtm, approved

#5340 rename sriov Dockerfiles
  images/sriov-network-config-daemon.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved

#5350 Fixing SR-IOV component mapping
  product.yml
Labels: lgtm, approved

#5356 Stricter build-sync for 4.17
  releases.yml
Labels: lgtm, approved

#5360 [4.18] reenable helm images
  images/openshift-enterprise-helm-operator.yml
  images/openshift-enterprise-operator-sdk.yml
Labels: lgtm, approved

#5362 4.17: Update PRs against openshift/azure-storage-azcopy
  images/ose-azure-storage-azcopy-base.yml
Labels: lgtm, approved

#5361 4.18: Update PRs against openshift/azure-storage-azcopy
  images/ose-azure-storage-azcopy-base.yml
Labels: lgtm, approved

#5366 exlude OCPBUGS-37828 for 4.15.32
  releases.yml
Labels: lgtm, approved

#5367 4.16.12: fix assembly
  releases.yml
Labels: lgtm, approved

#5375 pinned openshift-kubelet
  releases.yml
Labels: lgtm, approved

#5376 Prepare 4.16.13
  releases.yml
Labels: lgtm, approved

#5377 Prepare 4.15.33
  releases.yml
Labels: lgtm, approved

#5378 Prepare 4.14.37
  releases.yml
Labels: lgtm, approved

#5379 Prepare 4.13.50
  releases.yml
Labels: lgtm, approved

#5380 Unpin previous microshift
  releases.yml
Labels: lgtm, approved

#5392 3.11 to new plashet host
  group.yml
Labels: lgtm, approved

#5372 Revert "Freeze 4.12 automation"
  group.yml
Labels: lgtm, approved

#5371 pin go tools with previous version to match golang version
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
Labels: lgtm, approved

#5355 Add component mappings
  product.yml
Labels: lgtm, approved, tide/merge-method-squash

#5410 Create 4.17.0-rc.4
  releases.yml
Labels: lgtm, approved

#5415 4.17-rc.5
  releases.yml
Labels: lgtm, approved

#5400 Fix 3.11 repos
  group.yml
Labels: lgtm, approved

#5418 [chore] update RHCOS for arm
  releases.yml
Labels: approved

#5419 Add permits for 4.18.0-ec.1 assembly
  releases.yml
Labels: lgtm, approved

#5402 OSASINFRA-3609: Move OpenStack Cinder CSI Driver Operator to csi-operator repo
  images/ose-openstack-cinder-csi-driver-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5407 [ART-10674] [4.16] bump rhel9 stream to rhel-els-container-9.4
  streams.yml
Labels: lgtm, approved

#5409 [4.16] bump rhel9 repos to 9.4
  group.yml
  images/driver-toolkit.yml
Labels: lgtm, approved

#5421 Do not trigger rebuilds when node or npm has an update
  group.yml
Labels: lgtm, approved

#5309 [4.7] disable cachito for machine-config-operator
  images/ose-machine-config-operator.yml
Labels: lgtm, approved

#5427 Revert "[openshift-4.16] pin go tools with previous version to match golang version"
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
  images/ci-openshift-build-root-previous.rhel8.yml
  images/ci-openshift-build-root-previous.rhel9.yml
Labels: lgtm, approved

#5429 add rc.6
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#5359 CFE-1125: Add pip integration for ansible-operator
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#5435 4.15.35: force-include python-webob
  releases.yml
Labels: lgtm, approved

#5436 4.14.38: force-include python-webob
  releases.yml
Labels: lgtm, approved

#5441 etcd to golang-1.22
  images/ose-etcd.yml
  images/ose-installer-etcd-artifacts.yml
  streams.yml
Labels: lgtm, approved

#5403 OSASINFRA-3610: OpenStack: ship manila CSI operator from csi-operator
  images/csi-driver-manila-operator.yml
Labels: lgtm, approved, jira/valid-reference

#5437 marketplace-operator: Move to openshift-priv
  group.yml
  images/marketplace-operator.yml
Labels: lgtm, approved

#5430 Be strict about rhaos rpms assembly issues
  group.yml
Labels: lgtm

#5443 Transition 4.17 to GA config
  bug.yml
  group.yml
Labels: lgtm, approved
