Repository openshift-eng/ocp-build-data, pull requests merged in 2024-04, with the labels that each got.

#4575 ART-9115 Add networking-console-plugin
  images/networking-console-plugin.yml
Labels: lgtm, approved

#4587 [4.16] fix ose-ovn-kubernetes
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#4589 changing mapping for cnf-tests-container
  product.yml
Labels: lgtm, approved

#4590 Revert "Configuration tweak"
  images/openshift-enterprise-hyperkube.yml
  images/openshift-enterprise-pod.yml
  rpms/openshift.yml
Labels: lgtm, approved

#4427 Fix component for openstack-cluster-api-controllers-container
  product.yml
Labels: lgtm, approved

#4604 4.12 - Exclude all redhat-release rpms as reason for mass rebuild
  releases.yml
Labels: lgtm

#4613 Define 4.15.8 assembly
  releases.yml
Labels: lgtm, approved

#4617 [4.16] Use rhel 9.4 beta to build DTK
  group.yml
  images/driver-toolkit.yml
Labels: lgtm, approved

#4618 4.12.55 assembly definition
  releases.yml
Labels: lgtm, approved

#4601 [ART-8909] base image add azcopy
  images/ose-azure-storage-azcopy-base.yml
Labels: lgtm, approved, tide/merge-method-squash

#4633 [4.16] disable networking-console-plugin in ec5
  releases.yml
Labels: lgtm, approved

#4634 [4.16] Pin networking-console-plugin build to ec5
  releases.yml
Labels: lgtm, approved

#4630 Add openstack 17.1 repo for rhel9
  group.yml
Labels: lgtm, approved

#4635 MCO match upstream
  images/ose-machine-config-operator.yml
Labels: lgtm, approved

#4583 ose-baremetal-installer does not depend on terraform-providers
  images/ose-baremetal-installer.yml
Labels: lgtm, approved

#4631 Remove alternative_upstream for images that moved to rhel9
  images/egress-router-cni.yml
  images/monitoring-plugin.yml
  images/nmstate-console-plugin.yml
  images/openshift-enterprise-cluster-capacity.yml
  images/openshift-enterprise-console.yml
  images/ose-azure-workload-identity-webhook.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-kube-metrics-server.yml
  images/ose-kubevirt-csi-driver-rhel8.yml
  images/ose-machine-config-operator.yml
  images/ose-network-interface-bond-cni.yml
  images/ose-olm-operator-controller.yml
  images/ose-olm-rukpak.yml
  images/ose-route-controller-manager.yml
  images/prom-label-proxy.yml
Labels: lgtm, approved

#4585 Update etcd to match k8s 1.28.8
  ci_transforms/rhel-8/ci-build-root/Dockerfile
  ci_transforms/rhel-9/ci-build-root/Dockerfile
Labels: lgtm, approved

#4637 ose-installer-kube-apiserver-artifacts-container mapping
  product.yml
Labels: lgtm, approved

#4638 Disable cachito accounting for baremetal-operator: STONEBLD-2206
  images/ose-baremetal-operator.yml
Labels: lgtm, approved

#4639 Bump tests to 1.21
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4641 Remove alternative_upstream from images that switched
  images/openstack-cluster-api-controllers.yml
  images/ose-containernetworking-plugins.yml
Labels: lgtm, approved

#4651 Fix aws-efs-utils-base name
  images/ose-aws-efs-utils.yml
Labels: lgtm, approved

#4652 Fix azure-storage-azcopy-base name
  images/ose-azure-storage-azcopy-base.yml
Labels: lgtm, approved

#4640 cloud-credential-operator: to rhel9
  images/ose-cloud-credential-operator.yml
Labels: lgtm, approved

#4656 fix ci stream name
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4627 OCPBUGS-31802: Enable cachito for ironic container in 4.15
  images/ironic.yml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4629 OCPBUGS-31811: Build ironic-agent with cachito in 4.15
  images/ironic-agent.yml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4658 Remove alternative_upstream 2024-04-15
  images/openshift-enterprise-builder.yml
  images/ose-cloud-credential-operator.yml
  images/ose-cluster-olm-operator.yml
  images/ose-olm-catalogd.yml
Labels: lgtm, approved

#4660 rhel-8-golang-1.20 MINOR to 4.15
  group.yml
Labels: lgtm

#4662 bump MINOR to 4.15
  group.yml
Labels: lgtm

#4665 [ART-9397] 4.15 golang bump
  streams.yml
Labels: lgtm, approved

#4667 branch to openshift-4.17
  bug.yml
  erratatool.yml
  group.yml
  releases.yml
Labels: lgtm, approved

#4666 [ART-9397] 4.14 golang bump
  streams.yml
Labels: lgtm, approved

#4669 Fix ocp4_scan
  group.yml
Labels: lgtm, approved

#4668 Exclude LCA operator component in 4.14 bug search
  bug.yml
Labels: lgtm, approved

#4672 [ART-9397] 4.13 golang bump
  streams.yml
Labels: lgtm, approved

#4674 Relax golang check while we wait for rhel8 1.22 build
  group.yml
Labels: lgtm, approved

#4675 4.16 v1.19.13 golang bump
  streams.yml
Labels: lgtm, approved

#4677 4.14 v1.19.13 golang bump
  streams.yml
Labels: lgtm, approved

#4676 4.15 v1.19.13 golang bump
  streams.yml
Labels: lgtm, approved

#4680 Fix ib-sriov-cni build
  images/ib-sriov-cni.yml
Labels: lgtm, approved

#4681 [4.15] fix sriov-cni rebase
  images/sriov-cni.yml
Labels: lgtm, approved

#4682 Add preview of golang 1.22 build root image
  streams.yml
Labels: lgtm, approved

#4690 [4.16] fix agent-installer-csr-approver
  images/ose-agent-installer-csr-approver.yml
Labels: lgtm, approved

#4688 early-kernel: Change target release to 4.14.z
  bug.yml
Labels: lgtm, approved

#4689 early-kernel: Change target version to 4.15.z
  bug.yml
Labels: lgtm, approved

#4642 Adds {gcr,acr}-image-credential-provider
  rpms/ose-azure-acr-image-credential-provider.yml
  rpms/ose-gcp-gcr-image-credential-provider.yml
Labels: lgtm, approved

#4698 remove golang-1.21 stream from 4.15
  streams.yml
Labels: lgtm, approved, tide/merge-method-squash

#4695 [ART-9397] 4.16 golang bump
  streams.yml
Labels: lgtm, approved

#4700 Follow upstream change
  images/ose-agent-installer-csr-approver.yml
Labels: lgtm, approved

#4702 no openshift-clients
  rpms/openshift-clients.yml
Labels: lgtm, approved

#4598 Tools to rhel9
  images/openshift-enterprise-tests.yml
  images/ose-network-tools.yml
  images/ose-tools.yml
Labels: lgtm, approved

#4706 Fix ose-tools Dockerfile reference
  images/ose-tools.yml
Labels: lgtm, approved

#4710 Allow rteval to be installed from rhel9 rt repo
  group.yml
Labels: lgtm, approved

#4683 [ART-9295] dpu image adds
  images/dpu-cni.yml
  images/dpu-daemon.yml
  images/dpu-operator.yml
  images/kube-rbac-proxy.yml
Labels: lgtm, approved, tide/merge-method-squash

#4713 4.16 golang bump v1.21.9
  streams.yml
Labels: lgtm, approved

#4717 Fix tests
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4722 Remove ship-ok tag check for early kernel
  group.yml
Labels: lgtm, approved

#4721 Update dpu-operator bundle name
  images/dpu-operator.yml
Labels: lgtm, approved

#4719 Revert "Fix tests"
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4720 Revert "[openshift-4.16] Fix tests"
  images/openshift-enterprise-tests.yml
Labels: lgtm, approved

#4708 OCPBUGS-32170,OCPBUGS-32169: add ironic and ironic-agent cachito configuration
  images/ironic-agent.yml
  images/ironic.yml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4737 promote permit 4.14.23 ATTACHED_BUGS
  releases.yml
Labels: lgtm, approved

#4599 Add dpu-operator to product config
  product.yml
Labels: lgtm, approved

#4728 CORS-3250: installer: add etcd/kas to altinfra image.
  images/ose-installer-altinfra.yml
Labels: lgtm, approved, jira/valid-reference

#4739 4.15.11: Permit INVALID_ERRATA_STATUS
  releases.yml
Labels: lgtm, approved

#4744 dpu-cni bump builder to rhel9
  images/dpu-cni.yml
Labels: lgtm, approved

#4748 Switch to 9.4 GA repos
  group.yml
Labels: lgtm, approved

#4747 Switch to 9.4 GA repos
  group.yml
Labels: lgtm, approved

#4749 Fix rt repo
  group.yml
Labels: lgtm, approved

#4751 Fix installer builds
  images/ose-baremetal-installer.yml
  images/ose-installer.yml
Labels: lgtm, approved

#4753 [4.16.0-ec.6] pin NVRs for components that did not exist at nightly time
  releases.yml
Labels: lgtm, approved

#4757 installer: oc from rpm
  images/ose-baremetal-installer.yml
  images/ose-installer.yml
Labels: lgtm

#4754 must-gather inherits from cli-artifacts
  images/ose-must-gather.yml
Labels: lgtm, approved

#4761 [4.16.0-ec.6] override dpu-operator metadata
  releases.yml
Labels: lgtm, approved

#4709 installer images to rhel9
  images/ose-baremetal-installer.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-installer.yml
  images/ose-machine-os-images.yml
Labels: lgtm, approved
