Repository openshift-eng/ocp-build-data, pull requests merged in 2025-02, with the labels that each got.

#6047 Pin dtk to stream assembly to match kernel from rhcos
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6050 [4.19] unpin dtk
  releases.yml
Labels: lgtm, approved

#6066 Revert "Add assembly 4.15.45"
  releases.yml
Labels: do-not-merge/hold

#6062 Update Owners file to add jkaurredhat to 4.12 release
  OWNERS
Labels: lgtm, approved

#6067 Pin openshift-4.18.0 RPM
  releases.yml
Labels: lgtm, approved

#6068 [4.19] temporarily allow RHCOS RPM inconsistencies
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6063 Update Owners to add jkaurredhat to 4.13 release
  OWNERS
Labels: lgtm, approved

#6051 ART-11973: add ORC to product.yml
  product.yml
Labels: lgtm, approved, jira/valid-reference

#6074 [konflux] ppc VM with bigger disk space, s390x
  images/ose-installer-artifacts.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6075 [ART-11911][konflux] enable ansible-operator
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6080 Set pre-release operator index mode in rc.8
  releases.yml
Labels: lgtm, approved

#6081 Dynamic removal of cachito references to REMOTE_SOURCES
  images/openshift-enterprise-console.yml
Labels: lgtm, approved

#6082 4.12.73 Include bugs
  releases.yml
Labels: lgtm, approved

#6084 Revert "OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo"
  images/ose-olm-catalogd.yml
Labels: jira/valid-reference

#6085 Revert "Revert "OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo""
  images/ose-olm-catalogd.yml
Labels: jira/valid-reference

#6087 [konflux] sync overrides from 4.19
  images/driver-toolkit.yml
  images/monitoring-plugin.yml
  images/networking-console-plugin.yml
  images/nmstate-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-console.yml
  images/ose-baremetal-installer.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
Labels: lgtm, approved

#6088 [konflux] disable kuryr images in 4.12
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: lgtm, approved

#6090 ART-12057 Use EUS base RHEL image
  images/microshift-bootc.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6094 Freeze 4.15 automation for mass rebuild management
  group.yml
Labels: lgtm, approved

#6093 Freeze 4.19 automation for mass rebuild management
  group.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6095 Freeze 4.18 automation for mass rebuild management
  group.yml
Labels: lgtm, approved

#6099 [konflux] rename VM flavor to linux-d200-large/ppc64le
  images/ose-installer-artifacts.yml
Labels: do-not-merge/hold

#6103 Revert "Freeze 4.19 automation for mass rebuild management"
  group.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6104 Revert "Freeze 4.18 automation for mass rebuild management"
  group.yml
Labels: lgtm, approved

#6106 Make rc.9 prerelease
  releases.yml
Labels: lgtm, approved

#6092 Fix ci build root stream
  images/openstack-resource-controller.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6108 linuxptp-daemon: Update dockerfile path
  images/linuxptp-daemon.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6096 Use consistent powerful instances across heavyweight builds
  images/ose-baremetal-installer.yml
  images/ose-cli-artifacts.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
Labels: lgtm, approved, tide/merge-method-squash, acknowledge-critical-fixes-only

#6120 OSDOCS-11376-414: updates release note link for MicroShift 4.14
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#6119 OSDOCS-13376-415: updates release note link for MicroShift 4.15
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#6117 OSDOCS-11376-417: updates release note link for MicroShift 4.17
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#6091 add HighAvailability repo
  group.yml
  images/driver-toolkit.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6138 pin ose-sriov-rdma-cni
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6139 chore: remove grafana -> Monitoring mapping as since OCP 4.11 it's no longer shipped
  product.yml
Labels: lgtm, approved

#6059 add ocp component dpu-intel-ipu-vsp
  images/dpu-intel-ipu-vsp.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6146 Revert "[konflux] disable kuryr images in 4.12"
  images/kuryr-cni.yml
  images/kuryr-controller.yml
Labels: lgtm, approved

#6149 exempt bind*
  releases.yml
Labels: lgtm, approved

#6150 exempt bind*
  releases.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6151 [4.19] fix ci alignment for openstack-resource-controller
  images/openstack-resource-controller.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6161 Add 4.18.1
  releases.yml
Labels: lgtm, approved

#6164 Remove quotes around strings in assembly basis
  releases.yml
Labels: lgtm

#6166 Revert "exempt bind*"
  releases.yml
Labels: lgtm, approved

#6165 Revert "exempt bind*"
  releases.yml
Labels: lgtm, approved

#6168 [konflux] cli-artifacts use d320 VMs
  images/ose-cli-artifacts.yml
Labels: lgtm

#6179 Freeze automation
  group.yml
Labels: lgtm, approved

#6178 stop mass rebuilds
  releases.yml
Labels: lgtm, approved

#6180 Update OWNERS of baremetal-machine-controller in 4.19
  images/baremetal-machine-controller.yml
Labels: lgtm, approved

#6181 Update OWNERS of baremetal-machine-controller in 4.18
  images/baremetal-machine-controller.yml
Labels: lgtm, approved

#6182 ART-11047:changed target_release
  bug.yml
Labels: lgtm, approved, jira/valid-reference

#6183 change 4.18 release lifecycle to release
  group.yml
Labels: lgtm, approved

#6185 [konflux] alibaba tagging mode
  images/ose-alibaba-machine-controllers.yml
Labels: lgtm, approved

#6184 [konflux] vpa tagging mode
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6196 added image to payload
  images/openstack-resource-controller.yml
Labels: lgtm, approved

#6199 Fix payload reference openstack-resource-controller
  images/openstack-resource-controller.yml
Labels: lgtm, approved

#6200 [konflux] ose-cli-artifacts IBM flavor update
  images/ose-cli-artifacts.yml
Labels: lgtm, approved

#6201 [konflux] ose-cli-artifacts IBM flavor update
  images/ose-cli-artifacts.yml
Labels: lgtm

#6169 create 4.19 10.0 repos for CI
  group.yml
Labels: lgtm, approved

#6212 permit attached_bugs in promote
  releases.yml
Labels: lgtm, approved

#6249 Update bug mapping for Secrets Store CSI driver images
  product.yml
Labels: lgtm, approved

#6251 ART-12115 remove images/openshift-enterprise-operator-sdk.yml
  images/openshift-enterprise-operator-sdk.yml
Labels: lgtm, approved

#6252 [ART-12210] 4.18.2: added Microshift advisory
  releases.yml
Labels: lgtm, approved
