Repository openshift-eng/ocp-build-data, pull requests merged in 2025-09, with the labels that each got.

#7485 Bump 4.13 golang manually
  streams.yml
Labels: lgtm, approved

#7486 Golang bump of 4.12
  streams.yml
Labels: lgtm, approved

#7491 Disable cachi2 ci-openshift-golang-builder-extra.rhel9.yml
  images/ci-openshift-golang-builder-extra.rhel9.yml
Labels: lgtm, approved

#7499 Add delivery_repo_names to ingress-node-firewall-operator
  images/ingress-node-firewall-operator.yml
Labels: lgtm, approved

#7302 [ART-13925] Add image support-log-gather-operator
  images/ose-must-gather.yml
  images/ose-support-log-gather-operator.yml
Labels: lgtm, approved, tide/merge-method-squash

#7507 exclude bug for 4.19.10
  releases.yml
Labels: lgtm, approved

#7514 4.12.80 - revert to earlier advisory ids for rpm and rhcos
  releases.yml
Labels: lgtm, approved

#7515 excluded bug
  releases.yml
Labels: lgtm, approved

#7523 Disable hermetic mode for ci-openshift-golang-builder-extra.rhel9
  images/ci-openshift-golang-builder-extra.rhel9.yml
Labels: lgtm, approved

#7487 Update etcd to match k8s 1.33.4
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#7533 4.20: Stop signing
  group.yml
  rpms/openshift-clients.yml
  rpms/openshift.yml
Labels: lgtm, approved

#7538 Revert "Update group.yml"
  group.yml
Labels: lgtm, approved

#7540 Revert 4.16 automation to all days
  group.yml
Labels: lgtm, approved

#7541 added missing component
  product.yml
Labels: lgtm, approved

#7477 ART-14033: template payload shas automatically
  config/advisory_templates.yml
Labels: jira/valid-reference

#7570 Set network_mode to hermetic
  group.yml
  images/openshift-base-rhel9.yml
Labels: lgtm, approved

#7565 Set network_mode to hermetic
  images/openshift-base-rhel8.yml
  images/openshift-base-rhel9.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
Labels: lgtm, approved, tide/merge-method-squash

#7601 Get 4.15 to build
  group.yml
  images/openshift-enterprise-base-rhel9.yml
  images/openshift-enterprise-base.yml
  streams.yml
Labels: lgtm, approved

#7492 Add new-style repo config files
  group.ext.yml
  plashet.yml
  repos/openstack-17-for-rhel-9-rpms.yml
  repos/rhel-10-appstream.yml
  repos/rhel-10-baseos.yml
  repos/rhel-10-highavailability.yml
  repos/rhel-10-nfv.yml
  repos/rhel-10-server-ose-rpms-embargoed.yml
  repos/rhel-10-server-ose-rpms.yml
  repos/rhel-8-appstream-rpms.yml
  repos/rhel-8-baseos-rpms.yml
  repos/rhel-8-fast-datapath-rpms.yml
  repos/rhel-8-server-ose-rpms-embargoed.yml
  repos/rhel-8-server-ose-rpms.yml
  repos/rhel-9-appstream-rpms.yml
  repos/rhel-9-baseos-rpms.yml
  repos/rhel-9-codeready-builder-rpms.yml
  repos/rhel-9-fast-datapath-rpms.yml
  repos/rhel-9-rt-rpms.yml
  repos/rhel-9-server-ironic-rpms.yml
  repos/rhel-9-server-microshift-rpms.yml
  repos/rhel-9-server-ose-rpms-embargoed.yml
  repos/rhel-9-server-ose-rpms.yml
  repos/rhel-96-appstream.yml
  repos/rhel-96-baseos.yml
  repos/rhel-96-highavailability.yml
  repos/rhel-96-nfv.yml
Labels: lgtm, approved

#7614 prepare new prerelease based on rc.1
  releases.yml
Labels: tide/merge-method-squash

#7638 bump(k8s): bump 4.21 builder image to etcd version 3.6.4
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#7622 Revert "Disable ose-support-log-gather-operator"
  images/ose-support-log-gather-operator.yml
Labels: do-not-merge/hold

#7710 fix: add trailing slash to baseurl entries (4.12)
  group.yml
Labels: lgtm, approved

#7715 fix: add trailing slash to baseurl entries (4.17)
  group.yml
Labels: lgtm, approved

#7763 build(konflux): convert 2 images to hermetic mode
  images/ose-aws-ebs-csi-driver.yml
  images/ose-frr.yml
Labels: lgtm, approved

#7761 build(konflux): convert 2 CSI/networking images to hermetic mode
  images/ose-aws-ebs-csi-driver.yml
  images/ose-frr.yml
Labels: lgtm, approved

#7226 [openshift-4.18] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved, jira/valid-reference

#7228 [openshift-4.16] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved, jira/valid-reference

#7227 [openshift-4.17] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved, jira/valid-reference

#7510 [openshift-4.15] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved, jira/valid-reference
