Repository openshift-eng/ocp-build-data, pull requests merged in 2025-07, with the labels that each got.

#7061 Enable Hermeto for 4.19
  group.yml
Labels: lgtm, approved

#7063 ART-13269: [4.20] add explicit delivery repo names #2
  images/cluster-nfd-operator.yml
  images/local-storage-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-smb-csi-driver-operator.yml
  images/ptp-operator.yml
Labels: jira/valid-reference

#7066 Update golang 4.17 1.22.12
  group.yml
  streams.yml
Labels: lgtm, approved

#7080 ART-13269: [4.15] fix rhel8 names
  images/azure-file-csi-driver-operator.yml
  images/csi-driver-manila-operator.yml
  images/csi-livenessprobe.yml
  images/csi-node-driver-registrar.yml
  images/csi-provisioner.yml
  images/egress-router-cni.yml
  images/monitoring-plugin.yml
  images/nmstate-console-plugin.yml
  images/openshift-enterprise-operator-sdk.yml
  images/openstack-cluster-api-controllers.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-agent-installer-orchestrator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-aws-efs-csi-driver.yml
  images/ose-azure-disk-csi-driver-operator.yml
  images/ose-azure-workload-identity-webhook.yml
  images/ose-baremetal-installer.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-containernetworking-plugins.yml
  images/ose-csi-driver-shared-resource-mustgather.yml
  images/ose-csi-external-resizer.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver.yml
  images/ose-gcp-pd-csi-driver-operator.yml
  images/ose-image-customization-controller.yml
  images/ose-installer-altinfra.yml
  images/ose-kube-metrics-server.yml
  images/ose-kubevirt-csi-driver-rhel8.yml
  images/ose-machine-os-images.yml
  images/ose-metallb-operator.yml
  images/ose-multus-route-override-cni.yml
  images/ose-multus-whereabouts-ipam-cni.yml
  images/ose-network-interface-bond-cni.yml
  images/ose-network-tools.yml
  images/ose-olm-catalogd.yml
  images/ose-olm-operator-controller.yml
  images/ose-olm-rukpak.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-route-controller-manager.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-secrets-store-csi-mustgather.yml
  images/ose-tools.yml
  images/ptp-operator-must-gather.yml
  images/thanos.yml
Labels: jira/valid-reference

#7084 fix indent in docs template
  erratatool.yml
Labels: lgtm, approved

#7083 ART-13269: [4.15] fix bundle namesfix bundle name
  images/ose-metallb-operator.yml
Labels: lgtm, approved, jira/valid-reference

#7094 exclude bug for 4.19.3
  releases.yml
Labels: lgtm, approved

#7110 pin gotestsum to v1.12.2
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
Labels: lgtm, approved

#7112 Pin dpu-operator in stream
  releases.yml
Labels: lgtm, approved

#7113 Fix validator 4.15
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-csi-driver-shared-resource-webhook.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-nutanix-cloud-controller-manager.yml
Labels: lgtm, approved

#7118 4.14: Fix web for validator
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-csi-driver-shared-resource-webhook.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-nutanix-cloud-controller-manager.yml
Labels: lgtm, approved

#7119 4.13: Fix web for validator
  images/ose-cluster-control-plane-machine-set-operator.yml
  images/ose-csi-driver-shared-resource-webhook.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-nutanix-cloud-controller-manager.yml
Labels: lgtm, approved

#7122 fix ci for volume-data
  images/volume-data-source-validator.yml
Labels: lgtm, approved

#7121 ART-13333: [4.19] make delivery_repo_names as list #2
  images/microshift-bootc.yml
Labels: lgtm, approved, jira/valid-reference

#7125 Freeze automation to prevent mass rebuild
  group.yml
Labels: lgtm, approved

#7127 Freeze automation
  group.yml
Labels: lgtm, approved

#7128 Freeze automation
  group.yml
Labels: lgtm, approved

#7099 AUTOSCALE-286: opt clusterresourceoverride into auto_label for merge
  images/clusterresourceoverride-operator.yml
  images/clusterresourceoverride.yml
Labels: lgtm, approved, jira/valid-reference

#7135 revoke stream_permits in 4.19
  releases.yml
Labels: lgtm, approved

#7133 revoke stream_permits in 4.12
  releases.yml
Labels: lgtm, approved

#7136 check_golang_versions for z-version
  group.yml
Labels: lgtm, approved

#7149 Re-enable openshift-kubernetes-nmstate-operator, ose-metallb-operator.yml, pf-status-relay-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-metallb-operator.yml
  images/pf-status-relay-operator.yml
Labels: lgtm, approved

#7154 ART-13260: Replace add modifications with disabling cachi2 in 4.18
  images/coredns.yml
  images/csi-driver-manila.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-metallb.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#7155 ART-13260: Disable cachi2 for ptp-operator in 4.15
  images/ptp-operator.yml
Labels: lgtm, approved, jira/valid-reference

#7156 ART-13260: Disable cachi2 for several images in 4.13
  images/baremetal-machine-controller.yml
  images/cluster-network-operator.yml
  images/csi-driver-manila.yml
  images/ibm-vpc-node-label-updater.yml
  images/node-feature-discovery.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-cluster-api.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-haproxy-router-base.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-ibmcloud-machine-controllers.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-operator.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-machine-api-provider-openstack.yml
  images/ose-metallb-operator.yml
  images/ose-nutanix-machine-controllers.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-powervs-machine-controllers.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
  images/ptp-operator.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved, jira/valid-reference

#7167 exclude bug
  releases.yml
Labels: lgtm, approved

#7169 Include golang cves
  releases.yml
Labels: lgtm, approved

#7173 Exclude bug from releases.yml
  releases.yml
Labels: lgtm, approved

#7174 include blcoker bug
  releases.yml
Labels: lgtm, approved

#7175 include blcoker bug
  releases.yml
Labels: lgtm, approved

#7180 ART-13260: Disable cachi2 for several images in 4.12
  images/baremetal-machine-controller.yml
  images/csi-driver-manila.yml
  images/ibm-vpc-node-label-updater.yml
  images/node-feature-discovery.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-agent-installer-orchestrator.yml
  images/ose-alibaba-cloud-csi-driver.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-azure-disk-csi-driver.yml
  images/ose-cluster-api.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-haproxy-router-base.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-ibmcloud-machine-controllers.yml
  images/ose-machine-api-operator.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-machine-config-operator.yml
  images/ose-metallb-operator.yml
  images/ose-multus-route-override-cni.yml
  images/ose-nutanix-machine-controllers.yml
  images/ose-openshift-controller-manager.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-powervs-machine-controllers.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
  images/ptp-operator.yml
  images/sriov-cni.yml
  images/sriov-network-config-daemon.yml
  images/sriov-network-operator.yml
  images/sriov-network-webhook.yml
Labels: lgtm, approved, jira/valid-reference

#7181 Revert "Freeze automation"
  group.yml
Labels: lgtm, approved

#7210 ART-13407: 4.19 hermetic #3
  images/dpu-intel-ipu-vsp.yml
  images/driver-toolkit.yml
  images/golang-github-prometheus-node_exporter.yml
  images/golang-github-prometheus-prometheus.yml
  images/ironic-rhcos-downloader.yml
  images/ironic.yml
  images/linuxptp-daemon.yml
  images/okd-only-upi-installer.yml
  images/openshift-base-rhel9.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-haproxy-router.yml
  images/ose-agent-installer-api-server.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-frr.yml
  images/ose-image-customization-controller.yml
  images/ose-insights-runtime-extractor.yml
  images/ose-machine-config-operator.yml
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/prom-label-proxy.yml
  images/thanos.yml
Labels: lgtm, approved, jira/valid-reference

#7211 fix: add trailing slashes to base URLs in group.yml for consistency
  group.yml
Labels: lgtm, approved

#7205 Fix names 4.16
  images/aws-kms-encryption-provider.yml
  images/azure-kms-encryption-provider.yml
  images/container-networking-plugins-microshift.yml
  images/csi-driver-manila-operator.yml
  images/driver-toolkit.yml
  images/egress-router-cni.yml
  images/networking-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-helm-operator.yml
  images/ose-cloud-credential-operator.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-cluster-olm-operator.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-csi-driver-shared-resource-operator.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-image-customization-controller.yml
  images/ose-kubevirt-csi-driver-rhel8.yml
  images/ose-machine-config-operator.yml
  images/ose-network-tools.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-operator-framework-tools.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-route-controller-manager.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#7207 Fix names 4.18
  images/aws-kms-encryption-provider.yml
  images/azure-kms-encryption-provider.yml
  images/container-networking-plugins-microshift.yml
  images/csi-driver-manila-operator.yml
  images/driver-toolkit.yml
  images/egress-router-cni.yml
  images/kube-compare-artifacts.yml
  images/microshift-bootc.yml
  images/networking-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-helm-operator.yml
  images/ose-azure-service-operator.yml
  images/ose-cloud-credential-operator.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-cluster-olm-operator.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-image-customization-controller.yml
  images/ose-insights-runtime-exporter.yml
  images/ose-insights-runtime-extractor.yml
  images/ose-kubevirt-csi-driver-rhel8.yml
  images/ose-machine-config-operator.yml
  images/ose-network-tools.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-operator-framework-tools.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-route-controller-manager.yml
  images/ose-tools.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#7208 Fix names 4.19
  images/aws-kms-encryption-provider.yml
  images/azure-kms-encryption-provider.yml
  images/container-networking-plugins-microshift.yml
  images/csi-driver-manila-operator.yml
  images/driver-toolkit.yml
  images/egress-router-cni.yml
  images/kube-compare-artifacts.yml
  images/microshift-bootc.yml
  images/networking-console-plugin.yml
  images/oc-mirror-plugin.yml
  images/openshift-enterprise-helm-operator.yml
  images/openstack-resource-controller.yml
  images/ose-azure-service-operator.yml
  images/ose-cloud-credential-operator.yml
  images/ose-cloud-network-config-controller.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-cluster-olm-operator.yml
  images/ose-cluster-ovirt-csi-operator.yml
  images/ose-ibm-vpc-block-csi-driver-operator.yml
  images/ose-image-customization-controller.yml
  images/ose-insights-runtime-exporter.yml
  images/ose-insights-runtime-extractor.yml
  images/ose-kubevirt-csi-driver-rhel8.yml
  images/ose-machine-config-operator.yml
  images/ose-network-tools.yml
  images/ose-openstack-cinder-csi-driver-operator.yml
  images/ose-operator-framework-tools.yml
  images/ose-powervs-block-csi-driver-operator.yml
  images/ose-route-controller-manager.yml
  images/ose-tools.yml
  images/ose-vmware-vsphere-csi-driver-operator.yml
  images/ptp-operator-must-gather.yml
Labels: lgtm, approved

#7232 [4.20] add delivery_repo_names
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-metallb-operator.yml
  images/pf-status-relay-operator.yml
Labels: lgtm, approved

#7213 ART-13429: ci-openshift-build-root*: Stop building in Konflux
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
Labels: lgtm, approved, jira/valid-reference

#7214 ART-13429: ci-openshift-build-root*: Stop building in Konflux
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
Labels: lgtm, approved, jira/valid-reference

#7212 ART-13429: ci-openshift-build-root*: Stop building in Konflux
  images/ci-openshift-build-root-latest.rhel8.yml
Labels: lgtm, approved, jira/valid-reference

#7216 ART-13429: ci-openshift-build-root*: Stop building in Konflux
  images/ci-openshift-build-root-latest.rhel8.yml
  images/ci-openshift-build-root-latest.rhel9.yml
Labels: lgtm, approved, jira/valid-reference

#7243 fix ose-metallb-operator build errors
  images/kube-rbac-proxy.yml
  images/ose-frr.yml
Labels: lgtm, approved

#7248 [temporary]: pin driver-toolkit to match kernel version used by rhcos
  releases.yml
Labels: lgtm, approved

#7249 pin dtk
  releases.yml
Labels: lgtm, approved

#7259 Renable dpu-operator, sriov-network-operator, clusterresource override operator
  images/clusterresourceoverride-operator.yml
  images/dpu-operator.yml
  images/sriov-network-operator.yml
Labels: lgtm, approved, tide/merge-method-squash

#7264 scan-sources:noop Set network_mode to open
  images/openshift-base-nodejs.rhel9.yml
  images/openshift-enterprise-keepalived-ipfailover.yml
  images/ose-egress-http-proxy.yml
Labels: lgtm, approved

#7269 exclude OCPBUGS-52548
  releases.yml
Labels: lgtm, approved

#7270 Update konflux configuration to include lockfile settings for egress-…
  images/egress-router-cni.yml
  images/ose-containernetworking-plugins.yml
  images/ose-secrets-store-csi-driver.yml
Labels: lgtm, approved

#7273 openshift-4.14: Move from eus to e4s for 9.2 content
  group.yml
Labels: lgtm, approved

#7280 Fix ovn payload name
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#7275 Update 4.14.54 to include missed bugs
  releases.yml
Labels: lgtm, approved

#7297 Add security_reviewer to boilerplates [4.13]
  erratatool.yml
Labels: lgtm, approved
