Repository openshift-eng/ocp-build-data, pull requests merged in 2025-05, with the labels that each got.

#6697 [openshift-4.19] start singing RPMs
  group.yml
Labels: lgtm, approved

#6587 Remove Terraform & Altinfra Images
  images/okd-only-upi-installer.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-installer.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6688 [openshift-4.20] Remove Terraform & Altinfra Images
  images/okd-only-upi-installer.yml
  images/ose-installer-altinfra.yml
  images/ose-installer-artifacts.yml
  images/ose-installer-terraform-providers.yml
  images/ose-installer.yml
Labels: lgtm, approved, tide/merge-method-squash

#6707 Fix ose-ovn-kubernetes payload name
  group.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6695 ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#6718 oc-mirror: Point to v2 go.mod
  images/oc-mirror-plugin.yml
Labels: lgtm, approved

#6706 ART-12761: keep common docs template in main
  config/advisory_templates.yml
Labels: lgtm, jira/valid-reference

#6728 add cert to CI images
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, do-not-merge/hold

#6738 [4.15] fix libreswan exemption
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#6736 [4.18] fix libreswan exemption
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#6746 Add microshift entry to 4.16.40 assembly
  releases.yml
Labels: lgtm, approved

#6727 ART-12763: move OCP 4.19 to real RHEL 9.6
  group.yml
Labels: lgtm, approved, jira/valid-reference

#6752 ART-12761: Move templates from version specific ones
  config/advisory_templates.yml
Labels: lgtm, approved, jira/valid-reference

#6756 Fix NFV repo urls
  group.yml
Labels: lgtm, approved

#6757 Remove workaround aws-ebs-csi-driver
  images/ose-aws-ebs-csi-driver.yml
Labels: lgtm, approved

#6751 ART-12761: remove boilerplate from config
  erratatool.yml
Labels: lgtm, approved, jira/valid-reference

#6758 ART-12761: Update microshift release notes template
  config/advisory_templates.yml
Labels: jira/valid-reference

#6765 Fix metallb rebase
  images/ose-metallb.yml
Labels: lgtm, approved

#6773 Remove boilerplate from 4.12 errata config
  erratatool.yml
Labels: lgtm, approved

#6769 Remove boilerplate from 4.16 errata config
  erratatool.yml
Labels: lgtm, approved

#6772 Remove boilerplate from 4.13 errata config
  erratatool.yml
Labels: lgtm, approved

#6770 Remove boilerplate from 4.15 errata config
  erratatool.yml
Labels: lgtm, approved

#6771 Remove boilerplate from 4.14 errata config
  erratatool.yml
Labels: lgtm, approved

#6777 permit ATTACHED_BUGS for 4.17.30
  releases.yml
Labels: lgtm, approved

#6775 ART-12761: template impact
  config/advisory_templates.yml
Labels: lgtm, approved, jira/valid-reference

#6781 Fix ibmcloud rebase
  images/kube-rbac-proxy.yml
  images/ose-frr.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
Labels: lgtm, approved

#6779 Stop building metallb until golang1.24 is available and consumed
  images/kube-rbac-proxy.yml
  images/ose-frr.yml
  images/ose-metallb-operator.yml
  images/ose-metallb.yml
Labels: lgtm, approved

#6780 add docs bootc template
  config/advisory_templates.yml
Labels: lgtm, tide/merge-method-squash

#6784 4.15.51 drop microshift advisory
  releases.yml
Labels: lgtm

#6786 Remove EXTRA mentions
  streams.yml
Labels: lgtm, approved

#6774 [4.13] docs override
  erratatool.yml
Labels: lgtm

#6791 [4.10] remove dtk redundant repos
  images/driver-toolkit.yml
Labels: approved

#6790 [4.19] remove dtk redundant repos
  images/driver-toolkit.yml
Labels: approved

#6792 ART-12956: update microshift-bootc image to RHEL9.6
  images/microshift-bootc.yml
Labels: lgtm, approved, jira/valid-reference

#6789 Fix cluster-api-provider-vsphere rebase
  images/ose-vsphere-cluster-api-controllers.yml
Labels: lgtm, approved

#6796 Fix rebase failures
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-metallb.yml
  images/ose-vsphere-cloud-controller-manager.yml
Labels: lgtm, approved

#6799 CVES param for microshift
  config/advisory_templates.yml
Labels: lgtm, approved

#6800 Fix dtk konflux repos
  images/driver-toolkit.yml
Labels: lgtm, approved

#6809 exclude issue OCPBUGS-43685
  releases.yml
Labels: lgtm, approved

#6811 exclude issue OCPBUGS-37369
  releases.yml
Labels: lgtm, approved

#6812 skip "Low latency validation tooling" component
  bug.yml
Labels: lgtm, approved

#6817 ART-13005: Make go1.23 available in streams and as 4.18 CI images
  streams.yml
Labels: lgtm, approved, jira/valid-reference

#6824 4.14: reinstate rhel8 go1.19 builder
  streams.yml
Labels: lgtm, approved

#6826 Get rhel8 builder to normal go1.20 for ovn-k
  images/ose-ovn-kubernetes.yml
Labels: lgtm, approved

#6820 Route windows-machine-config-rhel{8,9}-operator to Windows Containers
  product.yml
Labels: lgtm, approved

#6830 Pin NTO for bad tuned
  releases.yml
Labels: lgtm, approved

#6833 stop adding vendored file
  images/ose-machine-api-provider-openstack.yml
Labels: lgtm, approved

#6835 Fix 4.14 sync-ci-images again
  streams.yml
Labels: lgtm, approved

#6841 exclude OCPBUGS-43685
  releases.yml
Labels: lgtm

#6844 [4.17.32] add promotion permits
  releases.yml
Labels: lgtm

#6848 Update releases.yml
  releases.yml
Labels: lgtm, approved

#6853 [4.20] Add EC.1
  releases.yml
Labels: lgtm

#6854 [4.20.0-ec.1] add upgrade edges
  releases.yml
Labels: lgtm
