Repository openshift-eng/ocp-build-data, pull requests merged in 2025-06, with the labels that each got.

#6858 Revert "Pin NTO for bad tuned"
  releases.yml
Labels: lgtm, approved

#6857 4.12: Unpin tuned image
  releases.yml
Labels: lgtm, approved

#6859 include bug OCPBUGS-56740
  releases.yml
Labels: lgtm, approved

#6860 custom pre-release
  releases.yml
Labels: lgtm

#6862 Pin insights operator commit and build
  releases.yml
Labels: lgtm, approved

#6864 add assembly ec.2
  releases.yml
Labels: lgtm

#6865 [4.20 ex.2] remove brewevent since its for konflux
  releases.yml
Labels: lgtm, approved

#6872 console modification for hermeto
  images/openshift-enterprise-console.yml
Labels: lgtm

#6868 ART-13076: Initialize go1.24 rhel8 branch
  group.yml
  images/openshift-golang-builder.Dockerfile
  images/openshift-golang-builder.yml
Labels: lgtm, approved, jira/valid-reference

#6898 4.16.42: Exclude OCPBUGS-43686
  releases.yml
Labels: lgtm, approved

#6902 exclude bug
  releases.yml
Labels: lgtm, approved

#6903 4.19 rc.5 pin cluster-nfd-operator
  releases.yml
Labels: lgtm, approved

#6909 Make go1.24 available to ocp4.20
  group.yml
  streams.yml
Labels: lgtm, approved

#6911 pinning sriov with correct imagestreams
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#6925 4.17: Adjust Hermeto bits in monitoring-plugin dockerfile
  images/monitoring-plugin.yml
Labels: lgtm, approved

#6926 4.16: Adjust Hermeto bits in monitoring-plugin dockerfile
  images/monitoring-plugin.yml
Labels: lgtm, approved

#6927 Configure ovn for Hermeto
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#6928 Fix hermeto config ovn images
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#6931 Updates MicroShift bootc image boiler plate advisory text
  config/advisory_templates.yml
Labels: lgtm, approved

#6936 [4.17] monitoring fix
  images/monitoring-plugin.yml
Labels: lgtm, do-not-merge/hold

#6937 [4.16] monitoring fix
  images/monitoring-plugin.yml
Labels: lgtm

#6942 add exempt_rpms for 4.16 rhcos
  group.yml
Labels: lgtm, approved

#6947 [4.19] - Ignore low latency image that we do not build
  bug.yml
Labels: lgtm, approved

#6951 helloworld operator add labels
  Dockerfile
Labels: lgtm

#6953 Add go1.21 to 4.15 for a select few images
  streams.yml
Labels: lgtm, approved

#6960 Start opening reconciliation PRs for 4.20
  group.yml
Labels: lgtm, approved

#6956 Set 4.19 to release phase
  group.yml
Labels: lgtm, approved

#6970 Allow network-interface-bond-cni to build with go1.23 on 4.18
  images/ose-network-interface-bond-cni.yml
Labels: lgtm, approved

#6971 [4.20] Reinstate brew event for ec.2
  releases.yml
Labels: lgtm, approved

#6966 Add bundle_delivery_repo_name for all OLM bundles - 4.17
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/dpu-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-smb-csi-driver-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6963 Add bundle_delivery_repo_name for all OLM bundles - 4.18
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/dpu-operator.yml
  images/helloworld-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-smb-csi-driver-operator.yml
  images/pf-status-relay-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6967 Add bundle_delivery_repo_name for all OLM bundles - 4.16
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/dpu-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-smb-csi-driver-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6968 Add bundle_delivery_repo_name for all OLM bundles - 4.15
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6989 Update releases.yml
  releases.yml
Labels: lgtm, approved

#6991 Update releases.yml
  releases.yml
Labels: lgtm, approved

#6996 exclude bug
  releases.yml
Labels: lgtm, approved

#6997 Allow NEW_FILES advisory for 4.18.18
  releases.yml
Labels: lgtm, approved, tide/merge-method-squash

#6998 Update releases.yml
  releases.yml
Labels: lgtm, approved

#6984 Add bundle_delivery_repo_name for all OLM bundles - 4.14
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ose-secrets-store-csi-driver-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6985 Add bundle_delivery_repo_name for all OLM bundles - 4.13
  images/cluster-nfd-operator.yml
  images/clusterresourceoverride-operator.yml
  images/ingress-node-firewall-operator.yml
  images/local-storage-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-efs-csi-driver-operator.yml
  images/ose-gcp-filestore-csi-driver-operator.yml
  images/ose-metallb-operator.yml
  images/ptp-operator.yml
  images/sriov-network-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#7012 ose-console mapping
  product.yml
Labels: lgtm, approved

#7013 Produce 4.20 nightlies by pinning a build
  releases.yml
Labels: lgtm, approved

#7030 Allow mismatched siblings for misbehaving operand of optional operator
  releases.yml
Labels: lgtm

#7017 [ART-13260] Disable cachi2 for several images in 4.17
  images/coredns.yml
  images/csi-driver-manila.yml
  images/dpu-cni.yml
  images/dpu-daemon.yml
  images/dpu-operator.yml
  images/golang-github-prometheus-alertmanager.yml
  images/ib-sriov-cni.yml
  images/kube-proxy.yml
  images/node-feature-discovery.yml
  images/oauth-server.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-provider-openstack.yml
  images/ose-machine-config-operator.yml
  images/ose-metallb.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-sriov-rdma-cni.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#7018 [ART-13260] Disable cachi2 for several images in 4.16
  images/baremetal-machine-controller.yml
  images/coredns.yml
  images/csi-driver-manila.yml
  images/golang-github-prometheus-alertmanager.yml
  images/ib-sriov-cni.yml
  images/node-feature-discovery.yml
  images/openshift-enterprise-console-operator.yml
  images/openshift-enterprise-hyperkube.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-aws-cluster-api-controllers.yml
  images/ose-azure-cluster-api-controllers.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-gcp-cluster-api-controllers.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-installer-kube-apiserver-artifacts.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-provider-openstack.yml
  images/ose-metallb.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-openstack-cloud-controller-manager.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#7038 Remove add modification for ib-sriov-cni in 4.19
  images/ib-sriov-cni.yml
Labels: lgtm, approved

#7039 Add adobes1 to OWNERS
  OWNERS
Labels: lgtm, approved

#7043 Add adobes1 to OWNERS
  OWNERS
Labels: lgtm, approved

#7042 Add adobes1 to OWNERS
  OWNERS
Labels: lgtm, approved

#7041 Add adobes1 to OWNERS
  OWNERS
Labels: lgtm, approved

#7050 4.18.19 ptp-operator fix
  releases.yml
Labels: lgtm, do-not-merge/hold
