Repository openshift-eng/ocp-build-data, pull requests merged in 2025-01, with the labels that each got.

#5930 4.17.11 pin builds
  releases.yml
Labels: lgtm

#5943 fix microshift build
  modifications/Dockerfile
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5960 enabled RHCOS for 4.19
  group.yml
Labels: lgtm, approved

#5961 rt repo: Use e4s for 9.4
  group.yml
Labels: lgtm, approved

#5964 rt repo: Use e4s for 9.4
  group.yml
Labels: lgtm, approved

#5965 [konflux] ironic cachito fix
  images/ironic.yml
Labels: lgtm

#5973 4.16.30 pin sriov builds
  releases.yml
Labels: lgtm, approved

#5978 Add Rayford to OWNERS
  OWNERS
Labels: lgtm, approved

#5986 Add Rayford to OWNERS
  OWNERS
Labels: lgtm, approved

#5985 Add Rayford to OWNERS
  OWNERS
Labels: lgtm, approved

#5976 update valid-subscription-label for pf-status-relay-operator
  images/pf-status-relay-operator.yml
Labels: lgtm, approved

#5974 Allow child images to add repos
  ci_images/dnf_wrapper.sh
  ci_images/dnf_wrapper_test.Dockerfile
  ci_images/install_dnf_wrapper.sh
  ci_images/rhel-8/ci-openshift-base/Dockerfile
  ci_images/rhel-9/ci-openshift-base/Dockerfile
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5988 Give golang image necessary env vars
  ci_images/install_dnf_wrapper.sh
  ci_images/rhel-8/ci-openshift-golang-builder/Dockerfile
  ci_images/rhel-9/ci-openshift-golang-builder/Dockerfile
Labels: lgtm, approved, acknowledge-critical-fixes-only

#5990 disable canonical_builder_from_upstream after rc start
  group.yml
Labels: lgtm, approved

#5999 Consume rhcos 96
  group.yml
  images/driver-toolkit.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6005 4.14.45: BLOCKER_BUGS permit
  releases.yml
Labels: lgtm, approved

#6009 Deal better with unshippable kernel
  group.yml
  releases.yml
Labels: lgtm, approved

#6014 add BLOCKER_BUGS flag to permits
  releases.yml
Labels: lgtm, approved

#6003 internal-only mode for ironic
  images/ironic.yml
Labels: lgtm, approved

#6019 DNF wrapper should not fail when not connected to VPN
  ci_images/dnf_wrapper.sh
  ci_images/dnf_wrapper_test.Dockerfile
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6027 OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo
  images/ose-olm-catalogd.yml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#6036 permit attached bugs
  releases.yml
Labels: lgtm, approved

#6035 pinning build ptp-operator-must-gather-container-v4.12.0-20250129105…
  releases.yml
Labels: lgtm, approved

#6032 [konflux] ironic reset network mode
  images/ironic.yml
Labels: lgtm, approved

#6041 scan-sources:noop [4.19] re-enable installer-artifacts for Konflux
  images/ose-installer-artifacts.yml
Labels: lgtm, approved

#6037 Add germanparente in OWNERS file for 4.14
  OWNERS
Labels: lgtm, approved

#6045 Update releases.yml
  releases.yml
Labels: lgtm, approved
