Repository openshift-eng/ocp-build-data, pull requests merged in 2025-03, with the labels that each got.

#6259 [4.18] secrets-store-csi-driver: update owners alias
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#6258 [4.19] secrets-store-csi-driver: update owners alias
  images/ose-secrets-store-csi-driver-operator.yml
  images/ose-secrets-store-csi-driver.yml
  images/ose-secrets-store-csi-mustgather.yml
Labels: lgtm, approved

#6039 Update OWNERS with san7ket
  OWNERS
Labels: lgtm, approved

#6263 Enable optional operators 4.19
  images/cluster-nfd-operator.yml
  images/openshift-kubernetes-nmstate-operator.yml
  images/ose-metallb-operator.yml
  images/vertical-pod-autoscaler-operator.yml
Labels: lgtm, approved

#6040 Update OWNERS with san7ket for 4.13
  OWNERS
Labels: lgtm, approved

#6147 ART-11740: remove ovirt-machine-controllers
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6269 [4.14][konflux] add modifications alibaba-cloud-csi-driver
  images/ose-alibaba-cloud-csi-driver.yml
Labels: lgtm, approved

#6268 [4.15][konflux] add modifications alibaba-cloud-csi-driver
  images/ose-alibaba-cloud-csi-driver.yml
Labels: lgtm, approved

#6266 ART-11740: 4.16: remove ovirt-machine-controllers
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6267 ART-11740: 4.15: remove ovirt-machine-controllers
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6264 ART-11740: 4.18: remove ovirt-machine-controllers
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6275 Revert "ART-11740: 4.18: remove ovirt-machine-controllers"
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6272 Revert "ART-11740: 4.15: remove ovirt-machine-controllers"
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6283 Revert "Revert "ART-11740: 4.18: remove ovirt-machine-controllers""
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6281 [konflux] add konflux_arches param in group.yaml
  group.yml
Labels: lgtm, approved

#6295 [konflux] terraform-providers use bigger VM
  images/ose-installer-terraform-providers.yml
Labels: do-not-merge/hold

#6301 4.19: added new signing advisory
  group.yml
Labels: lgtm, approved

#6308 [konflux] restrict arches to x86,arm
  group.yml
Labels: lgtm, approved

#6317 Enabling rebase tagging for impacted images
  images/ose-cluster-autoscaler-operator.yml
  images/ose-machine-api-operator.yml
  images/ose-machine-api-provider-aws.yml
  images/ose-machine-api-provider-azure.yml
  images/ose-machine-api-provider-gcp.yml
  images/ose-machine-api-provider-openstack.yml
Labels: lgtm, approved

#6324 [4.17] pin rhcos bug
  releases.yml
Labels: lgtm

#6325 Update releases.yml to include missing Bug
  releases.yml
Labels: lgtm, approved

#6330 Reapply "ART-11740: 4.15: remove ovirt-machine-controllers"
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6332 Fix goimport installation on go1.22
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved

#6333 No mass rebuild because of libxml2 for 4.19
  releases.yml
Labels: lgtm, approved

#6336 update ose-alibaba-cloud-csi-driver replace
  images/ose-alibaba-cloud-csi-driver.yml
Labels: lgtm, approved

#6340 Unfreeze 4.13
  group.yml
Labels: lgtm, approved

#6343 4.19 ec.3 pin cluster-nfd-operator
  releases.yml
Labels: lgtm, approved

#6346 internal-only
  images/microshift-bootc.yml
Labels: tide/merge-method-squash

#5992 Add intel vsp
  README.md
  product.yml
Labels: lgtm, approved

#6334 Change rhcos metadata url
  group.yml
Labels: lgtm, approved

#6253 Add component mapping for lifecycle-agent-operator-bundle-container
  product.yml
Labels: lgtm, approved

#6358 Update rhcos release browser for 4.18
  group.yml
Labels: lgtm, approved

#6359 Update rhcos release browser for 4.17
  group.yml
Labels: lgtm, approved

#6363 Update rhcos release browser for 4.13
  group.yml
Labels: lgtm, approved

#6360 Update rhcos release browser for 4.16
  group.yml
Labels: lgtm, approved

#6361 Update rhcos release browser for 4.15
  group.yml
Labels: lgtm, approved

#6362 Update rhcos release browser for 4.14
  group.yml
Labels: lgtm, approved

#6365 Added ose-azure-service-operator-container
  product.yml
Labels: lgtm, approved

#6366 update rhcos enabled repos
  group.yml
Labels: lgtm, approved

#6367 Route libreswan issues to OVN
  product.yml
Labels: lgtm, approved

#6342 ART-12284: Update `nodejs-rhel9` to node 22
  streams.yml
Labels: lgtm, approved, jira/valid-reference

#6402 ART-12297: adjustments for OCP 4.20 branch
  bug.yml
  erratatool.yml
  group.yml
  releases.yml
Labels: lgtm, approved, jira/valid-reference

#6404 routing for openshift-compliance-must-gather-container
  product.yml
Labels: lgtm, approved

#6406 added telco operators routing
  product.yml
Labels: lgtm, approved

#6409 automation for 4.20
  group.yml
Labels: lgtm, approved

#6405 ci build root images: No nobest
  ci_images/rhel-8/ci-openshift-build-root/Dockerfile
  ci_images/rhel-9/ci-openshift-build-root/Dockerfile
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6413 Try enabling x86_64 to fix scan-sources
  images/dpu-intel-ipu-p4sdk.yml
Labels: lgtm, approved

#6414 add x86_64 for dpu-intel-ipu-p4sdk
  images/dpu-intel-ipu-p4sdk.yml
Labels: lgtm, approved

#6442 ART-12101 remove csi-snapshot-validation-webhook in 4.19
  images/csi-snapshot-validation-webhook.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#6403 Prune "bring your own RHEL"-rpms for 4.19
  rpms/openshift.yml
  rpms/ose-aws-ecr-image-credential-provider.yml
  rpms/ose-azure-acr-image-credential-provider.yml
  rpms/ose-gcp-gcr-image-credential-provider.yml
Labels: lgtm, approved
