Repository openshift-eng/ocp-build-data, pull requests merged in 2025-04, with the labels that each got.

#6458 Prevent mass rebuilds dues to libgcrypt
  releases.yml
Labels: lgtm, approved

#6460 Avoid mass rebuild 4.16
  releases.yml
Labels: lgtm, approved

#6459 Prevent mass rebuilds due to libgcrypt
  releases.yml
Labels: lgtm, approved

#6466 [konflux] enable sast for bootc
  images/microshift-bootc.yml
Labels: lgtm, approved

#6474 Ignore openssl updates for 4.16
  releases.yml
Labels: lgtm, approved

#6470 Ignore openssl updates for 4.20
  releases.yml
Labels: lgtm, approved

#6473 Ignore openssl updates for 4.17
  releases.yml
Labels: lgtm, approved

#6472 Ignore openssl updates for 4.18
  releases.yml
Labels: lgtm, approved

#6481 Revert "Ignore openssl updates for 4.18"
  releases.yml
Labels: lgtm, approved

#6482 change for_payload
  images/aws-karpenter-provider-aws.yml
Labels: approved

#6483 ART-12451: add karpenter-provider-aws to product.yml
  product.yml
Labels: lgtm, approved, jira/valid-reference

#6486 [openshift-4.20] Switch to 10.1 repos for CI
  group.yml
Labels: lgtm, approved, tide/merge-method-squash

#6487 Revert "Ignore openssl updates for 4.17"
  releases.yml
Labels: lgtm, approved

#6494 add gparente to ownersfile
  OWNERS
Labels: lgtm, approved

#6524 Revert "Reapply "ART-11740: 4.16: remove ovirt-machine-controllers""
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6523 Prepare hotfix art12586
  releases.yml
Labels: approved

#6536 Remove Unnecessary enabled_repos Definitions from Image Configs
  images/local-storage-mustgather.yml
  images/openshift-enterprise-pod.yml
  images/openstack-resource-controller.yml
  images/ose-installer.yml
  images/ose-secrets-store-csi-mustgather.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm, approved

#6484 OAPE-35: [openshift-4.19] Add new requirements-build file for ansible-operator-plugins
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved, jira/valid-reference

#6548 remove repos which aren't required
  images/aws-karpenter-provider-aws.yml
Labels: approved

#6525 Revert "Revert "Reapply "ART-11740: 4.16: remove ovirt-machine-controllers"""
  images/ose-ovirt-machine-controllers.yml
Labels: lgtm, approved, jira/valid-reference

#6543 ART-12587: Remove descheduler images
  images/atomic-openshift-descheduler.yml
  images/ose-cluster-kube-descheduler-operator.yml
Labels: lgtm, jira/valid-reference

#6550 include payload_name for aws-karpenter-provider-aws
  images/aws-karpenter-provider-aws.yml
Labels: lgtm, approved

#6555 Inclusive bug sweep for 4.18
  bug.yml
Labels: lgtm, approved

#6554 Inclusive bug sweep for 4.19
  bug.yml
Labels: lgtm, approved

#6564 Set aliases for golang images
  group.yml
  streams.yml
Labels: lgtm, approved

#6546 Add `requirements-build1.txt` to `requirements_build_files` in `openshift-enterprise-ansible-operator.yml`
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm, approved

#6568 Add Sustaining ART members to owners file
  OWNERS
Labels: lgtm, approved

#6595 4.17.26 Exclude Bug
  releases.yml
Labels: lgtm, approved

#6589 add modification fix gomod vendor
  images/coredns.yml
  images/ose-aws-ebs-csi-driver.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-libvirt-machine-controllers.yml
  images/ose-machine-api-provider-openstack.yml
  images/ose-metallb.yml
  images/ose-vsphere-cloud-controller-manager.yml
Labels: lgtm

#6618 cachi2 updates
  images/coredns.yml
  images/csi-driver-manila.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-cluster-baremetal-operator.yml
  images/ose-ibm-vpc-block-csi-driver.yml
  images/ose-insights-operator.yml
  images/ose-machine-config-operator.yml
  images/ose-metallb.yml
  images/ose-openstack-cinder-csi-driver.yml
  images/ose-vsphere-cloud-controller-manager.yml
  images/ose-vsphere-cluster-api-controllers.yml
Labels: lgtm, approved

#6626 cachi2 images update
  images/ib-sriov-cni.yml
  images/node-feature-discovery.yml
  images/openshift-enterprise-console.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-ibmcloud-cluster-api-controllers.yml
  images/ose-network-tools.yml
  images/ptp-operator.yml
Labels: lgtm, approved

#6625 ovn images remove gomod
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-microshift.yml
Labels: lgtm

#6628 OKD-240: streams: add stream10 ocp builder in app.ci
  streams.yml
Labels: lgtm, approved, jira/valid-reference

#6652 4.20 - Fix build root stream name
  images/aws-karpenter-provider-aws.yml
Labels: lgtm, approved

#6588 Remove altinfra container
  product.yml
Labels: lgtm, approved

#6480 Add rhel10 ose repos
  group.yml
Labels: lgtm, approved

#6677 Prevent mass rebuild because of glibc
  releases.yml
Labels: lgtm, approved

#6676 Prevent mass rebuild for glibc
  releases.yml
Labels: lgtm, approved

#6680 Do not trigger rebuilds for pinned rpm
  images/ose-frr.yml
Labels: lgtm, approved

#6684 [4.18] Do not trigger rebuilds for pinned rpm
  images/ose-frr.yml
Labels: lgtm, approved

#6683 [4.17] Do not trigger rebuilds for pinned rpm
  images/ose-frr.yml
Labels: lgtm, approved

#6685 [4.16] Do not trigger rebuilds for pinned rpm
  images/ose-frr.yml
Labels: lgtm, approved

#6569 ART-12600: Enable layered rhcos
  group.yml
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#6689 ART-12600: Enable layered rhcos 4.20
  group.yml
Labels: lgtm, approved, jira/valid-reference

#6690 Revert "ART-12600: Enable layered rhcos 4.20"
  group.yml
Labels: jira/valid-reference

#6691 Revert "ART-12600: Enable layered rhcos"
  group.yml
Labels: jira/valid-reference

#6692 ART-12600 update rhcos config
  group.yml
Labels: lgtm, approved

#6693 ART-12600 update rhcos config
  group.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only
