Repository openshift-eng/ocp-build-data, pull requests merged in 2025-08, with the labels that each got.

#7317 ART-13260: Disable Konflux cachi2 for sriov-cni in 4.13
  images/sriov-cni.yml
Labels: lgtm, approved, jira/valid-reference

#7327 pin 4.14.55 releases.yml
  releases.yml
Labels: lgtm, approved

#7331 Update releases.yml to pin ose-frr in 4.14.55
  releases.yml
Labels: lgtm, approved

#7341 Correct bundle delivery repo for dpu-operator
  images/dpu-operator.yml
Labels: lgtm, approved

#7347 4.19.9: Include RHCOS bugs
  releases.yml
Labels: lgtm, approved

#7362 [4.209] Define pre-release permits
  releases.yml
Labels: lgtm

#7387 [4.21] Temporarily pin rhcos to 4.20
  group.yml
Labels: lgtm, approved

#7390 ART-14015 Establish go1.23 streams in 4.17
  group.yml
  images/ci-openshift-build-root-extra.rhel9.yml
  images/ci-openshift-golang-builder-extra.rhel9.yml
  streams.yml
Labels: lgtm, approved, tide/merge-method-squash

#7413 4.21: Only look for existing target versions
  bug.yml
Labels: lgtm, approved

#7424 4.20: No rhel10 builds of rpms
  rpms/openshift-clients.yml
  rpms/openshift.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#7426 Fix scan
  images/ose-insights-runtime-extractor.yml
Labels: lgtm, approved

#7434 Fix 4.20
  group.yml
  images/dpu-intel-ipu-vsp.yml
  images/driver-toolkit.yml
  images/linuxptp-daemon.yml
  images/openshift-base-rhel9.yml
  images/openshift-enterprise-builder.yml
  images/openshift-enterprise-egress-dns-proxy.yml
  images/openshift-enterprise-haproxy-router.yml
  images/openshift-kubernetes-nmstate-handler.yml
  images/ose-agent-installer-csr-approver.yml
  images/ose-agent-installer-node-agent.yml
  images/ose-agent-installer-utils.yml
  images/ose-image-customization-controller.yml
  images/ose-machine-config-operator.yml
  images/ose-ovn-kubernetes.yml
  images/ovn-kubernetes-base.yml
  rpms/openshift-clients.yml
  rpms/openshift.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#7435 Fix dpu-intel-ipu-p4sdk build
  images/dpu-intel-ipu-p4sdk.yml
Labels: lgtm, approved

#7447 Update group.yml
  group.yml
Labels: lgtm, approved

#7465 4.19.10 exclude bug
  releases.yml
Labels: lgtm

#7466 ansible operator remove artifact lockfile
  images/openshift-enterprise-ansible-operator.yml
Labels: lgtm

#7471 Fix 4.19 build problems
  images/dpu-intel-ipu-p4sdk.yml
  images/ose-agent-installer-node-agent.yml
Labels: lgtm, approved

#7472 Fix 4.20 build errors
  images/dpu-daemon.yml
  images/dpu-intel-ipu-p4sdk.yml
  images/ose-gcp-cloud-controller-manager.yml
Labels: lgtm, approved, acknowledge-critical-fixes-only

#7474 Fix kernel bug sweep
  bug.yml
Labels: lgtm, approved
